force-app/main/default/objects/Programme_Events__c/Programme_Events__c.object-meta.xml
<CustomObject>
    <label>Programme/ Event</label>
    <nameField>
        <label>Programme/ Events Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programme/ Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Programme_Events__c/fields/Active_Birthday_Programme__c.field-meta.xml
<CustomField>
    <fullName>Active_Birthday_Programme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active Birthday Programme</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Programme_Events__c/fields/Cancel_Programme_Event__c.field-meta.xml
<CustomField>
    <fullName>Cancel_Programme_Event__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cancel Programme/Event</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Programme_Events__c/fields/Engagement_Type__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Type__c</fullName>
    <inlineHelpText>Please Select Direct/Indirect Patient Involvement</inlineHelpText>
    <label>Engagement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Indirect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Programme_Events__c/fields/Event_Attire__c.field-meta.xml
<CustomField>
    <fullName>Event_Attire__c</fullName>
    <label>Event Attire</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Casual</fullName>
            </value>
            <value>
                <fullName>Smart Casual</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Programme_Events__c/fields/Programme_Description__c.field-meta.xml
<CustomField>
    <fullName>Programme_Description__c</fullName>
    <label>Programme Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Programme_Events__c/fields/Venue_of_Event_or_Mobilisation__c.field-meta.xml
<CustomField>
    <fullName>Venue_of_Event_or_Mobilisation__c</fullName>
    <label>Venue of Event or Mobilisation</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProgrammeEventClassTest.cls
@isTest
public class ProgrammeEventClassTest {
	@isTest
    public static void updateProgram() {
		Programme_Events__c programEventObj= new Programme_Events__c(
        name='testing1',
        Engagement_Type__c='Direct',
        Programme_Description__c='Test',
        Event_Attire__c='Casual',
        Venue_of_Event_or_Mobilisation__c='test',
        Start_Date_Time__c= Date.today(),
        End_Date_Time__c= Date.today(),
        Active_Birthday_Programme__c = true
        );
        insert programEventObj;
        
        Programme_Events__c programEventObj1= new Programme_Events__c(
        name='testing2',
        Engagement_Type__c='Direct',
        Programme_Description__c='Test',
        Event_Attire__c='Casual',
        Venue_of_Event_or_Mobilisation__c='test',
        Start_Date_Time__c= Date.today(),
        End_Date_Time__c= Date.today(),
        Active_Birthday_Programme__c = true
        );
        insert programEventObj1;
        
        Programme_Events__c programEventObj2= new Programme_Events__c(
        name='testin3g',
        Engagement_Type__c='Direct',
        Programme_Description__c='Test',
        Event_Attire__c='Casual',
        Venue_of_Event_or_Mobilisation__c='test',
        Start_Date_Time__c= Datetime.now().addDays(1),
        End_Date_Time__c= Datetime.now().addDays(3),
        Active_Birthday_Programme__c = false
        );
        insert programEventObj2;
        
        Programme_Events__c programEventObj3= new Programme_Events__c(
        name='testing1',
        Engagement_Type__c='Direct',
        Programme_Description__c='Test',
        Event_Attire__c='Casual',
        Venue_of_Event_or_Mobilisation__c='test',
        Start_Date_Time__c= Datetime.now().addDays(-2),
        End_Date_Time__c= Datetime.now().addDays(-1),
        Active_Birthday_Programme__c = true
        );
        insert programEventObj3;
        
        Programme_Events__c programEventObj4= new Programme_Events__c(
        name='testing1',
        Engagement_Type__c='Direct',
        Programme_Description__c='Test',
        Event_Attire__c='Casual',
        Venue_of_Event_or_Mobilisation__c='test',
        Active_Birthday_Programme__c = true
        );
        insert programEventObj4;
        
        //Update Started
        
        programEventObj2.Cancel_Programme_Event__c = true;
        programEventObj2.Active_Birthday_Programme__c = true;
        programEventObj2.Start_Date_Time__c= Date.today();
        programEventObj2.End_Date_Time__c= Date.today();
        update programEventObj2;
        
        //Update Ended
        programEventObj1.Start_Date_Time__c= Datetime.now().addDays(-2);
        programEventObj1.End_Date_Time__c= Datetime.now().addDays(-1);
        update programEventObj1;
        
        //Update Planned
        programEventObj.Start_Date_Time__c= Datetime.now().addDays(1);
        programEventObj.End_Date_Time__c= Datetime.now().addDays(3);
        update programEventObj;
        
        //Cancel
        programEventObj2.Cancel_Programme_Event__c = true;
        programEventObj2.Active_Birthday_Programme__c = true;
        update programEventObj2;
    }
}