force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Selected</fullName>
                <default>true</default>
                <label>Selected</label>
            </value>
            <value>
                <fullName>Invitation Sent</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Absent</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Withdraw</fullName>
                <label>Withdrawn</label>
            </value>
            <value>
                <fullName>Registered</fullName>
                <isActive>false</isActive>
                <label>Registered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ParticipantAcceptRejectController.cls
public class ParticipantAcceptRejectController {
	public Id participantId {get;set;}
    public Participant__c participantRecord {get;set;}
	public ParticipantAcceptRejectController(ApexPages.StandardController controller) {
        participantId = ApexPages.CurrentPage().getParameters().get('id'); 
        participantRecord = [SELECT Id, name
                                    , Status__c
                                    FROM Participant__c WHERE Id = :participantId
            ]; 
        if(participantRecord.Status__c <> 'Registered'){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING, 'This volunteer is not registered yet or already processed.'));
        }
    }
    
    public PageReference acceptVolunteer(){
        participantRecord.Status__c = 'Accepted';
        update(participantRecord);
        pageReference pg = new pageReference('/'+participantId);
        pg.setRedirect(true);
        return pg;
    }
    public PageReference declineVolunteer(){
        participantRecord.Status__c = 'Declined';
        update(participantRecord);
        pageReference pg = new pageReference('/'+participantId);
        pg.setRedirect(true);
        return pg;
    }
    public PageReference back(){
        pageReference pg = new pageReference('/'+participantId);
        pg.setRedirect(true);
        return pg;
    }
}