force-app/main/default/objects/Account/fields/ID_No__c.field-meta.xml
<CustomField>
    <fullName>ID_No__c</fullName>
    <externalId>true</externalId>
    <label>ID No.</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ID_Type__c.field-meta.xml
<CustomField>
    <fullName>ID_Type__c</fullName>
    <label>ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ASGD</fullName>
            </value>
            <value>
                <fullName>FIN</fullName>
            </value>
            <value>
                <fullName>ITR</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>NRIC</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>UEN</fullName>
            </value>
            <value>
                <fullName>UEN-Business</fullName>
            </value>
            <value>
                <fullName>UEN-Local Company</fullName>
            </value>
            <value>
                <fullName>UEN-Others</fullName>
            </value>
            <value>
                <fullName>UEN- Business</fullName>
                <isActive>false</isActive>
                <label>UEN- Business</label>
            </value>
            <value>
                <fullName>UEN- Local Company</fullName>
                <isActive>false</isActive>
                <label>UEN- Local Company</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Recipient_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Tax_Recipient_Full_Name__c</fullName>
    <label>Tax Recipient Full Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Organisation.recordType-meta.xml
<RecordType>
    <fullName>Organisation</fullName>
    <active>true</active>
    <label>Organisation</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Donor_Type__c.field-meta.xml
<CustomField>
    <fullName>Donor_Type__c</fullName>
    <defaultValue>if( $RecordType.DeveloperName = &apos;Contact&apos;, &apos;Organisation&apos;, null)</defaultValue>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Organisation</fullName>
            </value>
            <value>
                <fullName>Anonymous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ID_No__c.field-meta.xml
<CustomField>
    <fullName>ID_No__c</fullName>
    <externalId>true</externalId>
    <label>Tax Recipient ID No</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/ID_Type__c.field-meta.xml
<CustomField>
    <fullName>ID_Type__c</fullName>
    <label>Tax Recipient ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NRIC</fullName>
            </value>
            <value>
                <fullName>FIN</fullName>
            </value>
            <value>
                <fullName>UEN-Business</fullName>
            </value>
            <value>
                <fullName>UEN-Local Company</fullName>
            </value>
            <value>
                <fullName>UEN-Others</fullName>
            </value>
            <value>
                <fullName>ITR</fullName>
            </value>
            <value>
                <fullName>ASGD</fullName>
            </value>
            <value>
                <fullName>OTHERS</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
                <isActive>false</isActive>
                <label>BC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/isTaxRecipient__c.field-meta.xml
<CustomField>
    <fullName>isTaxRecipient__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isTaxRecipient</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Organisation_Name__c.field-meta.xml
<CustomField>
    <fullName>Organisation_Name__c</fullName>
    <label>Organisation Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Tax_Recipient_ID_No_Org__c.field-meta.xml
<CustomField>
    <fullName>Tax_Recipient_ID_No_Org__c</fullName>
    <label>Tax Recipient ID No (Org)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Tax_Recipient_Id_Type_Org__c.field-meta.xml
<CustomField>
    <fullName>Tax_Recipient_Id_Type_Org__c</fullName>
    <label>Tax Recipient Id Type (Org)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FIN</fullName>
            </value>
            <value>
                <fullName>UEN</fullName>
            </value>
            <value>
                <fullName>UEN-Business</fullName>
            </value>
            <value>
                <fullName>UEN-Local Company</fullName>
            </value>
            <value>
                <fullName>UEN-Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Individual.recordType-meta.xml
<RecordType>
    <fullName>Individual</fullName>
    <active>true</active>
    <label>Individual</label>
</RecordType>

force-app/main/default/classes/ContactTriggerTest.cls
@isTest
public class ContactTriggerTest {
    @TestSetup
    static void makeData(){
        List<Contact> contactsToInsert = new List<Contact>{
            new Contact(
                RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId(),
                Donor_Type__c = 'Individual',
                lastName = 'testSetup individual 1',
                Email = 'testSetup1@mail.com',
                ID_Type__c = 'NRIC',
                ID_No__c = 'NRIC-testSetup1',
                Tax_Recipient_Full_Name__c = 'testSetup individual 1'
            ),
            new Contact(
                RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId(),
                Donor_Type__c = 'Individual',
                lastName = 'testSetup individual 2',
                Email = null,
                ID_Type__c = 'FIN',
                ID_No__c = 'FIN-testSetup2',
                Tax_Recipient_Full_Name__c = 'testSetup individual 2',
                isTaxRecipient__c = true
            ),
            new Contact(
                RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId(),
                Donor_Type__c = 'Individual',
                lastName = 'testSetup individual 3',
                Email = 'testSetup3@mail.com',
                ID_Type__c = null,
                ID_No__c = null,
                Tax_Recipient_Full_Name__c = null
            ),
            new Contact(
                RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Contact').getRecordTypeId(),
                Donor_Type__c = 'Organisation',
                lastName = 'testSetup organisation 1',
                Email = 'testSetupOrganisation1@mail.com',
                Organisation_Name__c = 'Existing Organisation 1',
                Tax_Recipient_Id_Type_Org__c = 'UEN-Business',
                Tax_Recipient_ID_No_Org__c = 'UEN-testSetup1'
            )
        };

        Insert contactsToInsert;
    }

	@isTest
    public static void createAccount() {
        List<Account> testAccount = new List<Account>();
        testAccount.add(new Account(Name = 'test acc1'));
        testAccount.add(new Account(Name = 'test acc2'));
        
        insert testAccount;
        
        List<Contact> testContact = new List<Contact>();
    }
}