force-app/main/default/objects/Account/fields/ID_No__c.field-meta.xml
<CustomField>
    <fullName>ID_No__c</fullName>
    <externalId>true</externalId>
    <label>ID No.</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ID_Type__c.field-meta.xml
<CustomField>
    <fullName>ID_Type__c</fullName>
    <label>ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ASGD</fullName>
            </value>
            <value>
                <fullName>FIN</fullName>
            </value>
            <value>
                <fullName>ITR</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>NRIC</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>UEN</fullName>
            </value>
            <value>
                <fullName>UEN-Business</fullName>
            </value>
            <value>
                <fullName>UEN-Local Company</fullName>
            </value>
            <value>
                <fullName>UEN-Others</fullName>
            </value>
            <value>
                <fullName>UEN- Business</fullName>
                <isActive>false</isActive>
                <label>UEN- Business</label>
            </value>
            <value>
                <fullName>UEN- Local Company</fullName>
                <isActive>false</isActive>
                <label>UEN- Local Company</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Recipient_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Tax_Recipient_Full_Name__c</fullName>
    <label>Tax Recipient Full Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Volunteer_Status__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Status__c</fullName>
    <label>Volunteer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Unavailable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>true</active>
    <label>Household</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Organisation.recordType-meta.xml
<RecordType>
    <fullName>Organisation</fullName>
    <active>true</active>
    <label>Organisation</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Assignment_Status__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Status__c</fullName>
    <label>Assignment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Unavailable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/CS_Enquiry__c.field-meta.xml
<CustomField>
    <fullName>CS_Enquiry__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to identify if a contact is originating from CS Enquiry</description>
    <label>CS Enquiry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Donor_Type__c.field-meta.xml
<CustomField>
    <fullName>Donor_Type__c</fullName>
    <defaultValue>if( $RecordType.DeveloperName = &apos;Contact&apos;, &apos;Organisation&apos;, null)</defaultValue>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Organisation</fullName>
            </value>
            <value>
                <fullName>Anonymous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Dormant_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Dormant_End_Date__c</fullName>
    <label>Dormant End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Dormant_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Dormant_Start_Date__c</fullName>
    <label>Dormant Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ID_No__c.field-meta.xml
<CustomField>
    <fullName>ID_No__c</fullName>
    <externalId>true</externalId>
    <label>Tax Recipient ID No</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/ID_Type__c.field-meta.xml
<CustomField>
    <fullName>ID_Type__c</fullName>
    <label>Tax Recipient ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NRIC</fullName>
            </value>
            <value>
                <fullName>FIN</fullName>
            </value>
            <value>
                <fullName>UEN-Business</fullName>
            </value>
            <value>
                <fullName>UEN-Local Company</fullName>
            </value>
            <value>
                <fullName>UEN-Others</fullName>
            </value>
            <value>
                <fullName>ITR</fullName>
            </value>
            <value>
                <fullName>ASGD</fullName>
            </value>
            <value>
                <fullName>OTHERS</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
                <isActive>false</isActive>
                <label>BC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Imported__c.field-meta.xml
<CustomField>
    <fullName>Imported__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Imported</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ISS_Enquiry__c.field-meta.xml
<CustomField>
    <fullName>ISS_Enquiry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ISS Enquiry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/isTaxRecipient__c.field-meta.xml
<CustomField>
    <fullName>isTaxRecipient__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isTaxRecipient</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Last_Assignment_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Assignment_Date__c</fullName>
    <label>Last Assignment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Organisation_Name__c.field-meta.xml
<CustomField>
    <fullName>Organisation_Name__c</fullName>
    <label>Organisation Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Orientation_Completed__c.field-meta.xml
<CustomField>
    <fullName>Orientation_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Orientation Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Reason_of_Declined__c.field-meta.xml
<CustomField>
    <fullName>Reason_of_Declined__c</fullName>
    <label>Reason of Declined</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Resignation_Date__c.field-meta.xml
<CustomField>
    <fullName>Resignation_Date__c</fullName>
    <label>Resignation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Tax_Recipient_ID_No_Org__c.field-meta.xml
<CustomField>
    <fullName>Tax_Recipient_ID_No_Org__c</fullName>
    <label>Tax Recipient ID No (Org)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Tax_Recipient_Id_Type_Org__c.field-meta.xml
<CustomField>
    <fullName>Tax_Recipient_Id_Type_Org__c</fullName>
    <label>Tax Recipient Id Type (Org)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FIN</fullName>
            </value>
            <value>
                <fullName>UEN</fullName>
            </value>
            <value>
                <fullName>UEN-Business</fullName>
            </value>
            <value>
                <fullName>UEN-Local Company</fullName>
            </value>
            <value>
                <fullName>UEN-Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Volunteer__c.field-meta.xml
<CustomField>
    <fullName>Volunteer__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When the Volunteer Accepted Date is not blank</inlineHelpText>
    <label>Volunteer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Volunteer_accepted_date__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_accepted_date__c</fullName>
    <label>Volunteer accepted date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Volunteer_Activity_Status__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Activity_Status__c</fullName>
    <label>Volunteer Activity Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Volunteer_Status__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Status__c</fullName>
    <label>Volunteer Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
                <default>true</default>
                <label>Applied</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Resigned</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Individual.recordType-meta.xml
<RecordType>
    <fullName>Individual</fullName>
    <active>true</active>
    <label>Individual</label>
</RecordType>

force-app/main/default/classes/ContactTriggerHandler.cls
public with sharing class ContactTriggerHandler {
    public static List<String> idTypeIndividual = new List<String>{'NRIC', 'FIN'};
    public static List<String> idTypeOrganisation = new List<String>{'UEN', 'UEN-Business', 'UEN-Local Company', 'UEN-Others'};


    public static void checkEmailUnique(Contact[] newRecordList){
        List<String> emailCheckList = new List<String>();
        List<String> idNoCheckList = new List<String>();

        for(Contact cItem : newRecordList){
            if(cItem.Email != null){
                if(emailCheckList.contains(cItem.Email)){
                    cItem.addError('Duplicate email usage in the bulk import data');
                }
                else{
                    emailCheckList.add(cItem.Email); 
                }
            }

            if(cItem.ID_No__c != null){
                if(idNoCheckList.contains(cItem.ID_No__c)){
                    cItem.addError('Duplicate Id Number usage in the bulk import data');
                }
                else{
                    idNoCheckList.add(cItem.ID_No__c);
                }
            }
            
        }

    }


    public static void createAccount(Contact[] newRecordListRaw){
        List<Contact> newRecordList = new List<Contact>();

        for(Contact cItem : newRecordListRaw){
            if(!cItem.CS_Enquiry__c && !cItem.ISS_Enquiry__c ){
                newRecordList.add(cItem);
            }
        }

        if(newRecordList.size() > 0){
            try {
                // Duplicate email checking is handled by sf trigger
    
                // 1. Account Creation
                List<Account> accountToCreate = new List<Account>();
                
    
                Id anonymousAccountId = [
                    SELECT Id
                    FROM Account
                    WHERE Name = 'Anonymous'
                        AND RecordTypeId = :Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId()
                ]?.id;
    
                if(anonymousAccountId == null){
                    Account createAnon = new Account(
                        RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId(),
                        name = 'Anonymous'
                    );
                    Insert createAnon;
                    
                    anonymousAccountId = createAnon.id;
                }
    
    
                // check and retrieve for existing data
                // remove the duplicate rule in salesfor if this is success
                List<String> idNumberList = new List<String>();
                for(Contact cItem : newRecordList){
                    if( cItem.Tax_Recipient_Id_Type_Org__c != null
                        && cItem.RecordTypeId == Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Contact').getRecordTypeId()
                         && idTypeOrganisation.contains(cItem.Tax_Recipient_Id_Type_Org__c) ){
                        idNumberList.add(citem.Tax_Recipient_ID_No_Org__c);
                    }
                }
    
                List<Account> orgAccountExisted = ([
                    SELECT Id, ID_No__c
                    FROM Account
                    WHERE ID_No__c in :idNumberList
                ]);
    
                Map<String, Id> orgIdNoMap = new Map<String, Id>();
    
                for(Account aItem : orgAccountExisted){
                    orgIdNoMap.put(aItem.ID_No__c, aItem.id);
                }
                
                for(String item : orgIdNoMap.keySet()){
                    System.debug('\n\n item = ' + item );
                    System.debug('value = ' + orgIdNoMap.get(item) );
                }
    
    
    
                // compile list grouping
                for(Contact cItem : newRecordList){
                    System.debug('\n\ncItem.lastName \n' + cItem.lastName);
                    System.debug('\ncItem.isTaxRecipient__c \n' + cItem.isTaxRecipient__c);
                    System.debug('\ncItem.Email \n' + cItem.Email);
    
    
                    if( (cItem.isTaxRecipient__c == false || cItem.isTaxRecipient__c == null) && cItem.Email == null){
                        cItem.addError('Email is required if isTaxRecipient = false');
                    }
                    else{
                        System.debug('\n\nINSIDE the else \n');
                        Account AToAdd;
                        switch on cItem.Donor_Type__c {
                            when 'Organisation' {
                                System.debug('\n\ncItem.Tax_Recipient_ID_No_Org__c \n' + cItem.Tax_Recipient_ID_No_Org__c);
                                if(orgIdNoMap.containsKey(cItem.Tax_Recipient_ID_No_Org__c)){
                                    System.debug('\n\nMASUK \n');
                                    cItem.AccountId = orgIdNoMap.get(cItem.Tax_Recipient_ID_No_Org__c);
                                }
                                else{
                                    AToAdd = new Account(
                                        RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Organisation').getRecordTypeId(),
                                        Name = cItem.Organisation_Name__c,
                                        ID_Type__c = idTypeOrganisation.contains(cItem.Tax_Recipient_Id_Type_Org__c) ? cItem.Tax_Recipient_Id_Type_Org__c : null,
                                        ID_No__c = idTypeOrganisation.contains(cItem.Tax_Recipient_Id_Type_Org__c) ? cItem.Tax_Recipient_Id_No_Org__c : null
                                    );
                                    // accountToCreate.add(new Account(
                                    //     RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Organisation').getRecordTypeId(),
                                    //     Name = cItem.Organisation_Name__c,
                                    //     ID_Type__c = idTypeOrganisation.contains(cItem.Tax_Recipient_Id_Type_Org__c) ? cItem.Tax_Recipient_Id_Type_Org__c : null,
                                    //     ID_No__c = idTypeOrganisation.contains(cItem.Tax_Recipient_Id_Type_Org__c) ? cItem.Tax_Recipient_Id_No_Org__c : null
                                    // ));
    
                                }
    
                                
                            }
        
                            when 'Individual' {
                                AToAdd = new Account(
                                    RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId(),
                                    Name = cItem.lastName + ' Household',
                                    ID_Type__c = idTypeIndividual.contains(cItem.ID_Type__c) ? cItem.ID_Type__c : null,
                                    ID_No__c = idTypeIndividual.contains(cItem.ID_Type__c) ? cItem.ID_No__c : null,
                                    Tax_Recipient_Full_Name__c = idTypeIndividual.contains(cItem.ID_Type__c) ? cItem.lastName : null
                                );
                                // accountToCreate.add(new Account(
                                //     RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId(),
                                //     Name = cItem.lastName + ' Household',
                                //     ID_Type__c = idTypeIndividual.contains(cItem.ID_Type__c) ? cItem.ID_Type__c : null,
                                //     ID_No__c = idTypeIndividual.contains(cItem.ID_Type__c) ? cItem.ID_No__c : null,
                                //     Tax_Recipient_Full_Name__c = idTypeIndividual.contains(cItem.ID_Type__c) ? cItem.lastName : null
                                // ));
                                
                            }
        
                            when 'Anonymous' {
                                cItem.AccountId = anonymousAccountId;
                                cItem.lastName = 'Anonymous-'+ cItem.Email;
                            }
                            
                        }
    
                        if(AToAdd != null && accountToCreate.contains(AToAdd) == false){
                            accountToCreate.add(AToAdd);
                        }
                        
                    }
                    
                }
    
                for(Account aItem : accountToCreate){
                    System.Debug('\n\naccountToCreate aItem.name \n' + aItem.name);
                    System.Debug('accountToCreate aItem.ID_Type__c \n' + aItem.ID_Type__c);
                    System.Debug('accountToCreate aItem.ID_No__c \n' + aItem.ID_No__c);
                }
    
                // 2. Insert the Account
                Database.SaveResult[] dbInsertResult = Database.insert(accountToCreate, false);
    
                // compile for account map for successfull creation
                Map<String, Id> accountMap = new Map<String, Id>();
                for(Account accItem : accountToCreate ){
                    if(accItem.Id != null){
                        accountMap.put(accItem.Name.toLowerCase()
                                    + ' - ' 
                                    + accItem.ID_Type__c 
                                    + ' - ' 
                                    + accItem.ID_No__c
                                    , accItem.Id);
                    }
                    
                }
    
                // change account map property where the account name already existed
                for(Database.SaveResult sr : dbInsertResult){
                    System.Debug('\n\ndbInsertResult sr \n' + sr);
                    if(!sr.isSuccess()){
                        System.Debug('\n\nNOT SUCCESS \n' + sr.getErrors());
                        for(Database.Error duplicateError : sr.getErrors()){
                            Datacloud.DuplicateResult duplicateResult = 
                                ((Database.DuplicateError)duplicateError).getDuplicateResult();
                            
                            
                            SObject matchRecord = duplicateResult.getMatchResults()[0].getMatchRecords()[0].getRecord();
                            System.Debug('\n\nmatchRecord \n' + matchRecord);
                            String accountName = (String) matchRecord.get('Name');
                            accountMap.put(accountName.toLowerCase()
                                                + ' - ' 
                                                + matchRecord.get('ID_Type__c')
                                                + ' - '
                                                + matchRecord.get('ID_No__c')
                                                , matchRecord.Id);
    
                        }
                    }
    
                }
    
                for(String key : accountMap.keySet()){
                    System.Debug('\n\naccountMap key : ' + key);
                    System.Debug(accountMap.get(key));
    
                }
       
    
                // 3. Tag contact to the accountId accordingly
                for(Contact cItem : newRecordList){
                    if(cItem.AccountId == null){
                        System.debug('\n\nMASUK DONG \n');
                        switch on cItem.Donor_Type__c {
                            when 'Individual' {
                                cItem.AccountId = accountMap.get(
                                    (cItem.lastname + ' Household').toLowerCase()
                                    + ' - '
                                    + cItem.ID_Type__c
                                    + ' - '
                                    + cItem.ID_No__c
                                );
                                
                            }
        
                            when 'Organisation' {
                                cItem.AccountId = accountMap.get(
                                    cItem.Organisation_Name__c.toLowerCase()
                                    + ' - '
                                    + cItem.Tax_Recipient_Id_Type_Org__c
                                    + ' - '
                                    + cItem.Tax_Recipient_Id_No_Org__c
                                );
                            }
                        }
                        
                    }
                    
                    System.debug('\n\ncItem.lastName \n' + cItem.lastName);
                    System.debug('cItem.AccountId \n' + cItem.AccountId);
                    if(cItem.AccountId == null){
                        System.debug('\n\nthrow error acccountid blank \n');
                        cItem.addError('Can\'t create Account, check for duplicate possibility'); 
                    }
                  
                }
    
                
            } catch (Exception err) {
                CustomException.printErrorInfo('contactTriggerHandler.createAccount', err) ;
                Trigger.new[0].addError(err.getMessage());
            }
            
        }
    }


    public static void sendWelcomeEmailFirstTime(Contact[] newRecordList){
        List<Id> contactIdToSendList = new List<Id>();

        for(Contact cItem : newRecordList){
            if(!cItem.Imported__c && String.isNotBlank(cItem.Email) && cItem.Volunteer__c){
                contactIdToSendList.add(cItem.Id);
            }
        }
        
        if(contactIdToSendList?.size() > 0){
            Utils.sendMassEmail(contactIdToSendList, 'Welcome Email');
        }
    }


    public static void sendWelcomeEmailUpdate(Contact[] newRecordList, Map<Id, Contact> oldRecordMap){
        List<Id> contactIdToSendList = new List<Id>();

        for(Contact cItem : newRecordList){
            if(!oldRecordMap.get(cItem.Id).Volunteer__c && cItem.Volunteer__c){
                contactIdToSendList.add(cItem.Id);
            }
        }
        
        if(contactIdToSendList?.size() > 0){
            Utils.sendMassEmail(contactIdToSendList, 'Welcome Email');
        }

    }


	public static void setVolunteerStatus(List<Contact> listNew){
        Date lastFY;
        if(Date.today().month() > 7) lastFY = Date.newInstance(Date.today().year(), 7, 1);
        else lastFY = Date.newInstance(Date.today().year()-1, 7, 1);    
        for(Contact c : listNew){
            if(c.Volunteer__c){
                if(c.Resignation_Date__c <> null){
                    c.Volunteer_Status__c = 'Resigned';
                    c.Assignment_Status__c = 'Unavailable';
                }
                if(c.Reason_of_Declined__c <> null){
                        c.Volunteer_Status__c = 'Declined';
                        c.Assignment_Status__c = 'Unavailable';
                }
                if(c.Dormant_Start_Date__c != null && c.Dormant_End_Date__c != null){
                    if(c.Dormant_Start_Date__c <= Date.today() && c.Dormant_End_Date__c >= Date.today() ){
                        c.Volunteer_Activity_Status__c = 'Dormant';
                        c.Assignment_Status__c = 'Unavailable';
                    }else{
                        if(c.Orientation_Completed__c){
                            c.Assignment_Status__c = 'Available';
                        }else{
                            c.Assignment_Status__c = 'Pending';
                        }
                        if(c.Last_Assignment_Date__c != null){
                            if(c.Last_Assignment_Date__c > lastFY){
                                c.Volunteer_Activity_Status__c = 'Active';
                            }else{
                                c.Volunteer_Activity_Status__c = 'Inactive';
                            }
                        }else{
                             c.Volunteer_Activity_Status__c = 'Pending';
                        }
                    }
                }
                if(c.Dormant_Start_Date__c == null && c.Dormant_End_Date__c == null && c.Resignation_Date__c == null && c.Reason_of_Declined__c == null){  
                    if(c.Orientation_Completed__c){
                        c.Volunteer_Status__c = 'Accepted';
                        c.Assignment_Status__c = 'Available';
                    }else if(c.Volunteer_Accepted_Date__c <> null){
                        c.Volunteer_Status__c = 'Accepted';
                        c.Assignment_Status__c = 'Pending';
                    }else if(c.Reason_of_Declined__c <> null){
                        c.Volunteer_Status__c = 'Declined';
                        c.Assignment_Status__c = 'Unavailable';
                    }else{
                        c.Volunteer_Status__c = 'Applied';
                        c.Assignment_Status__c = 'Pending';
                    }
                    if(c.Last_Assignment_Date__c != null){
                        if(c.Last_Assignment_Date__c > lastFY){
                            c.Volunteer_Activity_Status__c = 'Active';
                        }else{
                            c.Volunteer_Activity_Status__c = 'Inactive';
                        }
                    }else{
                        c.Volunteer_Activity_Status__c = 'Pending';
                    }
                }
        	}
        }
    }
    
    public static void createTask(List<Contact> listNew){
        
        system.debug('@@@'+ listNew);
        date todayDate = date.today(); 
        List<Task> tskList = new List<Task>();
        
        for(Contact c : listNew)
        {
            if(!c.Imported__c && c.Volunteer__c == true){
                Task tsk = new Task();
                tsk.Status='Not Started';
                tsk.Priority='High';
                tsk.ActivityDate = AddBusinessDays(todayDate,5); //Due Date
                if(c.FirstName != null){
                    tsk.Subject = 'Volunteer Interview with'+' '+ c.FirstName+' '+c.LastName;                
                }else{
                    tsk.Subject = 'Volunteer Interview with'+' '+ c.LastName;
                }
                tsk.Status = 'Not Started';
                tsk.Priority = 'High';
                tsk.WhoId = c.Id;
                tsk.WhatId = c.AccountId; //RelatedTO Id
                tsk.OwnerId = c.OwnerId; // AssignTo Id
                
                tskList.add(tsk);
            }            
        }
        if(tskList!=null && tskList.size()>0){
            insert tskList;
            
        }       
    }
    
    public static void createTask(List<Contact> listNew, Map<Id, Contact> oldMap){
        
        system.debug('@@@'+ listNew);
        date todayDate = date.today(); 
        List<Task> tskList = new List<Task>();
        
        for(Contact c : listNew)
        {
            if(!c.Imported__c && c.Volunteer__c == true && oldMap.get(c.Id).Volunteer__c == false){
                Task tsk = new Task();
                tsk.Status='Not Started';
                tsk.Priority='High';
                tsk.ActivityDate = AddBusinessDays(todayDate,5); //Due Date
                if(c.FirstName != null){
                    tsk.Subject = 'Volunteer Interview with'+' '+ c.FirstName+' '+c.LastName;                
                }else{
                    tsk.Subject = 'Volunteer Interview with'+' '+ c.LastName;
                }
                tsk.Status = 'Not Started';
                tsk.Priority = 'High';
                tsk.WhoId = c.Id;
                tsk.WhatId = c.AccountId; //RelatedTO Id
                tsk.OwnerId = c.OwnerId; // AssignTo Id
                
                tskList.add(tsk);
            }            
        }
        if(tskList!=null && tskList.size()>0){
            insert tskList;
            
        }       
    }
    
	public static Date AddBusinessDays(Date StartDate, integer BusinessDaysToAdd ){
        //Add or decrease in BusinessDaysToAdd days 
        Date finalDate = StartDate;
        system.debug('finaldate = '+finalDate);
        integer direction = BusinessDaysToAdd < 0 ? -1 : 1;
        system.debug('direction = '+direction);
        while(BusinessDaysToAdd != 0){
            finalDate = finalDate.AddDays(direction);
            system.debug('BusinessDaysToAdd = '+BusinessDaysToAdd);            
            system.debug('finaldate = '+finalDate);
            if (!isWeekendDay(finalDate)){
                BusinessDaysToAdd -= direction;
                
            }
        }
        return finalDate;
    }
    
    public static Boolean IsWeekendDay(Date dateParam){
        boolean result     = false;
        system.debug('dateParam = '+dateParam); 
        //Recover the day of the week
        Date startOfWeek   = dateParam.toStartOfWeek();
        system.debug('startOfWeek = '+startOfWeek);
        Integer dayOfWeek  = dateParam.day() - startOfWeek.day();
        system.debug('dayOfWeek = '+dayOfWeek);   
        result = dayOfWeek == 0 || dayOfWeek == 6 ? true : false;
        system.debug('result = '+result); 
        return result;
    } 
}