force-app/main/default/objects/Account/fields/ID_No__c.field-meta.xml
<CustomField>
    <fullName>ID_No__c</fullName>
    <externalId>true</externalId>
    <label>ID No.</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ID_Type__c.field-meta.xml
<CustomField>
    <fullName>ID_Type__c</fullName>
    <label>ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ASGD</fullName>
            </value>
            <value>
                <fullName>FIN</fullName>
            </value>
            <value>
                <fullName>ITR</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>NRIC</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>UEN</fullName>
            </value>
            <value>
                <fullName>UEN-Business</fullName>
            </value>
            <value>
                <fullName>UEN-Local Company</fullName>
            </value>
            <value>
                <fullName>UEN-Others</fullName>
            </value>
            <value>
                <fullName>UEN- Business</fullName>
                <isActive>false</isActive>
                <label>UEN- Business</label>
            </value>
            <value>
                <fullName>UEN- Local Company</fullName>
                <isActive>false</isActive>
                <label>UEN- Local Company</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Recipient_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Tax_Recipient_Full_Name__c</fullName>
    <label>Tax Recipient Full Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>true</active>
    <label>Household</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Organisation.recordType-meta.xml
<RecordType>
    <fullName>Organisation</fullName>
    <active>true</active>
    <label>Organisation</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Donor_Type__c.field-meta.xml
<CustomField>
    <fullName>Donor_Type__c</fullName>
    <defaultValue>if( $RecordType.DeveloperName = &apos;Contact&apos;, &apos;Organisation&apos;, null)</defaultValue>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Organisation</fullName>
            </value>
            <value>
                <fullName>Anonymous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ID_No__c.field-meta.xml
<CustomField>
    <fullName>ID_No__c</fullName>
    <externalId>true</externalId>
    <label>Tax Recipient ID No</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/ID_Type__c.field-meta.xml
<CustomField>
    <fullName>ID_Type__c</fullName>
    <label>Tax Recipient ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NRIC</fullName>
            </value>
            <value>
                <fullName>FIN</fullName>
            </value>
            <value>
                <fullName>UEN-Business</fullName>
            </value>
            <value>
                <fullName>UEN-Local Company</fullName>
            </value>
            <value>
                <fullName>UEN-Others</fullName>
            </value>
            <value>
                <fullName>ITR</fullName>
            </value>
            <value>
                <fullName>ASGD</fullName>
            </value>
            <value>
                <fullName>OTHERS</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
                <isActive>false</isActive>
                <label>BC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/isTaxRecipient__c.field-meta.xml
<CustomField>
    <fullName>isTaxRecipient__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isTaxRecipient</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Organisation_Name__c.field-meta.xml
<CustomField>
    <fullName>Organisation_Name__c</fullName>
    <label>Organisation Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Tax_Recipient_ID_No_Org__c.field-meta.xml
<CustomField>
    <fullName>Tax_Recipient_ID_No_Org__c</fullName>
    <label>Tax Recipient ID No (Org)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Tax_Recipient_Id_Type_Org__c.field-meta.xml
<CustomField>
    <fullName>Tax_Recipient_Id_Type_Org__c</fullName>
    <label>Tax Recipient Id Type (Org)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FIN</fullName>
            </value>
            <value>
                <fullName>UEN</fullName>
            </value>
            <value>
                <fullName>UEN-Business</fullName>
            </value>
            <value>
                <fullName>UEN-Local Company</fullName>
            </value>
            <value>
                <fullName>UEN-Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Individual.recordType-meta.xml
<RecordType>
    <fullName>Individual</fullName>
    <active>true</active>
    <label>Individual</label>
</RecordType>

force-app/main/default/objects/Donations__c/Donations__c.object-meta.xml
<CustomObject>
    <label>Donations</label>
    <nameField>
        <displayFormat>{yy}{mm}-{000000}</displayFormat>
        <label>Donation No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Donations__c/fields/Cleared_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Cleared_Datetime__c</fullName>
    <label>Cleared Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donation_Amount__c.field-meta.xml
<CustomField>
    <fullName>Donation_Amount__c</fullName>
    <label>Donation Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donation_Date__c.field-meta.xml
<CustomField>
    <fullName>Donation_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Donation Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donation_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Donation_Datetime__c</fullName>
    <label>Donation Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donation_Status__c.field-meta.xml
<CustomField>
    <fullName>Donation_Status__c</fullName>
    <defaultValue>&apos;Pending&apos;</defaultValue>
    <label>Donation Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Payment_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>Cheque Returned</fullName>
            </value>
            <value>
                <fullName>Giro Rejected</fullName>
            </value>
            <value>
                <fullName>CC Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donor_Account__c.field-meta.xml
<CustomField>
    <fullName>Donor_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Will be filled by trigger</description>
    <inlineHelpText>Don&apos;t need to be manually filled, will be automatically overwritten by trigger,</inlineHelpText>
    <label>Donor Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donor_Name__c.field-meta.xml
<CustomField>
    <fullName>Donor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the person who made the donation and paid for it</description>
    <label>Donor Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Donor_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donor_Type__c.field-meta.xml
<CustomField>
    <fullName>Donor_Type__c</fullName>
    <label>Donor Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Organisation</fullName>
            </value>
            <value>
                <fullName>Anonymous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Email_Entered__c.field-meta.xml
<CustomField>
    <fullName>Email_Entered__c</fullName>
    <label>Email (Entered)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Full_Name_Entered__c.field-meta.xml
<CustomField>
    <fullName>Full_Name_Entered__c</fullName>
    <label>Full Name (Entered)</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Id_No__c.field-meta.xml
<CustomField>
    <fullName>Id_No__c</fullName>
    <formula>Donor_Name__r.ID_No__c</formula>
    <label>Donor Id No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/ID_Type__c.field-meta.xml
<CustomField>
    <fullName>ID_Type__c</fullName>
    <formula>Text(  Donor_Name__r.ID_Type__c )</formula>
    <label>Donor Id Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/ID_Type_Entered__c.field-meta.xml
<CustomField>
    <fullName>ID_Type_Entered__c</fullName>
    <label>Tax Recipient Id Type (Entered)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ASGD</fullName>
            </value>
            <value>
                <fullName>FIN</fullName>
            </value>
            <value>
                <fullName>ITR</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>NRIC</fullName>
            </value>
            <value>
                <fullName>OTHERS</fullName>
            </value>
            <value>
                <fullName>UEN</fullName>
            </value>
            <value>
                <fullName>UEN-Business</fullName>
            </value>
            <value>
                <fullName>UEN-Local Company</fullName>
            </value>
            <value>
                <fullName>UEN-Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>eNETS</fullName>
            </value>
            <value>
                <fullName>Giro</fullName>
            </value>
            <value>
                <fullName>PayNow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Tax_Recipient_Individual__c.field-meta.xml
<CustomField>
    <fullName>Tax_Recipient_Individual__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Recipient Individual</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Donations (Tax Recipient Contact)</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Tax_Recipient_Organisation__c.field-meta.xml
<CustomField>
    <fullName>Tax_Recipient_Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Recipient Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Donations (Tax Recipient Organisation)</relationshipLabel>
    <relationshipName>Donations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donations__c/recordTypes/Cash.recordType-meta.xml
<RecordType>
    <fullName>Cash</fullName>
    <active>true</active>
    <label>Cash</label>
</RecordType>

force-app/main/default/objects/Programme_Events__c/Programme_Events__c.object-meta.xml
<CustomObject>
    <label>Programme/ Event</label>
    <nameField>
        <label>Programme/ Events Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programme/ Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Programme_Events__c/fields/Event_Attire__c.field-meta.xml
<CustomField>
    <fullName>Event_Attire__c</fullName>
    <label>Event Attire</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Casual</fullName>
            </value>
            <value>
                <fullName>Smart Casual</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Programme_Events__c/fields/Programme_Description__c.field-meta.xml
<CustomField>
    <fullName>Programme_Description__c</fullName>
    <label>Programme Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DonationsTriggerHandlerTest.cls
@isTest
public with sharing class DonationsTriggerHandlerTest {
    @testSetup
    static void makeData(){
        Account anonAccount = new Account(
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId(),
            Name = 'Anonymous'
        );
        Database.insert(anonAccount);


        List<Contact> contactsToInsert = new List<Contact>{
            new Contact(
                RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId(),
                Donor_Type__c = 'Individual',
                lastName = 'testSetup individual 1',
                Email = 'testSetup1@mail.com',
                ID_Type__c = 'NRIC',
                ID_No__c = 'NRIC-testSetup1',
                Tax_Recipient_Full_Name__c = 'testSetup individual 1'
            ),
            new Contact(
                RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId(),
                Donor_Type__c = 'Individual',
                lastName = 'testSetup individual 2',
                Email = null,
                ID_Type__c = 'FIN',
                ID_No__c = 'FIN-testSetup2',
                Tax_Recipient_Full_Name__c = 'testSetup individual 2',
                isTaxRecipient__c = true
            ),
            new Contact(
                RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId(),
                Donor_Type__c = 'Individual',
                lastName = 'testSetup individual 3',
                Email = 'testSetup3@mail.com',
                ID_Type__c = null,
                ID_No__c = null,
                Tax_Recipient_Full_Name__c = null
            ),
            new Contact(
                RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Contact').getRecordTypeId(),
                Donor_Type__c = 'Organisation',
                lastName = 'testSetup organisation 1',
                Email = 'testSetupOrganisation1@mail.com',
                Organisation_Name__c = 'Existing Organisation 1',
                Tax_Recipient_Id_Type_Org__c = 'UEN-Business',
                Tax_Recipient_ID_No_Org__c = 'UEN-testSetup1'
            )
        };
        Database.insert(contactsToInsert);

        Programme_Events__c programmeTest = new Programme_Events__c(
            Name = 'Test Programme',
            Start_Date_Time__c = System.today(),
            End_Date_Time__c = Date.today().addDays(7),
            Event_Attire__c = 'Casual',
            Programme_Description__c = 'Testing'
        );

        Database.insert(programmeTest);


    }

    @isTest
    // Scenario :
    // create a donation with new contact detail
    public static void createDonation1(){
        Donations__c donationsToInsert = new Donations__c(
            RecordTypeId = Schema.SObjectType.Donations__c.getRecordTypeInfosByName().get('Cash').getRecordTypeId(),
            Donor_Type__c = 'Individual',
            Donation_Status__c = 'Cleared',
            Donation_Date__c = System.today(),
            Donation_Datetime__c = System.now(),
            Cleared_Datetime__c = System.now(),
            Full_Name_Entered__c = 'Test 1',
            Email_Entered__c = 'test1@mail.com',
            Donation_Amount__c = 100,
            Payment_Method__c = 'Credit Card'
        );

        Insert donationsToInsert;
        
        donationsToInsert = [
            SELECT Id, Donor_Name__c, Donor_Account__c,  Tax_Recipient_Individual__c, Tax_Recipient_Organisation__c
            FROM Donations__c
            WHERE id = :donationsToInsert.id
        ];
        System.assert(donationsToInsert.Donor_Name__c != null);
        System.assert(donationsToInsert.Donor_Account__c != null);
        System.assert(donationsToInsert.Tax_Recipient_Individual__c == null);
        System.assert(donationsToInsert.Tax_Recipient_Organisation__c == null);
    }


    @isTest
    // Scenario : 
    // create a donation with new contact detail
    // and tax recipient to the same donor
    public static void createDonation2(){
        Donations__c donationToInsert = new Donations__c(
            RecordTypeId = Schema.SObjectType.Donations__c.getRecordTypeInfosByName().get('Cash').getRecordTypeId(),
            Donor_Type__c = 'Individual',
            Donation_Status__c = 'Cleared',
            Donation_Date__c = System.today(),
            Donation_Datetime__c = System.now(),
            Cleared_Datetime__c = System.now(),
            Full_Name_Entered__c = 'Test Individual 1',
            Email_Entered__c = 'test1@mail.com',
            ID_Type_Entered__c = 'NRIC',
            Tax_Recipient_ID_No_Entered__c = 'NRIC-test1',
            Tax_Recipient_Full_Name_Entered__c = 'Test Individual 1',
            Donation_Amount__c = 100,
            Payment_Method__c = 'Credit Card'
        );

        Insert donationToInsert;
    }


    @isTest
    // Scenario : 
    // create a donation with existing Contact as donor
    // and tax recipient to the same existing Contact
    public static void createDonation3(){

        Donations__c donationToInsert = new Donations__c(
            RecordTypeId = Schema.SObjectType.Donations__c.getRecordTypeInfosByName().get('Cash').getRecordTypeId(),
            Donor_Type__c = 'Individual',
            Donation_Status__c = 'Cleared',
            Donation_Date__c = System.today(),
            Donation_Datetime__c = System.now(),
            Cleared_Datetime__c = System.now(),
            Full_Name_Entered__c = 'testSetup individual 1',
            Email_Entered__c = 'testSetup1@mail.com',
            Address_Entered__c = 'Street 1',
            Address_Unit_Entered__c = '101',
            Address_Postal_Code_Entered__c = '123451',
            ID_Type_Entered__c = 'NRIC',
            Tax_Recipient_ID_No_Entered__c = 'NRIC-testSetup1',
            Tax_Recipient_Full_Name_Entered__c = 'testSetup individual 1',
            Donation_Amount__c = 100,
            Payment_Method__c = 'Credit Card'
        );

        Insert donationToInsert;
    }


    @isTest
    // Scenario : 
    // create a donation with a new Organisation Contact 
    // and tax recipient to the Organisation
    public static void createDonation4(){

        Donations__c donationToInsert = new Donations__c(
            RecordTypeId = Schema.SObjectType.Donations__c.getRecordTypeInfosByName().get('Cash').getRecordTypeId(),
            Donor_Type__c = 'Organisation',
            Donation_Status__c = 'Cleared',
            Donation_Date__c = System.today(),
            Donation_Datetime__c = System.now(),
            Cleared_Datetime__c = System.now(),
            Full_Name_Entered__c = 'Test Organisation 1',
            Email_Entered__c = 'testOrg1@mail.com',
            Address_Entered__c = 'Street 1',
            Address_Unit_Entered__c = '101',
            Address_Postal_Code_Entered__c = '123451',
            Organisation_Name_Entered__c = 'Organisation 1',
            ID_Type_Entered__c = 'UEN',
            Tax_Recipient_ID_No_Entered__c = 'UEN-ORG 1',
            Tax_Recipient_Full_Name_Entered__c = 'Organisation 1',
            Donation_Amount__c = 100,
            Payment_Method__c = 'Credit Card'
        );

        Insert donationToInsert;
    }


    @isTest
    // Scenario : 
    // create a donation with existing Organisation Contact 
    // and tax recipient to the Organisation
    public static void createDonation5(){
        Donations__c donationToInsert = new Donations__c(
            RecordTypeId = Schema.SObjectType.Donations__c.getRecordTypeInfosByName().get('Cash').getRecordTypeId(),
            Donor_Type__c = 'Organisation',
            Donation_Status__c = 'Cleared',
            Donation_Date__c = System.today(),
            Donation_Datetime__c = System.now(),
            Cleared_Datetime__c = System.now(),
            Full_Name_Entered__c = 'Test Organisation 1',
            Email_Entered__c = 'testOrg1@mail.com',
            Address_Entered__c = 'Street 1',
            Address_Unit_Entered__c = '101',
            Address_Postal_Code_Entered__c = '123451',
            Organisation_Name_Entered__c = 'Existing Organisation 1',
            ID_Type_Entered__c = 'UEN-Business',
            Tax_Recipient_ID_No_Entered__c = 'UEN-testSetup1',
            Tax_Recipient_Full_Name_Entered__c = 'Existing Organisation 1',
            Donation_Amount__c = 100,
            Payment_Method__c = 'Credit Card'
        );

        Insert donationToInsert;
    }



    @isTest
    // Scenario : 
    // create a donation with new Individual Email
    // and tax recipient to an existing contact which has blank email 
    // donor full name = tax recipient full name
    public static void createDonation6a(){
        Donations__c donationToInsert = new Donations__c(
            RecordTypeId = Schema.SObjectType.Donations__c.getRecordTypeInfosByName().get('Cash').getRecordTypeId(),
            Donor_Type__c = 'Individual',
            Donation_Status__c = 'Cleared',
            Donation_Date__c = System.today(),
            Donation_Datetime__c = System.now(),
            Cleared_Datetime__c = System.now(),
            Full_Name_Entered__c = 'testSetup individual 2',
            Email_Entered__c = 'test2@mail.com',
            Address_Entered__c = 'Street 1',
            Address_Unit_Entered__c = '101',
            Address_Postal_Code_Entered__c = '123451',
            ID_Type_Entered__c = 'FIN',
            Tax_Recipient_ID_No_Entered__c = 'FIN-testSetup2',
            Tax_Recipient_Full_Name_Entered__c = 'testSetup individual 2',
            Donation_Amount__c = 100,
            Payment_Method__c = 'Credit Card'
        );

        Insert donationToInsert;
    }


    @isTest
    // Scenario : 
    // create a donation with new Individual Email
    // and tax recipient to an existing contact which has blank email 
    // donor full name != tax recipient full name
    public static void createDonation6b(){
        Donations__c donationToInsert = new Donations__c(
            RecordTypeId = Schema.SObjectType.Donations__c.getRecordTypeInfosByName().get('Cash').getRecordTypeId(),
            Donor_Type__c = 'Individual',
            Donation_Status__c = 'Cleared',
            Donation_Date__c = System.today(),
            Donation_Datetime__c = System.now(),
            Cleared_Datetime__c = System.now(),
            Full_Name_Entered__c = 'testSetup individual 3',
            Email_Entered__c = 'test3@mail.com',
            Address_Entered__c = 'Street 1',
            Address_Unit_Entered__c = '101',
            Address_Postal_Code_Entered__c = '123451',
            ID_Type_Entered__c = 'FIN',
            Tax_Recipient_ID_No_Entered__c = 'FIN-testSetup2',
            Tax_Recipient_Full_Name_Entered__c = 'testSetup individual 2',
            Donation_Amount__c = 100,
            Payment_Method__c = 'Credit Card'
        );

        Insert donationToInsert;
    }



    @isTest
    // Scenario : 
    // create a donation with new Individual Email
    // and tax recipient to an existing contact which has email 
    public static void createDonation7(){
        Donations__c donationToInsert = new Donations__c(
            RecordTypeId = Schema.SObjectType.Donations__c.getRecordTypeInfosByName().get('Cash').getRecordTypeId(),
            Donor_Type__c = 'Individual',
            Donation_Status__c = 'Cleared',
            Donation_Date__c = System.today(),
            Donation_Datetime__c = System.now(),
            Cleared_Datetime__c = System.now(),
            Full_Name_Entered__c = 'testSetup individual 4',
            Email_Entered__c = 'test4@mail.com',
            ID_Type_Entered__c = 'NRIC',
            Tax_Recipient_ID_No_Entered__c = 'NRIC-testSetup1',
            Tax_Recipient_Full_Name_Entered__c = 'testSetup individual 1',
            Donation_Amount__c = 100,
            Payment_Method__c = 'Credit Card'
        );

        Insert donationToInsert;
    }



    @isTest
    // Scenario : 
    // create a donation with existing Contact
    // and new tax recipient which is different with the donor
    public static void createDonation8(){
        Donations__c donationToInsert = new Donations__c(
            RecordTypeId = Schema.SObjectType.Donations__c.getRecordTypeInfosByName().get('Cash').getRecordTypeId(),
            Donor_Type__c = 'Individual',
            Donation_Status__c = 'Cleared',
            Donation_Date__c = System.today(),
            Donation_Datetime__c = System.now(),
            Cleared_Datetime__c = System.now(),
            Full_Name_Entered__c = 'testSetup individual 1',
            Email_Entered__c = 'testSetup1@mail.com',
            ID_Type_Entered__c = 'NRIC',
            Tax_Recipient_ID_No_Entered__c = 'NRIC-testSetup5',
            Tax_Recipient_Full_Name_Entered__c = 'testSetup individual 5',
            Donation_Amount__c = 100,
            Payment_Method__c = 'Credit Card'
        );

        Insert donationToInsert;
    }


    @isTest
    // Scenario : 
    // create a donation with existing Contact with blank tax recipient
    // and new tax recipient with same full name with the donor
    public static void createDonation9a(){
        Donations__c donationToInsert = new Donations__c(
            RecordTypeId = Schema.SObjectType.Donations__c.getRecordTypeInfosByName().get('Cash').getRecordTypeId(),
            Donor_Type__c = 'Individual',
            Donation_Status__c = 'Cleared',
            Donation_Date__c = System.today(),
            Donation_Datetime__c = System.now(),
            Cleared_Datetime__c = System.now(),
            Full_Name_Entered__c = 'testSetup individual 3',
            Email_Entered__c = 'testSetup3@mail.com',
            ID_Type_Entered__c = 'NRIC',
            Tax_Recipient_ID_No_Entered__c = 'NRIC-testSetup3',
            Tax_Recipient_Full_Name_Entered__c = 'testSetup individual 3',
            Donation_Amount__c = 100,
            Payment_Method__c = 'Credit Card'
        );

        Insert donationToInsert;
    }



    @isTest
    // Scenario : 
    // create a donation with existing Contact with blank tax recipient
    // and new tax recipient with different full name with the donor
    public static void createDonation9b(){
        Donations__c donationToInsert = new Donations__c(
            RecordTypeId = Schema.SObjectType.Donations__c.getRecordTypeInfosByName().get('Cash').getRecordTypeId(),
            Donor_Type__c = 'Individual',
            Donation_Status__c = 'Cleared',
            Donation_Date__c = System.today(),
            Donation_Datetime__c = System.now(),
            Cleared_Datetime__c = System.now(),
            Full_Name_Entered__c = 'testSetup individual 3',
            Email_Entered__c = 'testSetup3@mail.com',
            ID_Type_Entered__c = 'NRIC',
            Tax_Recipient_ID_No_Entered__c = 'NRIC-testSetup6',
            Tax_Recipient_Full_Name_Entered__c = 'test individual 6',
            Donation_Amount__c = 100,
            Payment_Method__c = 'Credit Card'
        );

        Insert donationToInsert;
    }


    @isTest
    // Scenario : 
    // create a donation with existing contact by fill in donor_name__c directly
    public static void createDonation10(){
        try {
            Contact existContact = [
                SELECT Id
                FROM Contact
                WHERE Email = 'testSetup1@mail.com'
            ];


            Donations__c donationToInsert = new Donations__c(
                RecordTypeId = Schema.SObjectType.Donations__c.getRecordTypeInfosByName().get('Cash').getRecordTypeId(),
                Donor_Type__c = 'Individual',
                Donation_Status__c = 'Cleared',
                Donation_Date__c = System.today(),
                Donation_Datetime__c = System.now(),
                Cleared_Datetime__c = System.now(),
                Donation_Amount__c = 100,
                Payment_Method__c = 'Credit Card'
            );

            Insert donationToInsert;
            
        } catch (Exception e) {
            
        }
        
    }


    @isTest
    // Scenario : 
    // create a donation with anonymous
    public static void createDonation11(){

        Donations__c donationToInsert = new Donations__c(
            RecordTypeId = Schema.SObjectType.Donations__c.getRecordTypeInfosByName().get('Cash').getRecordTypeId(),
            Donor_Type__c = 'Anonymous',
            Donation_Status__c = 'Cleared',
            Donation_Date__c = System.today(),
            Donation_Datetime__c = System.now(),
            Cleared_Datetime__c = System.now(),
            Email_Entered__c = 'anon@mail.com',
            Donation_Amount__c = 100,
            Payment_Method__c = 'Credit Card'
        );

        Insert donationToInsert;
    }


    @isTest
    // Scenario : 
    // create a donation with new Contact Info
    // and new tax recipient with different last name
    public static void createDonation12(){
        Donations__c donationToInsert = new Donations__c(
            RecordTypeId = Schema.SObjectType.Donations__c.getRecordTypeInfosByName().get('Cash').getRecordTypeId(),
            Donor_Type__c = 'Individual',
            Donation_Status__c = 'Cleared',
            Donation_Date__c = System.today(),
            Donation_Datetime__c = System.now(),
            Cleared_Datetime__c = System.now(),
            Full_Name_Entered__c = 'test individual 7',
            Email_Entered__c = 'test7@mail.com',
            ID_Type_Entered__c = 'NRIC',
            Tax_Recipient_ID_No_Entered__c = 'NRIC-test8',
            Tax_Recipient_Full_Name_Entered__c = 'test individual 8',
            Donation_Amount__c = 100,
            Payment_Method__c = 'Credit Card'
        );

        Insert donationToInsert;
    }


    @isTest
    // Scenario : 
    // create bulk donation with only donor_name__c filled
    // combined testing with programme/event
    public static void createDonation13(){
        List<String> emailToRetrieveList = new List<String>{
            'testSetup1@mail.com',
            'testSetup3@mail.com',
            'testSetupOrganisation1@mail.com'
        };

        List<Contact> existContact = new List<Contact>([
            SELECT ID
            FROM Contact
            WHERE Email in :emailToRetrieveList
        ]);

        Programme_Events__c programmeTest = [
            SELECT ID
            FROM Programme_Events__c
            WHERE Name = 'Test Programme'
        ];


        List<Donations__c> donationsToInsertList = new List<Donations__c>();
        
        for(Contact cItem : existContact){
            donationsToInsertList.add(new Donations__c(
                RecordTypeId = Schema.SObjectType.Donations__c.getRecordTypeInfosByName().get('Cash').getRecordTypeId(),
                Donor_Type__c = 'Individual',
                Donation_Status__c = 'Cleared',
                Donation_Date__c = System.today(),
                Donation_Datetime__c = System.now(),
                Cleared_Datetime__c = System.now(),
                Donor_Name__c = cItem.id,
                Programme_Event__c = programmeTest.id,
                Donation_Amount__c = 100,
                Payment_Method__c = 'Credit Card'
            ));
        }

        Insert donationsToInsertList;
        
    }


    
}