force-app/main/default/objects/Account/fields/ID_No__c.field-meta.xml
<CustomField>
    <fullName>ID_No__c</fullName>
    <externalId>true</externalId>
    <label>ID No.</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Organisation.recordType-meta.xml
<RecordType>
    <fullName>Organisation</fullName>
    <active>true</active>
    <label>Organisation</label>
</RecordType>

force-app/main/default/objects/Attendance__c/Attendance__c.object-meta.xml
<CustomObject>
    <label>Attendance</label>
    <nameField>
        <displayFormat>AT No.-{ddmmyy}-{00000}</displayFormat>
        <label>Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendance__c/fields/Checked_In__c.field-meta.xml
<CustomField>
    <fullName>Checked_In__c</fullName>
    <label>Checked In</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Checked_Out__c.field-meta.xml
<CustomField>
    <fullName>Checked_Out__c</fullName>
    <label>Checked Out</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Volunteer Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Attendances</relationshipLabel>
    <relationshipName>Attendances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Validated__c.field-meta.xml
<CustomField>
    <fullName>Validated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Validated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Donor_Type__c.field-meta.xml
<CustomField>
    <fullName>Donor_Type__c</fullName>
    <defaultValue>if( $RecordType.DeveloperName = &apos;Contact&apos;, &apos;Organisation&apos;, null)</defaultValue>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Organisation</fullName>
            </value>
            <value>
                <fullName>Anonymous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ID_No__c.field-meta.xml
<CustomField>
    <fullName>ID_No__c</fullName>
    <externalId>true</externalId>
    <label>Tax Recipient ID No</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Organisation_Name__c.field-meta.xml
<CustomField>
    <fullName>Organisation_Name__c</fullName>
    <label>Organisation Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Individual.recordType-meta.xml
<RecordType>
    <fullName>Individual</fullName>
    <active>true</active>
    <label>Individual</label>
</RecordType>

force-app/main/default/classes/TestAttendance.cls
@isTest
public class TestAttendance {
	@isTest
    public static void testcalculatevolunteerhours(){
        Account org = new Account(
        		Name = 'Organisation',
        		RecordTypeId = Utils.GetRecordTypeId('Account', 'Organisation'));
        insert org;
		Contact con = new Contact (
            	AccountId = org.Id,
                LastName = 'AccountTest',
                Email = 'test@test.test',
                HomePhone = '90077765',
            	Organisation_Name__c = 'Interaktiv',
                //ID_No__c = 'dystem',
            	RecordTypeId = Utils.GetRecordTypeId('Contact', 'Contact')
                );
        Contact con1 = new Contact (
                LastName = 'Testing',
                RecordTypeId = Utils.GetRecordTypeId('Contact', 'Individual'),
                //c.Email_Personal__c = 'testing@interaktiv.sg';
                Email = 'testingers@interaktiv.sg',
                Donor_Type__c = 'Individual'
                );
        Contact con3 = new Contact (
            	AccountId = org.Id,
                LastName = 'AccountTest',
                Email = 'test2@test.test',
                HomePhone = '90074765',
            	Organisation_Name__c = 'Hostel',
                //ID_No__c = 'dystem',
            	RecordTypeId = Utils.GetRecordTypeId('Contact', 'Contact')
                );
        test.startTest();
        insert con;
        insert con1;
        insert con3;
        
		Attendance__c att = new Attendance__c();
		att.Contact__c = con.id;
		att.Checked_In__c = Datetime.now();
		att.Checked_Out__c = Datetime.now().addHours(5);
        att.Validated__c = true;
        insert(att);
        
        att.Checked_Out__c = Datetime.now().addHours(8);
        update(att);
        
        att.Contact__c = con1.Id;
        update(att);
        
        delete(att);
        
        Attendance__c att1 = new Attendance__c();
		//att1.Organisation_Name__c = org.id;
		att1.Checked_In__c = Datetime.now();
		att1.Checked_Out__c = Datetime.now().addHours(5);
        att1.Validated__c = true;
        insert(att1);
  //      org = [SELECT Id, Volunteering_Mins_No_Name_Volunteer__c FROM Account WHERE id =:org.Id];
  //      system.assertEquals(5*60, org.Volunteering_Mins_No_Name_Volunteer__c);
        
        att1.Checked_Out__c = Datetime.now().addHours(8);
        update(att1);
        
        
        
        delete(att1);
        test.stopTest();
    }
}