force-app/main/default/objects/Assigned_Volunteer__c/Assigned_Volunteer__c.object-meta.xml
<CustomObject>
    <label>Assigned Volunteer</label>
    <nameField>
        <label>Volunteer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assigned Volunteers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Assignee_Status__c.field-meta.xml
<CustomField>
    <fullName>Assignee_Status__c</fullName>
    <label>Assignee Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Selected</fullName>
                <default>true</default>
                <label>Selected</label>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
                <isActive>false</isActive>
                <label>Declined</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Volunteer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assigned Volunteers</relationshipLabel>
    <relationshipName>Assigned_Volunteers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Volunteer_Request__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Request__c</fullName>
    <label>Activity/Event</label>
    <referenceTo>Volunteer_Request__c</referenceTo>
    <relationshipLabel>Assigned Volunteers</relationshipLabel>
    <relationshipName>Assigned_Volunteers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Donor_Type__c.field-meta.xml
<CustomField>
    <fullName>Donor_Type__c</fullName>
    <defaultValue>if( $RecordType.DeveloperName = &apos;Contact&apos;, &apos;Organisation&apos;, null)</defaultValue>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Organisation</fullName>
            </value>
            <value>
                <fullName>Anonymous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Individual.recordType-meta.xml
<RecordType>
    <fullName>Individual</fullName>
    <active>true</active>
    <label>Individual</label>
</RecordType>

force-app/main/default/objects/Volunteer_Request__c/Volunteer_Request__c.object-meta.xml
<CustomObject>
    <label>Volunteer Request</label>
    <nameField>
        <label>Activity/Event</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Request__c/fields/Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Number__c</fullName>
    <label>Contact Number VR</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/fields/Important_Information_Patient_Background__c.field-meta.xml
<CustomField>
    <fullName>Important_Information_Patient_Background__c</fullName>
    <label>Important Information/Patient Background</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/fields/Minimum_Volunteer_Required__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Volunteer_Required__c</fullName>
    <label>Minimum Volunteer Required</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/fields/Number_of_Volunteers_Required__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Volunteers_Required__c</fullName>
    <label>Number of Volunteers Required</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/fields/Recruitment_Deadline__c.field-meta.xml
<CustomField>
    <fullName>Recruitment_Deadline__c</fullName>
    <label>Recruitment Deadline</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/fields/Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Request_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Request Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/fields/Volunteer_Request_No__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Request_No__c</fullName>
    <displayFormat>VR-{yy}{mm}{dd}-{00}</displayFormat>
    <label>VR No.</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/recordTypes/Direct.recordType-meta.xml
<RecordType>
    <fullName>Direct</fullName>
    <active>true</active>
    <label>Direct</label>
</RecordType>

force-app/main/default/objects/Volunteer_Request__c/recordTypes/Indirect.recordType-meta.xml
<RecordType>
    <fullName>Indirect</fullName>
    <active>true</active>
    <label>Indirect</label>
</RecordType>

force-app/main/default/classes/AttendanceTest.cls
@isTest public class AttendanceTest {
	@isTest static void TestAttendanceUpload(){
    	Contact c1 = new Contact();
        c1.LastName = 'Test 123';
        c1.Email = 'abc123@testclass.com';
        c1.Donor_Type__c = 'Individual';
        c1.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        insert(c1);
        
        Volunteer_Request__c v1 = new Volunteer_Request__c();
        v1.RecordTypeId = Schema.SObjectType.Volunteer_Request__c.getRecordTypeInfosByName().get('Indirect').getRecordTypeId();
        v1.Name = 'Test VR';
        v1.Start_Date__c = Date.today().addDays(3);
        v1.End_Date__c = Date.today().addDays(9);
        v1.Start_Time__c = Time.newInstance(5, 0, 0, 0);
        v1.End_Time__c = Time.newInstance(11, 0, 0, 0);
        v1.Recruitment_Deadline__c = Date.today().addDays(2);
        v1.Request_Date__c = Date.today();
        v1.Email__c = 'abc@test.com';
        v1.Number_of_Volunteers_Required__c = 10;
        v1.Minimum_Volunteer_Required__c = 10;
        v1.Contact_Number__c = '08689';
        v1.Important_Information_Patient_Background__c = 'Test';
        insert(v1);
        v1 = [SELECT Id, Name, Volunteer_Request_No__c FROM Volunteer_Request__c WHERE Id = :v1.Id];
        
        Assigned_Volunteer__c a1 = new Assigned_Volunteer__c();
        a1.Volunteer_Request__c = v1.Id;
        a1.Contact__c = c1.Id;
        a1.Assignee_Status__c = 'Contacted';
        insert(a1);
        
        String strData = 'Record Type,Programme/Event,Volunteer Request No.,Account,Name,Email,Mobile,Date In,Time In,Date Out,Time Out,Hours,Remarks \n'+
'Indirect,,,Company A,Testing A1,abc123@testclass.com,,06/08/2021,10:20:00 AM,06/08/2021,04:00:00 PM,5,Testing only \n'+
'Indirect,,,,Testing A2,abctest2@company-a.com,,06/08/2021,10:20:00 AM,06/08/2021,04:00:00 PM,5, \n'+
'Direct,,' + v1.Volunteer_Request_No__c + ',Company ABC,Testing A3,abctest3@company-a.com,,06/08/2021,12:00:00 PM,07/08/2021,12:00:00 AM,5,normal test \n'+
'Direct,,' + v1.Volunteer_Request_No__c + ',,Testing A4,abctest4@company-a.com,,06/08/2021,10:20 AM,07/08/2021,12:10 PM,5,without second \n'+
'Direct,,' + v1.Volunteer_Request_No__c + ',,Testing X5,abctest5@company-a.com,,06/08/2021,10:20 AM,07/08/2021,12:10 PM,5,without second 2 \n'+
'Indirect,,,Company A,Testing A2,abctest2@company-a.com,,06/08/2021,10:20:00 AM,06/08/2021,04:00:00 PM \n'+
'Indirect,,,Company A,Testing A2,abctest2@company-a.com,,,10:20:00 AM,06/08/2021,04:00:00 PM,5, \n'+
'Indirect,,ABC,Company A,Testing A2,abctest2@company-a.com,,06/08/2021,10:20:00 AM,06/08/2021,04:00:00 PM,5, \n'+
'Direct,,' + v1.Volunteer_Request_No__c + ',,Testing A5,abc123@testclass.com,,06/08/2021,12:30:15 AM,07/08/2021,12:45:44 AM,5,with second';
        
        // testing controller
        AttendanceController aCtl = new AttendanceController();
        aCtl.fileCsv = Blob.valueOf(strData);
        aCtl.back();
        aCtl.upload();
        
        // check maperror
        for(Integer i: aCtl.mapErrors.keyset()) {
            system.debug('DEBUG err ' + i + ' = ' + aCtl.mapErrors.get(i));
        }
        
        // Testing SSSCsvReader
        strData = strData.replace('Testing A2', '"Testing A2"');
        SSSCsvReader csvTest = new SSSCsvReader(strData, ',');
        
        List<String> dLine = new List<String>();
        while (dLine != null)
        {
            dLine = csvTest.readLine();
        }
        
    }
    
    @isTest static void isValidNumber(){
        AttendanceController aCtl = new AttendanceController();
        
        aCtl.isValidNumber('10', true);
        aCtl.isValidNumber('10', false);
        aCtl.isValidNumber('hehe', false);
    }
    
    @isTest static void isValidDate(){
        AttendanceController aCtl = new AttendanceController();
        
        aCtl.isValidDate('2012-11-10');
        aCtl.isValidDate('anjay');
    }
    
    @isTest static void convertDate(){
        AttendanceController aCtl = new AttendanceController();
        
        aCtl.convertDate('12-05-2003');
    }
    
    @isTest static void strToTime(){
        AttendanceController aCtl = new AttendanceController();
        
        aCtl.strToTime('10:00:00');
        aCtl.strToTime('12:00');
        aCtl.strToTime('11:00:50');
    }
}