force-app/main/default/objects/Assigned_Volunteer__c/Assigned_Volunteer__c.object-meta.xml
<CustomObject>
    <label>Assigned Volunteer</label>
    <nameField>
        <label>Volunteer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assigned Volunteers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Accepted_Date__c.field-meta.xml
<CustomField>
    <fullName>Accepted_Date__c</fullName>
    <label>Accepted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Assignee_Status__c.field-meta.xml
<CustomField>
    <fullName>Assignee_Status__c</fullName>
    <label>Assignee Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Selected</fullName>
                <default>true</default>
                <label>Selected</label>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
                <isActive>false</isActive>
                <label>Declined</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Assignment_Status__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Status__c</fullName>
    <formula>TEXT(Volunteer_Request__r.Assignment_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assignment Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Cancelled_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancelled_Date__c</fullName>
    <label>Cancelled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Volunteer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assigned Volunteers</relationshipLabel>
    <relationshipName>Assigned_Volunteers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Description_of_Task__c.field-meta.xml
<CustomField>
    <fullName>Description_of_Task__c</fullName>
    <label>Description of Task</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Email_Sent__c</fullName>
    <label>Email Sent</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>End Date_Old</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Frequency_Type__c.field-meta.xml
<CustomField>
    <fullName>Frequency_Type__c</fullName>
    <formula>TEXT(Volunteer_Request__r.Frequency_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Frequency Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Key_Objective__c.field-meta.xml
<CustomField>
    <fullName>Key_Objective__c</fullName>
    <formula>Volunteer_Request__r.Key_Objective__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Key Objective</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Participant_s_Role__c.field-meta.xml
<CustomField>
    <fullName>Participant_s_Role__c</fullName>
    <label>Participant&apos;s Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Volunteer</fullName>
                <default>true</default>
                <label>Volunteer</label>
            </value>
            <value>
                <fullName>Caterer</fullName>
            </value>
            <value>
                <fullName>Counselor</fullName>
            </value>
            <value>
                <fullName>Instructor</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Facilitator</fullName>
            </value>
            <value>
                <fullName>Leader</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Programme_Event_Status__c.field-meta.xml
<CustomField>
    <fullName>Programme_Event_Status__c</fullName>
    <formula>TEXT(Volunteer_Request__r.Programme_Event__r.Programme_Stage__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Programme/Event Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Programme_Name__c.field-meta.xml
<CustomField>
    <fullName>Programme_Name__c</fullName>
    <formula>Volunteer_Request__r.Programme_Event__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Programme Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Rejected_Date__c.field-meta.xml
<CustomField>
    <fullName>Rejected_Date__c</fullName>
    <label>Rejected Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Sent_Notification__c.field-meta.xml
<CustomField>
    <fullName>Sent_Notification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sent Notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Survey_Sent__c.field-meta.xml
<CustomField>
    <fullName>Survey_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Survey Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Volunteer_Hours__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Hours__c</fullName>
    <label>Volunteer Hours</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Volunteer_Manager__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Manager__c</fullName>
    <formula>Volunteer_Request__r.Owner:User.FirstName &amp; &quot; &quot; &amp; Volunteer_Request__r.Owner:User.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Volunteer Manager</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Volunteer_Request__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Request__c</fullName>
    <label>Activity/Event</label>
    <referenceTo>Volunteer_Request__c</referenceTo>
    <relationshipLabel>Assigned Volunteers</relationshipLabel>
    <relationshipName>Assigned_Volunteers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Withdrawn_Date__c.field-meta.xml
<CustomField>
    <fullName>Withdrawn_Date__c</fullName>
    <label>Withdrawn Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Assignment_Status__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Status__c</fullName>
    <label>Assignment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Unavailable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/Volunteer_Request__c.object-meta.xml
<CustomObject>
    <label>Volunteer Request</label>
    <nameField>
        <label>Activity/Event</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Request__c/fields/Assignment_Status__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Status__c</fullName>
    <label>Assignment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fully Assigned</fullName>
            </value>
            <value>
                <fullName>Minimum Assigned</fullName>
            </value>
            <value>
                <fullName>Not assigned</fullName>
                <default>true</default>
                <label>Not assigned</label>
            </value>
            <value>
                <fullName>Partially Assigned</fullName>
            </value>
            <value>
                <fullName>Register</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/fields/Frequency_Type__c.field-meta.xml
<CustomField>
    <fullName>Frequency_Type__c</fullName>
    <label>Frequency Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ad hoc</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Fortnightly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/fields/Key_Objective__c.field-meta.xml
<CustomField>
    <fullName>Key_Objective__c</fullName>
    <label>Key Objective</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/fields/Outcome_Remarks__c.field-meta.xml
<CustomField>
    <fullName>Outcome_Remarks__c</fullName>
    <label>Outcome Remarks</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/fields/Participant_s_Role__c.field-meta.xml
<CustomField>
    <fullName>Participant_s_Role__c</fullName>
    <label>Participant&apos;s Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Case Worker</fullName>
            </value>
            <value>
                <fullName>Caterer</fullName>
            </value>
            <value>
                <fullName>Counselor</fullName>
            </value>
            <value>
                <fullName>Facilitator</fullName>
            </value>
            <value>
                <fullName>Instructor</fullName>
            </value>
            <value>
                <fullName>Leader</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/fields/Programme_Event__c.field-meta.xml
<CustomField>
    <fullName>Programme_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programme/ Event</label>
    <referenceTo>Programme_Events__c</referenceTo>
    <relationshipLabel>Volunteer Requests</relationshipLabel>
    <relationshipName>Volunteer_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/fields/Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Request_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Request Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/fields/Request_status__c.field-meta.xml
<CustomField>
    <fullName>Request_status__c</fullName>
    <label>Request status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/fields/Request_Title__c.field-meta.xml
<CustomField>
    <fullName>Request_Title__c</fullName>
    <label>Request Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/fields/Type_of_Request__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Request__c</fullName>
    <label>Type of Request</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ad Hoc</fullName>
            </value>
            <value>
                <fullName>Recurring</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VRSendInvitationEmailController.cls
public class VRSendInvitationEmailController {
	public Id Id{get;set;}
    public String Email{get;set;}
    public List<Volunteer_Request__c> L {get;set;}
    public List<Assigned_Volunteer__c> P {get;set;}
    public List<ObjTable> ObjtblList {get;set;}
    public List<Assigned_Volunteer__c> Acc {get;set;}
    public String emsg{get;set;}
    public String esub{get;set;}
    Volunteer_Request__c objL;
    public Volunteer_Request__c Invo {get;set;}
    public String strSelected  {get;set;}
    public String strTemplate  {get;set;}
    public String FoldId{get;set;}
    public List<SelectOption> options {get;set;}
    public List<EmailTemplate> orderItemList {get; set;}
    public List<EmailObject> EmailObjectList {get; set;}
    public Assigned_Volunteer__c dParam {get; set;}
    public boolean pageRender {get; set;}
    public Decimal noVol {get; set;}
    
    public VRSendInvitationEmailController (ApexPages.StandardController controller) {
        Id = ApexPages.CurrentPage().getParameters().get('id');   
        Email = ApexPages.CurrentPage().getParameters().get('Email');   
        System.debug('DEBUG das Id = ' + Id );  
        strTemplate = '';
        noVol = 0;
        dParam = new Assigned_Volunteer__c();
        dParam.Assignee_Status__c = 'Selected';
        //ObjtblList = new List<ObjTable>();
        if (Id == null )
        {
          ApexPages.Message myMsg = new ApexPages.Message(ApexPages.severity.ERROR, Label.VRSendEmailError1);
          ApexPages.addMessage(myMsg);
        } 
        
        try{
            Invo = [SELECT Id,name
                    ,Assignment_Status__c
                    ,End_Date__c 
                    ,Frequency_Type__c
                    ,Key_Objective__c
                    ,Outcome_remarks__c
                    ,Programme_Event__c
                    ,Request_Date__c
                    ,Request_status__c
                    ,Request_Title__c
                    ,Start_Date__c
                    ,Type_of_Request__c
                    ,Programme_Event__r.Name
                    FROM Volunteer_Request__c WHERE Id = :Id AND Request_status__c NOT IN ('Cancelled','Terminated')];
            pageRender = true;
            refreshAll();
            refreshAssignedVolunteer();

        }catch(Exception e){
            pageRender = false;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING, Label.VRSendEmailError2 + e.getMessage()));
        }
    }
    class EmailObject{
        public integer num {get; set;}
        public String name {get; set;}
        public String templatetype {get; set;}
        public integer noofsent {get; set;}
        public EmailTemplate guest {get; set;} 
    }   
    public void refreshAll(){    
        //Organization org = [select id,IsSandbox from Organization];           
        //if(org.IsSandbox == true){FoldId = '00l2v000003wCKv';}else{FoldId = '00l2v000003wCKv';}
        FoldId = 'Volunteer Request';
        strSelected = '';
        options = new List<SelectOption>();
        options.add(new SelectOption('','-Please Select-'));
        EmailObjectList = new List<EmailObject>();
        integer i = 1;
        
        orderItemList = [SELECT Id, Name,TemplateType, Folder.name FROM EmailTemplate WHERE Folder.name =:FoldId order by TemplateType,Name];
        for(EmailTemplate obj : orderItemList ){
            options.add(new SelectOption(obj.Id,obj.Name));
            EmailObject gObj = new EmailObject();
            gObj.num = i;
            gObj.guest = obj;
            gObj.Name = obj.name;
            gObj.templatetype = obj.TemplateType;           
            EmailObjectList.add(gObj);
            i++;
        }
    }   
    public PageReference PreviewEmail(){
        if(strSelected <> '-Please Select-' && strSelected <> null)
        {
            System.debug('DEBUG das strSelected = ' + strSelected );  
            LoadDatasendMassEmail();
        }
        else{
            System.debug('DEBUG das strSelected = ' + strSelected ); 
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,Label.VRSendEmailError3));
        }
        return null;   
    }
    public PageReference LoadDatasendMassEmail(){
        L = [ SELECT Id,name
                ,Assignment_Status__c
                ,End_Date__c
                ,Frequency_Type__c
                ,Outcome_remarks__c
                ,Programme_Event__c
                ,Request_Date__c
                ,Request_status__c
                ,Request_Title__c
                ,Start_Date__c
                ,Type_of_Request__c
             ,Key_Objective__c
             ,Programme_Event__r.Name
             ,Start_Time__c
             ,End_Time__c
             ,Owner.Name
                FROM Volunteer_Request__c WHERE Id = :Id
            ];
            
        Decimal a;
        System.debug('DEBUG das L = ' + L ); 
        
        for(Volunteer_Request__c tempL : L){
                a = 1;
        }  
        if(a == 1){            
            EmailTemplate emsgsub;
            if(!Test.isRunningTest()){
                emsgsub =[SELECT subject,Body,DeveloperName,Id,HTMLValue  FROM EmailTemplate where id=:strSelected LIMIT 1];
            }else{
                emsgsub =[SELECT subject,Body,DeveloperName,Id,HTMLValue  FROM EmailTemplate  LIMIT 1];
            }
            System.debug('DEBUG das emsgsub.Subject = ' + emsgsub.Subject ); 
            System.debug('DEBUG das emsgsub.Body = ' + emsgsub.Body ); 
            Datetime startDatetime = DateTime.newInstance(L[0].Start_Date__c.year(),L[0].Start_Date__c.month(),L[0].Start_Date__c.day(), L[0].Start_Time__c.hour(), L[0].Start_Time__c.minute(), L[0].Start_Time__c.second());
            Datetime endDatetime;
            if(L[0].End_Date__c != null){
                endDatetime = DateTime.newInstance(L[0].End_Date__c.year(),L[0].End_Date__c.month(),L[0].End_Date__c.day(), L[0].End_Time__c.hour(), L[0].End_Time__c.minute(), L[0].End_Time__c.second());
            }
            if(emsgsub.Subject != null){
                esub = emsgsub.Subject;
                esub = (L[0].name <> null) ? esub.replace('{!Volunteer_Request__c.Name}', L[0].name) : esub.replace('{!Volunteer_Request__c.Name}', '');
                esub = (L[0].Start_Date__c <> null) ? esub.replace('{!Assigned_Volunteer__c.Start_Date__c}', startDatetime.format('dd-MMM-yyyy')) : esub.replace('{!Assigned_Volunteer__c.Start_Date__c}', '');
                esub = (L[0].Start_Time__c <> null) ? esub.replace('{!Assigned_Volunteer__c.Start_Time__c}', startDatetime.format('hh:mm a')) : esub.replace('{!Assigned_Volunteer__c.Start_Time__c}', '');
            } else {
                esub = '';
            }
            
            //if(emsgsub.Body != null){
                //emsg = emsgsub.Body.replace('\n','<br>') ;
            //} else{
                if(!Test.isRunningTest()){emsg = emsgsub.HtmlValue;}
                else{emsg = emsgsub.Body;}
            //}
            emsg = (L[0].Programme_Event__c <> null) ? emsg.replace('{!Assigned_Volunteer__c.Programme_Name__c}', L[0].Programme_Event__r.Name) : emsg.replace('{!Assigned_Volunteer__c.Programme_Name__c}', '');
            emsg = (L[0].Name <> null) ? emsg.replace('{!Assigned_Volunteer__c.Volunteer_Request__c}', L[0].Name) : emsg.replace('{!Assigned_Volunteer__c.Volunteer_Request__c}', '');
            emsg = (L[0].Start_Date__c <> null) ? emsg.replace('{!Assigned_Volunteer__c.Start_Date__c}', startDatetime.format('dd-MMM-yyyy')) : emsg.replace('{!Assigned_Volunteer__c.Start_Date__c}', '');
            emsg = (L[0].End_Date__c <> null) ? emsg.replace('{!Assigned_Volunteer__c.End_Date__c}', enddatetime.format('dd-MMM-yyyy')) : emsg.replace('{!Assigned_Volunteer__c.End_Date__c}', '');
            emsg = (L[0].Start_Time__c <> null) ? emsg.replace('{!Assigned_Volunteer__c.Start_Time__c}', string.valueof(startDatetime.format('hh:mm a'))) : emsg.replace('{!Assigned_Volunteer__c.Start_Time__c}', '');
            emsg = (L[0].End_Time__c <> null) ? emsg.replace('{!Assigned_Volunteer__c.End_Time__c}', string.valueof(endDatetime.format('hh:mm a'))) : emsg.replace('{!Assigned_Volunteer__c.End_Time__c}', '');
            emsg = (L[0].Key_Objective__c <> null) ? emsg.replace('{!Assigned_Volunteer__c.Key_Objective__c}', L[0].Key_Objective__c) : emsg.replace('{!Assigned_Volunteer__c.Key_Objective__c}', '');
            emsg = (L[0].Request_Title__c <> null) ? emsg.replace('{!Volunteer_Request__c.Request_Title__c}', L[0].Request_Title__c) : emsg.replace('{!Volunteer_Request__c.Request_Title__c}', '');
            emsg = (L[0].Owner.Name <> null) ? emsg.replace('{!Assigned_Volunteer__c.Volunteer_Manager__c}', L[0].Owner.Name) : emsg.replace('{!Assigned_Volunteer__c.Volunteer_Manager__c}', '');
            
            //DateTime.newInstance(L[0].Start_Date__c.year(),L[0].Start_Date__c.month(),L[0].Start_Date__c.day()).format('dd-mmm-yyyy');
            //DateTime.newInstance(L[0].End_Date__c.year(),L[0].End_Date__c.month(),L[0].End_Date__c.day()).format('dd-mmm-yyyy');
            return null;
        }else{
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING, Label.VRSendEmailError5));
            return null;
        }
        
    }
    public void refreshAssignedVolunteer(){
        ObjtblList = new List<ObjTable>();
        P = [   SELECT Id,name
                ,Contact__r.firstname
                ,Contact__r.lastname
                ,Contact__r.Email
                ,Contact__r.Phone
                ,Contact__r.MobilePhone
                ,Accepted_Date__c
                ,Assignee_Status__c
                ,Cancelled_Date__c
                ,Contact__c
                ,CreatedById
                ,Description_of_Task__c
                ,Email_Sent__c
                ,Survey_Sent__c
                ,End_Date__c
                ,EndDate__c
                ,LastModifiedById
                ,Participant_s_Role__c
                ,Programme_Event_Status__c
                ,Rejected_Date__c
                ,Sent_Notification__c
                ,Start_Date__c
                ,Volunteer_Request__c
                ,Volunteer_Request__r.name
                ,Volunteer_Hours__c
                ,Withdrawn_Date__c
                ,Key_Objective__c
                ,Programme_Name__c
                ,Invitation_URL__c
                ,Volunteer_Manager__c
                ,Start_Time__c
             	,Assignment_Status__c 
                ,End_Time__c
                FROM Assigned_Volunteer__c WHERE Volunteer_Request__c = :Id  AND Assignee_Status__c =:dParam.Assignee_Status__c AND Contact__r.Email <> NULL//AND Email_sent__c = null
            ]; 
            for(Assigned_Volunteer__c v : P){
                ObjTable obj = new ObjTable();
                //obj.selected = false;
                obj.rowObj = v;
                ObjtblList.add(obj);
            }
        
    }
    
    
    public PageReference sendEmailInBatch(){ 
        integer iselect = 0;
        for(ObjTable obj: ObjtblList ){
            if(obj.selected == true){
                iselect++;
            }
        }
        if(strSelected == null){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING, Label.VRSendEmailError6));
        }
        else if(iselect == 0){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING, 'Please select at least one Email to send.'));
        }else{
            String vIds = '(';
            for(ObjTable obj : ObjtblList ){
                if(obj.selected == true){
                    vIds += '\''+obj.rowObj.Id+'\',';
                }
            }
            vIds = vIds.removeEnd(',');
            vIds += ')';
            SendEmailInBatch batchEmail = new SendEmailInBatch(vIds, strSelected, id);
            Database.executeBatch(batchEmail, 10);
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM, 'Emails sent.')); 
            refreshAssignedVolunteer();
        }
        return null;
    }
    public PageReference Accepted(){   
        integer z = 0;
        Acc = [ Select Id, Assignee_Status__c,Contact__r.email from Assigned_Volunteer__c WHERE Contact__r.email = :Email];
        for(Assigned_Volunteer__c I : Acc){
                z = 1;
                I.Assignee_Status__c = 'Accepted';
                I.Accepted_Date__c = date.today();
        }
        if(z == 1)
        {
            Update(Acc);
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO, Label.VRSendEmailError4));
        }     
        return null;  
    }
    
    public PageReference selectAll(){
        for(ObjTable obj : ObjtblList ){
            obj.selected = true;
        }
        return null;
    } 
    public PageReference unselectAll(){
        for(ObjTable obj : ObjtblList ){
            obj.selected = false;
        }
        return null;
    }
    
    public PageReference back(){
        pageReference pg = new pageReference('/'+Id);
        pg.setRedirect(true);
        return pg;
    }
    
    public class ObjTable{
        public boolean selected {get; set;}
        public Assigned_Volunteer__c rowObj {get; set;}
    }
}