force-app/main/default/objects/Assigned_Volunteer__c/Assigned_Volunteer__c.object-meta.xml
<CustomObject>
    <label>Assigned Volunteer</label>
    <nameField>
        <label>Volunteer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assigned Volunteers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Accepted_Date__c.field-meta.xml
<CustomField>
    <fullName>Accepted_Date__c</fullName>
    <label>Accepted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Assignee_Status__c.field-meta.xml
<CustomField>
    <fullName>Assignee_Status__c</fullName>
    <label>Assignee Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Selected</fullName>
                <default>true</default>
                <label>Selected</label>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
                <isActive>false</isActive>
                <label>Declined</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Assignment_Status__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Status__c</fullName>
    <formula>TEXT(Volunteer_Request__r.Assignment_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assignment Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Cancelled_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancelled_Date__c</fullName>
    <label>Cancelled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Volunteer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assigned Volunteers</relationshipLabel>
    <relationshipName>Assigned_Volunteers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Description_of_Task__c.field-meta.xml
<CustomField>
    <fullName>Description_of_Task__c</fullName>
    <label>Description of Task</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Email_Sent__c</fullName>
    <label>Email Sent</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>End Date_Old</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Frequency_Type__c.field-meta.xml
<CustomField>
    <fullName>Frequency_Type__c</fullName>
    <formula>TEXT(Volunteer_Request__r.Frequency_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Frequency Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Invitation_URL__c.field-meta.xml
<CustomField>
    <fullName>Invitation_URL__c</fullName>
    <formula>$Label.Landing_URL +&quot;volunteer-request?id=&quot;+ Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invitation URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Key_Objective__c.field-meta.xml
<CustomField>
    <fullName>Key_Objective__c</fullName>
    <formula>Volunteer_Request__r.Key_Objective__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Key Objective</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Participant_s_Role__c.field-meta.xml
<CustomField>
    <fullName>Participant_s_Role__c</fullName>
    <label>Participant&apos;s Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Volunteer</fullName>
                <default>true</default>
                <label>Volunteer</label>
            </value>
            <value>
                <fullName>Caterer</fullName>
            </value>
            <value>
                <fullName>Counselor</fullName>
            </value>
            <value>
                <fullName>Instructor</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Facilitator</fullName>
            </value>
            <value>
                <fullName>Leader</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Programme_Event_Status__c.field-meta.xml
<CustomField>
    <fullName>Programme_Event_Status__c</fullName>
    <formula>TEXT(Volunteer_Request__r.Programme_Event__r.Programme_Stage__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Programme/Event Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Programme_Name__c.field-meta.xml
<CustomField>
    <fullName>Programme_Name__c</fullName>
    <formula>Volunteer_Request__r.Programme_Event__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Programme Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Rejected_Date__c.field-meta.xml
<CustomField>
    <fullName>Rejected_Date__c</fullName>
    <label>Rejected Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Sent_Notification__c.field-meta.xml
<CustomField>
    <fullName>Sent_Notification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sent Notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Survey_Sent__c.field-meta.xml
<CustomField>
    <fullName>Survey_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Survey Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Volunteer_Manager__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Manager__c</fullName>
    <formula>Volunteer_Request__r.Owner:User.FirstName &amp; &quot; &quot; &amp; Volunteer_Request__r.Owner:User.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Volunteer Manager</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Volunteer_Request__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Request__c</fullName>
    <label>Activity/Event</label>
    <referenceTo>Volunteer_Request__c</referenceTo>
    <relationshipLabel>Assigned Volunteers</relationshipLabel>
    <relationshipName>Assigned_Volunteers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Withdrawn_Date__c.field-meta.xml
<CustomField>
    <fullName>Withdrawn_Date__c</fullName>
    <label>Withdrawn Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Assignment_Status__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Status__c</fullName>
    <label>Assignment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Unavailable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Volunteer_Request__c/Volunteer_Request__c.object-meta.xml
<CustomObject>
    <label>Volunteer Request</label>
    <nameField>
        <label>Activity/Event</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Request__c/fields/Assignment_Status__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Status__c</fullName>
    <label>Assignment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fully Assigned</fullName>
            </value>
            <value>
                <fullName>Minimum Assigned</fullName>
            </value>
            <value>
                <fullName>Not assigned</fullName>
                <default>true</default>
                <label>Not assigned</label>
            </value>
            <value>
                <fullName>Partially Assigned</fullName>
            </value>
            <value>
                <fullName>Register</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/fields/Frequency_Type__c.field-meta.xml
<CustomField>
    <fullName>Frequency_Type__c</fullName>
    <label>Frequency Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ad hoc</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Fortnightly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/fields/Key_Objective__c.field-meta.xml
<CustomField>
    <fullName>Key_Objective__c</fullName>
    <label>Key Objective</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/fields/Outcome_Remarks__c.field-meta.xml
<CustomField>
    <fullName>Outcome_Remarks__c</fullName>
    <label>Outcome Remarks</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/fields/Participant_s_Role__c.field-meta.xml
<CustomField>
    <fullName>Participant_s_Role__c</fullName>
    <label>Participant&apos;s Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Case Worker</fullName>
            </value>
            <value>
                <fullName>Caterer</fullName>
            </value>
            <value>
                <fullName>Counselor</fullName>
            </value>
            <value>
                <fullName>Facilitator</fullName>
            </value>
            <value>
                <fullName>Instructor</fullName>
            </value>
            <value>
                <fullName>Leader</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/fields/Programme_Event__c.field-meta.xml
<CustomField>
    <fullName>Programme_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programme/ Event</label>
    <referenceTo>Programme_Events__c</referenceTo>
    <relationshipLabel>Volunteer Requests</relationshipLabel>
    <relationshipName>Volunteer_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/fields/Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Request_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Request Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/fields/Request_status__c.field-meta.xml
<CustomField>
    <fullName>Request_status__c</fullName>
    <label>Request status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/fields/Request_Title__c.field-meta.xml
<CustomField>
    <fullName>Request_Title__c</fullName>
    <label>Request Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SendEmailInBatch.cls
global class SendEmailInBatch implements Database.Batchable<sObject> {
	global String query;
    global String objName;
    global String errorMsg;
    global String volIds;
    global String templateId;
    global String vrId;
    
    global SendEmailInBatch(String vIds, String tId, String vreqId){
        query = 'SELECT Id,name'+
                ',Contact__r.firstname'+
            	',Contact__r.Name'+
                ',Contact__r.lastname'+
                ',Contact__r.Email'+
                ',Contact__r.Phone'+
                ',Contact__r.MobilePhone'+
                ',Accepted_Date__c'+
            	',Assignee_Status__c'+
                ',Cancelled_Date__c'+
                ',Contact__c'+
                ',CreatedById'+
                ',Description_of_Task__c'+
                ',Email_Sent__c'+
                ',Survey_Sent__c'+
                ',End_Date__c'+
                ',EndDate__c'+
                ',LastModifiedById'+
                ',Participant_s_Role__c'+
                ',Programme_Event_Status__c'+
                ',Rejected_Date__c'+
                ',Sent_Notification__c'+
                ',Start_Date__c'+
                ',Volunteer_Request__c'+
                ',Volunteer_Request__r.name'+
                ',Withdrawn_Date__c'+
                ',Key_Objective__c'+
                ',Programme_Name__c'+
                ',Invitation_URL__c'+
                ',Volunteer_Manager__c'+
                ',Start_Time__c'+
             	',End_Time__c'+
            	',Email__c'+
                ' FROM Assigned_Volunteer__c'+
            	' WHERE Id IN '+vIds;
        volIds = vIds;
        system.debug('=======ericca debug query========'+query);
        templateId = tId; 
        vrId = vreqId;
    }
    
    global Database.QueryLocator start (Database.BatchableContext bc){
        system.debug('=======ericca debug query========'+volIds);
        return Database.getQueryLocator(query);
    }
    
    global void execute (Database.BatchableContext bc, List<SObject> scope){
        System.debug('lstRI before = ' + scope );  
        Set<Id> pIds = new Set<Id>();
        if(scope.size()>0){
            Set<id> contIds = new Set<Id>();
            for(SObject s : scope){
                pIds.add((Id)s.get('Contact__c'));
            }
            EmailTemplate emailTemp =[SELECT subject,Body,DeveloperName,Id,HTMLValue  FROM EmailTemplate where id=:templateId LIMIT 1];
        	List<Volunteer_Request__c> L = [ SELECT Id,name
                                            ,Assignment_Status__c
                                            ,End_Date__c
                                            ,Frequency_Type__c
                                            ,Outcome_remarks__c
                                            ,Programme_Event__c
                                            ,Request_Date__c
                                            ,Request_status__c
                                            ,Request_Title__c
                                            ,Start_Date__c
                                            ,Type_of_Request__c
                                         	,Key_Objective__c
                                         	,Programme_Event__r.Name
                                         	,Start_Time__c
                                         	,End_Time__c
                                         	,Owner.Name
                                            FROM Volunteer_Request__c WHERE Id = :vrId
                                          ];
            //Map<Id, Contact> contactMap = new Map<Id, Contact>([SELECT Id, Name, Email, Phone, MobilePhone, Passcode__c 
            //                                                    FROM Contact WHERE Id IN :pIds]);
            
            for(SObject S : scope){  
                Datetime startDatetime = DateTime.newInstance(L[0].Start_Date__c.year(),L[0].Start_Date__c.month(),L[0].Start_Date__c.day(), L[0].Start_Time__c.hour(), L[0].Start_Time__c.minute(), L[0].Start_Time__c.second());
                Datetime endDatetime;
                if(L[0].End_Date__c != null){
                    endDatetime = DateTime.newInstance(L[0].End_Date__c.year(),L[0].End_Date__c.month(),L[0].End_Date__c.day(), L[0].End_Time__c.hour(), L[0].End_Time__c.minute(), L[0].End_Time__c.second());
                }
                String emsg;
                String esub;
                if(emailTemp.Subject != null){
                    esub = emailTemp.Subject;
                    esub = (L[0].name <> null) ? esub.replace('{!Volunteer_Request__c.Name}', L[0].name) : esub.replace('{!Volunteer_Request__c.Name}', '');
                } else {
                    esub = '';
                }
                
                if(!Test.isRunningTest()){emsg = emailTemp.HtmlValue;}
                else{emsg = emailTemp.Body;}
                
                emsg = (L[0].Programme_Event__c <> null) ? emsg.replace('{!Assigned_Volunteer__c.Programme_Name__c}', L[0].Programme_Event__r.Name) : emsg.replace('{!Assigned_Volunteer__c.Programme_Name__c}', '');
                emsg = (L[0].Name <> null) ? emsg.replace('{!Assigned_Volunteer__c.Volunteer_Request__c}', L[0].Name) : emsg.replace('{!Assigned_Volunteer__c.Volunteer_Request__c}', '');
                emsg = (L[0].Key_Objective__c <> null) ? emsg.replace('{!Assigned_Volunteer__c.Key_Objective__c}', L[0].Key_Objective__c) : emsg.replace('{!Assigned_Volunteer__c.Key_Objective__c}', '');
                emsg = (L[0].Request_Title__c <> null) ? emsg.replace('{!Volunteer_Request__c.Request_Title__c}', L[0].Request_Title__c) : emsg.replace('{!Volunteer_Request__c.Request_Title__c}', '');
                emsg = (L[0].Owner.Name <> null) ? emsg.replace('{!Assigned_Volunteer__c.Volunteer_Manager__c}', L[0].Owner.Name) : emsg.replace('{!Assigned_Volunteer__c.Volunteer_Manager__c}', '');

                String strname = (String)s.get('Name');
                Datetime startdt;
                Datetime enddt;
                
                if(s.get('Start_Date__c') != null && s.get('Start_Time__c') != null){
                    startdt = DateTime.newInstance(((Date)s.get('Start_Date__c')).year(),((Date)s.get('Start_Date__c')).month(),((Date)s.get('Start_Date__c')).day(), ((Time)s.get('Start_Time__c')).hour(), ((Time)s.get('Start_Time__c')).minute(), ((Time)s.get('Start_Time__c')).second());
        			esub = esub.replace('{!Assigned_Volunteer__c.Start_Date__c}', startdt.format('dd-MMM-yyyy'));
                    emsg = emsg.replace('{!Assigned_Volunteer__c.Start_Date__c}', startdt.format('dd-MMM-yyyy'));
                    esub = esub.replace('{!Assigned_Volunteer__c.Start_Time__c}', startdt.format('hh:mm a'));
                    emsg = emsg.replace('{!Assigned_Volunteer__c.Start_Time__c}', startdt.format('hh:mm a'));
                }else{
                    esub = (L[0].Start_Date__c <> null) ? esub.replace('{!Assigned_Volunteer__c.Start_Date__c}', startDatetime.format('dd-MMM-yyyy')) : esub.replace('{!Assigned_Volunteer__c.Start_Date__c}', '');
                	esub = (L[0].Start_Time__c <> null) ? esub.replace('{!Assigned_Volunteer__c.Start_Time__c}', startDatetime.format('hh:mm a')) : esub.replace('{!Assigned_Volunteer__c.Start_Time__c}', '');
                	
                    emsg = (L[0].Start_Date__c <> null) ? emsg.replace('{!Assigned_Volunteer__c.Start_Date__c}', startDatetime.format('dd-MMM-yyyy')) : emsg.replace('{!Assigned_Volunteer__c.Start_Date__c}', '');
                    emsg = (L[0].Start_Time__c <> null) ? emsg.replace('{!Assigned_Volunteer__c.Start_Time__c}', startDatetime.format('hh:mm a')) : emsg.replace('{!Assigned_Volunteer__c.Start_Time__c}', '');
            	} 
                
                if(s.get('End_Date__c') != null && s.get('End_Time__c') != null){
                    enddt = DateTime.newInstance(((Date)s.get('End_Date__c')).year(),((Date)s.get('End_Date__c')).month(),((Date)s.get('End_Date__c')).day(), ((Time)s.get('End_Time__c')).hour(), ((Time)s.get('End_Time__c')).minute(), ((Time)s.get('End_Time__c')).second());
        			emsg = emsg.replace('{!Assigned_Volunteer__c.End_Date__c}', enddt.format('dd-MMM-yyyy'));
            		emsg = emsg.replace('{!Assigned_Volunteer__c.End_Time__c}', enddt.format('hh:mm a'));
                }else{
                    emsg = (L[0].End_Date__c <> null) ? emsg.replace('{!Assigned_Volunteer__c.End_Date__c}', enddatetime.format('dd-MMM-yyyy')) : emsg.replace('{!Assigned_Volunteer__c.End_Date__c}', '');
            		emsg = (L[0].End_Time__c <> null) ? emsg.replace('{!Assigned_Volunteer__c.End_Time__c}', endDatetime.format('hh:mm a')) : emsg.replace('{!Assigned_Volunteer__c.End_Time__c}', '');
                }                
                emsg = (strname <> null) ? emsg.replace('{!Assigned_Volunteer__c.Contact__c}', strname) : emsg.replace('{!Assigned_Volunteer__c.Contact__c}', '');
                emsg = ((String)s.get('Invitation_URL__c') <> null) ? emsg.replace('{!Assigned_Volunteer__c.Invitation_URL__c}', (String)s.get('Invitation_URL__c')) : emsg.replace('{!Assigned_Volunteer__c.Invitation_URL__c}', '');
            	
                List<String> toemail = new List<String>();
                toemail.add((String)s.get('Email__c'));
            	Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            	email.setToAddresses(toemail); 
                email.setHtmlBody(emsg); 
            	email.setSubject(esub);
            	Messaging.SendEmailResult [] results = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
                
                s.put('Email_sent__c', Date.today());
                if(s.get('Assignee_Status__c') == 'Selected') s.put('Assignee_Status__c', 'Contacted');
            }
            if(!Test.isRunningTest())update(scope);  
        }
    }
    
    global void finish (Database.BatchableContext bc){
        //AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id =:BC.getJobId()];
        //Disbursement_Item__c d = [SELECT Id, Status__c, Batch_Remarks__c FROM Disbursement_Item__c WHERE Id = :disbItemId];
        
        //d.Status__c = 'Disbursed';
        //d.Batch_Remarks__c = 'The batch Apex job processed ' + a.TotalJobItems +' batches with '+ a.NumberOfErrors + ' failures.';
        //update(d);
    }
}