force-app/main/default/objects/Assigned_Volunteer__c/Assigned_Volunteer__c.object-meta.xml
<CustomObject>
    <label>Assigned Volunteer</label>
    <nameField>
        <label>Volunteer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assigned Volunteers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Accepted_Date__c.field-meta.xml
<CustomField>
    <fullName>Accepted_Date__c</fullName>
    <label>Accepted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Assignee_Status__c.field-meta.xml
<CustomField>
    <fullName>Assignee_Status__c</fullName>
    <label>Assignee Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Selected</fullName>
                <default>true</default>
                <label>Selected</label>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
                <isActive>false</isActive>
                <label>Declined</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Volunteer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assigned Volunteers</relationshipLabel>
    <relationshipName>Assigned_Volunteers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Email_Sent__c</fullName>
    <label>Email Sent</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Rejected_Date__c.field-meta.xml
<CustomField>
    <fullName>Rejected_Date__c</fullName>
    <label>Rejected Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Volunteer_Request__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Request__c</fullName>
    <label>Activity/Event</label>
    <referenceTo>Volunteer_Request__c</referenceTo>
    <relationshipLabel>Assigned Volunteers</relationshipLabel>
    <relationshipName>Assigned_Volunteers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/Volunteer_Request__c.object-meta.xml
<CustomObject>
    <label>Volunteer Request</label>
    <nameField>
        <label>Activity/Event</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/VolunteerAcceptDeclineController.cls
public class VolunteerAcceptDeclineController {
	public Volunteer_Request__c vr {get; set;}
    public Assigned_Volunteer__c pt {get; set;}
    public Id vrId {get; set;}
    public List<Assigned_Volunteer__c> participantRecords {get; set;}
    public List<ObjTable> ObjtblList {get;set;}
    
    public VolunteerAcceptDeclineController(ApexPages.StandardController controller) {
        vrId = ApexPages.CurrentPage().getParameters().get('id'); 
        pt = new Assigned_Volunteer__c();
        pt.Volunteer_Request__c = vrId;
        pt.Assignee_Status__c = 'Registered';
        refreshTable();
                        
    }
    public void refreshTable(){
        vr = [SELECT Id, name FROM Volunteer_Request__c WHERE Id = :pt.Volunteer_Request__c];
        
        ObjtblList = new List<ObjTable>();
        if(pt.Assignee_Status__c == null){
            participantRecords = [SELECT Id
                              ,name
                              ,Contact__r.Lastname
                              ,Assignee_Status__c
                              ,Email_Sent__c
                              FROM Assigned_Volunteer__c WHERE Volunteer_Request__c = :pt.Volunteer_Request__c]; 
        }else{
			participantRecords = [SELECT Id
                              ,name
                              ,Contact__r.Lastname
                              ,Assignee_Status__c
                              ,Email_Sent__c
                              FROM Assigned_Volunteer__c WHERE Volunteer_Request__c = :pt.Volunteer_Request__c AND Assignee_Status__c = :pt.Assignee_Status__c]; 
        }
        
        for(Assigned_Volunteer__c v : participantRecords ){
            ObjTable obj = new ObjTable();
            obj.rowObj = v;
            ObjtblList.add(obj);
        }                      
    }
    
    public PageReference acceptVolunteer(){
        List<Assigned_Volunteer__c> pList = new List<Assigned_Volunteer__c>();
        integer iselect = 0;
        for(ObjTable obj: ObjtblList ){
            if(obj.selected == true){
                Assigned_Volunteer__c p = obj.rowObj ;
                p.Assignee_Status__c = 'Accepted';
                p.Accepted_Date__c = Date.today();
                p.Rejected_Date__c = null;
                pList.add(p);
                iselect++;
            }
        }
        try{
            if(iselect == 0){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'No Volunteer selected.'));
            }else{
                update(pList );
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, pList.size()+ ' Volunteer(s) is Accepted.'));
            }
        }catch(Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Error: Unable to reject this Participant. ERROR CODE:'+e.getMessage()));
        }
        return null;
    }
    public PageReference declineVolunteer(){
        List<Assigned_Volunteer__c> pList = new List<Assigned_Volunteer__c>();
        integer iselect = 0;
        for(ObjTable obj: ObjtblList ){
            if(obj.selected == true){
                Assigned_Volunteer__c p = obj.rowObj ;
                p.Assignee_Status__c = 'Declined';
                p.Rejected_Date__c = Date.today();
                p.Accepted_Date__c = null;
                pList.add(p);
                iselect++;
            }
        }
        try{
            if(iselect == 0){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'No Volunteer selected.'));
            }else{
                update(pList);
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, pList.size()+ ' Volunteer(s) is Declined.'));
            }
        }catch(Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Error: Unable to reject this Volunteer. ERROR CODE:'+e.getMessage()));
        }
        
        return null;
    }
    public PageReference back(){
        pageReference pg = new pageReference('/'+vrId);
        pg.setRedirect(true);
        return pg;
    }
    public PageReference selectAll(){
        for(ObjTable obj : ObjtblList ){
            obj.selected = true;
        }
        return null;
    } 
    public PageReference unselectAll(){
        for(ObjTable obj : ObjtblList ){
            obj.selected = false;
        }
        return null;
    }
    
    public class ObjTable{
        public boolean selected {get; set;}
        public Assigned_Volunteer__c rowObj {get; set;}
    }
}