force-app/main/default/objects/Assigned_Volunteer__c/Assigned_Volunteer__c.object-meta.xml
<CustomObject>
    <label>Assigned Volunteer</label>
    <nameField>
        <label>Volunteer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assigned Volunteers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Assignee_Status__c.field-meta.xml
<CustomField>
    <fullName>Assignee_Status__c</fullName>
    <label>Assignee Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Selected</fullName>
                <default>true</default>
                <label>Selected</label>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
                <isActive>false</isActive>
                <label>Declined</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Uploaded__c.field-meta.xml
<CustomField>
    <fullName>Uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Uploaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Volunteer_Request__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Request__c</fullName>
    <label>Activity/Event</label>
    <referenceTo>Volunteer_Request__c</referenceTo>
    <relationshipLabel>Assigned Volunteers</relationshipLabel>
    <relationshipName>Assigned_Volunteers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Email_Notification__c.field-meta.xml
<CustomField>
    <fullName>Email_Notification__c</fullName>
    <label>Email Notification</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Participant_Lastname__c.field-meta.xml
<CustomField>
    <fullName>Participant_Lastname__c</fullName>
    <label>Participant Lastname (upload)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Programme_Event__c.field-meta.xml
<CustomField>
    <fullName>Programme_Event__c</fullName>
    <label>Programme/ Event</label>
    <referenceTo>Programme_Events__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Selected</fullName>
                <default>true</default>
                <label>Selected</label>
            </value>
            <value>
                <fullName>Invitation Sent</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Absent</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Withdraw</fullName>
                <label>Withdrawn</label>
            </value>
            <value>
                <fullName>Registered</fullName>
                <isActive>false</isActive>
                <label>Registered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Uploaded__c.field-meta.xml
<CustomField>
    <fullName>Uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Uploaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Programme_Events__c/Programme_Events__c.object-meta.xml
<CustomObject>
    <label>Programme/ Event</label>
    <nameField>
        <label>Programme/ Events Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programme/ Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Programme_Events__c/fields/Engagement_Type__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Type__c</fullName>
    <inlineHelpText>Please Select Direct/Indirect Patient Involvement</inlineHelpText>
    <label>Engagement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Indirect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Programme_Events__c/fields/Event_Attire__c.field-meta.xml
<CustomField>
    <fullName>Event_Attire__c</fullName>
    <label>Event Attire</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Casual</fullName>
            </value>
            <value>
                <fullName>Smart Casual</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Programme_Events__c/fields/Programme_Description__c.field-meta.xml
<CustomField>
    <fullName>Programme_Description__c</fullName>
    <label>Programme Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Programme_Events__c/fields/Programme_Stage__c.field-meta.xml
<CustomField>
    <fullName>Programme_Stage__c</fullName>
    <label>Programme Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Programme_Events__c/fields/Venue_of_Event_or_Mobilisation__c.field-meta.xml
<CustomField>
    <fullName>Venue_of_Event_or_Mobilisation__c</fullName>
    <label>Venue of Event or Mobilisation</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/Volunteer_Request__c.object-meta.xml
<CustomObject>
    <label>Volunteer Request</label>
    <nameField>
        <label>Activity/Event</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Request__c/fields/Programme_Event__c.field-meta.xml
<CustomField>
    <fullName>Programme_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programme/ Event</label>
    <referenceTo>Programme_Events__c</referenceTo>
    <relationshipLabel>Volunteer Requests</relationshipLabel>
    <relationshipName>Volunteer_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/fields/Programme_Stage__c.field-meta.xml
<CustomField>
    <fullName>Programme_Stage__c</fullName>
    <formula>TEXT(Programme_Event__r.Programme_Stage__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Programme Stage</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/fields/Recruitment_Deadline__c.field-meta.xml
<CustomField>
    <fullName>Recruitment_Deadline__c</fullName>
    <label>Recruitment Deadline</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/recordTypes/Direct.recordType-meta.xml
<RecordType>
    <fullName>Direct</fullName>
    <active>true</active>
    <label>Direct</label>
</RecordType>

force-app/main/default/classes/TestInvitationEmail.cls
@isTest
public class TestInvitationEmail {
	@isTest static void TestUploadParticipantController(){
        integer progNums = 1;
        List<Programme_Events__c> progList = new List<Programme_Events__c>();
        for(Integer i=0; i<progNums; i++) {
            Programme_Events__c p = new Programme_Events__c();
            p.Name = 'Test Programme';
          //  p.Category__c = 'One-Time';
            p.Start_Date_Time__c = Datetime.now().addDays(i+1);
            p.End_Date_Time__c = Datetime.now().addDays(i+5);
            p.Programme_Stage__c = 'Planned';
            p.Engagement_Type__c = 'Direct';
            p.Programme_Description__c = 'Description';
            p.Venue_of_Event_or_Mobilisation__c = 'Venue';
            p.Event_Attire__c = 'Casual';
            progList.add(p);
        }
        insert(progList);
        
        string strSelected;
        List<EmailTemplate> etList = [SELECT name,subject,Body,DeveloperName,Id,HTMLValue  FROM EmailTemplate limit 1];
        for(EmailTemplate e : etList){
            strSelected = e.Id;
        }
        Test.startTest();
        ApexPages.CurrentPage().getParameters().put('id', progList.get(0).Id);
        UploadParticipantController v = new UploadParticipantController(new ApexPages.StandardController(progList.get(0)));
        String s = 	'Fulname,Email,Mobile\n'+
				   	'Apple Pine 1,apple1@email.com,99999747\n'+
					'Apple Pine 2,apple2@email.com,88888888\n'+
					'Apple Pine 3,apple3@email.com,99987455';
        v.csvFileBody = Blob.valueOf(s);
        List<Participant__c> pList = [SELECT Id, Name, Programme_Event__c, Status__c FROM Participant__c WHERE Programme_Event__c = :progList.get(0).Id];
        v.back();
        v.importCSVFile();
        ApexPages.CurrentPage().getParameters().put('strSelected', strSelected);
        ProgEvSendInvitationEmailController pc = new ProgEvSendInvitationEmailController(new ApexPages.StandardController(progList.get(0)));
        pc.strSelected = strSelected;
        pc.PreviewEmail();
        pc.selectAll();
        pc.unselectAll();
        pc.refreshAssignedVolunteer();
        pc.selectAll();
        pc.sendEmailInBatch();
        pc.back();    
        
        
        Participant__c p = new Participant__c();
        p.Participant_Lastname__c = 'Testing Participant';
        p.Email_Notification__c = 'testing@participant.com';
        p.Mobile__c = '94736264';
        p.uploaded__c = true;
        p.Programme_Event__c = progList.get(0).Id;
        insert(p);
        ApexPages.CurrentPage().getParameters().put('id', p.Id);
		ParticipantAcceptRejectController ar = new ParticipantAcceptRejectController(new ApexPages.StandardController(p)); 
        ar.acceptVolunteer();
        ar.declineVolunteer();
        ar.back();
        Test.stopTest();
    }
    @isTest static void TestUploadVolunteerController(){
        integer progNums = 1;
        List<Volunteer_Request__c> progList = new List<Volunteer_Request__c>();
        for(Integer i=0; i<progNums; i++) {
            Volunteer_Request__c v = new Volunteer_Request__c();
            v.Name = 'Test VR';
            v.Start_Date__c = Date.today().addDays(i+3);
            v.End_Date__c = Date.today().addDays(i+9);
            v.RecordTypeId = Schema.SObjectType.Volunteer_Request__c.getRecordTypeInfosByName().get('Direct').getRecordTypeId();
            v.Start_Time__c = Time.newInstance(5, 0, 0, 0);
            v.End_Time__c = Time.newInstance(8, 0, 0, 0);
            v.Recruitment_Deadline__c = Date.today();
            progList.add(v);
        }
        insert(progList);
        Volunteer_Request__c v = progList[0];
        v.Start_Date__c = Date.today().addDays(-30);
        v.End_Date__c = Date.today().addDays(-10);
        update(v);
        v.Start_Date__c = Date.today().addDays(1);
        v.End_Date__c = Date.today().addDays(5);
        update(v);
        v.Start_Date__c = Date.today().addDays(-1);
        v.End_Date__c = Date.today().addDays(5);
        update(v);
        string strSelected;
        List<EmailTemplate> etList = [SELECT name,subject,Body,DeveloperName,Id,HTMLValue  FROM EmailTemplate limit 1];
        for(EmailTemplate e : etList){
            strSelected = e.Id;
        }
        
        Test.startTest();
        
        ApexPages.CurrentPage().getParameters().put('id', progList.get(0).Id);
        UploadVolunteerController uv = new UploadVolunteerController(new ApexPages.StandardController(progList.get(0)));
        String s = 	'Fulname,Email,Mobile\n'+
				   	'Apple Pine 1,apple1@email.com,99999747\n'+
					'Apple Pine 2,apple2@email.com,88888888\n'+
					'Apple Pine 3,apple3@email.com,99987455';
        uv.csvFileBody = Blob.valueOf(s);
        uv.importCSVFile(); 
        List<Contact> cList = [SELECT id, Name, Email FROM Contact];
        system.debug('Contact Test: '+cList.size());
        for(Contact c : cList){
            system.debug('Email: '+c.Email);
        }
        ApexPages.CurrentPage().getParameters().put('strSelected', strSelected);
        VRSendInvitationEmailController pc = new VRSendInvitationEmailController(new ApexPages.StandardController(progList.get(0)));
        pc.strSelected = strSelected;
        pc.PreviewEmail();
        pc.selectAll();
        pc.unselectAll();
        pc.refreshAssignedVolunteer();
        pc.selectAll();
        pc.sendEmailInBatch();
        pc.back();  
        
        /*List<Assigned_Volunteer__c> pList = [SELECT Id, Name, Volunteer_Request__c, Assignee_Status__c FROM Assigned_Volunteer__c WHERE Volunteer_Request__c = :progList.get(0).Id];
        
        ApexPages.CurrentPage().getParameters().put('id', pList.get(0).Id);
		VRAcceptDeclineController ar = new VRAcceptDeclineController(new ApexPages.StandardController(pList.get(0))); 
        ar.acceptVolunteer();
        ar.declineVolunteer();
        ar.back();*/
        Test.stopTest();
    }
}