force-app/main/default/objects/Assigned_Volunteer__c/Assigned_Volunteer__c.object-meta.xml
<CustomObject>
    <label>Assigned Volunteer</label>
    <nameField>
        <label>Volunteer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assigned Volunteers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Assignee_Status__c.field-meta.xml
<CustomField>
    <fullName>Assignee_Status__c</fullName>
    <label>Assignee Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Selected</fullName>
                <default>true</default>
                <label>Selected</label>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
                <isActive>false</isActive>
                <label>Declined</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Volunteer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assigned Volunteers</relationshipLabel>
    <relationshipName>Assigned_Volunteers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Email_upload__c.field-meta.xml
<CustomField>
    <fullName>Email_upload__c</fullName>
    <label>Email (upload)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Uploaded__c.field-meta.xml
<CustomField>
    <fullName>Uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Uploaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Volunteer_Name_upload__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Name_upload__c</fullName>
    <label>Volunteer Name (upload)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assigned_Volunteer__c/fields/Volunteer_Request__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Request__c</fullName>
    <label>Activity/Event</label>
    <referenceTo>Volunteer_Request__c</referenceTo>
    <relationshipLabel>Assigned Volunteers</relationshipLabel>
    <relationshipName>Assigned_Volunteers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/Volunteer_Request__c.object-meta.xml
<CustomObject>
    <label>Volunteer Request</label>
    <nameField>
        <label>Activity/Event</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/UploadVolunteerController.cls
public class UploadVolunteerController {
    public Blob csvFileBody{get;set;}
    public string csvAsString{get;set;}
    public String[] csvFileLines{get;set;}
    public List<List<String>> dataAll {get;set; }    
    public List<Assigned_Volunteer__c> volunteerlist{get;set;}
    //public List<Assigned_Volunteer__c> updatedList{get;set;}
    public String vrId {get; set;}
    public Integer totalData {get;set;}
    public Integer totalProceed {get;set;}
    public Integer totalSuccess {get;set;}
    public Integer totalFailed {get;set;}
    public String strInfo {get; set;}
    
    
    public UploadVolunteerController(ApexPages.StandardController controller) {
        vrId = ApexPages.CurrentPage().getParameters().get('id');
    }
      
    public PageReference importCSVFile(){
        //try{
            //csvAsString = csvFileBody.toString();
            Set<String> emails = new Set<String>(); 
            String strTmp;
        	totalData = 0;
			dataAll = new List<List<String>>(); 
        	csvFileLines = new String[]{};
        	volunteerlist = New List<Assigned_Volunteer__c>(); 
            system.debug('csvFileBody:'+ csvFileBody.tostring());
            CSVReader objCsv = new CSVReader(csvFileBody.toString());
            csvFileLines = objCsv.readLine();
            system.debug('csvFileLines:'+ csvFileLines.tostring());
            
            system.debug('csvFileLines:'+ csvFileLines.tostring());
            while (csvFileLines != null){
                dataAll.add(csvFileLines);
                if(csvFileLines.size() > 1 && csvFileLines[1] != null && csvFileLines[1] != ''){
                    strTmp = csvFileLines[1];
                    if (emails.contains(strTmp)) {
                        // duplicate
                        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Error: Duplicate Volunteer ' + strTmp));
                        totalData = 0;
                        return null;
                    }
                    else {
                        emails.add(strTmp);
                    }
                }else{
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Error: Email cannot be blank. Please fix the data.'));
                    totalData = 0;
                    return null;
                }
                totalData++;                
                csvFileLines = objCsv.readLine();
            }
            totalData = totalData-1;
            system.debug('emails = ' +emails.size());
            List<Assigned_Volunteer__c> updatedVolunteerList = [SELECT Id, Volunteer_Name_upload__c, Uploaded__c, Email_Upload__c, Assignee_Status__c, Contact__r.Email, Mobile__c FROM Assigned_Volunteer__c WHERE (Email_Upload__c  IN :emails OR Contact__r.Email IN :emails) AND Volunteer_Request__c = :vrId];
            system.debug(updatedVolunteerList.size());
            Map<String, Assigned_Volunteer__c> volunteerMap = new Map<String, Assigned_Volunteer__c>();
            for(Assigned_Volunteer__c p : updatedVolunteerList){
                if(p.Contact__r.Email != null){
                    volunteerMap.put(p.Contact__r.Email, p);
                }else{
                    volunteerMap.put(p.Email_Upload__c, p);
                }
                system.debug(p.Volunteer_Name_upload__c +' and '+p.Email_Upload__c);
            }
            
            Map<String, Assigned_Volunteer__c> upsertParMap = new Map<String, Assigned_Volunteer__c>();
            integer k = 0, j = 0;
        	strInfo = '';
            for(Integer i=1; i<dataAll.size(); i++){
                csvFileLines = dataAll[i];
                if(volunteerMap != null && volunteerMap.get(csvFileLines[1]) != null){
                    Assigned_Volunteer__c partObj =  volunteerMap.get(csvFileLines[1]);
                    partObj.Assignee_Status__c = 'Selected';
                    partObj.Uploaded__c = true;
                    partObj.Mobile__c = csvFileLines[2]; 
                    
                    upsertParMap.put(partObj.Email_Upload__c, partObj);
                    k++;
                }else{
                    Assigned_Volunteer__c partObj = new Assigned_Volunteer__c() ;
                    partObj.Name = csvFileLines[0];
                    partObj.Volunteer_Name_upload__c = csvFileLines[0];
                    partObj.Email_Upload__c = csvFileLines[1];
                    partObj.Mobile__c = csvFileLines[2];
                    partObj.Assignee_Status__c = 'Selected';
                    partObj.Uploaded__c = true;
                    partObj.Volunteer_Request__c = vrId ; 
                    upsertParMap.put(partObj.Email_Upload__c, partObj);
                    j++;
                }
            }
            String msg = '';
            if(upsertParMap != null && upsertParMap.values().size() > 0){
                Database.UpsertResult[] srList;
            	Database.Error[] listErr;
                try{
                    srList = Database.upsert(upsertParMap.values(), false);
                	volunteerlist = upsertParMap.values();
                	msg += ' '+j+' records inserted and '+k+' records updated.';
                }catch (DmlException e){
                    ApexPages.addMessages(e);
                }
                
                totalSuccess = 0;
                totalFailed = 0;
                totalProceed = 0;
                
                List<String> stContactSuccess = new List<String>();
                if (srList != null) {
                    for(Database.UpsertResult sr: srList) {
                        totalProceed++;
                        if (listErr != null) listErr.clear();
                        
                        if (sr.isSuccess()) {
                            stContactSuccess.add(sr.getId());
                            totalSuccess++;
                        }
                        else {
                            listErr = sr.getErrors();
                            totalFailed++;
                            for(j = 0; j < listErr.size();j++) {
                                strInfo += 'Row ' + String.valueOf(totalFailed) + ': ' + listErr[j].getMessage() + '<br/>\n';
                            }
                        }
                    }
                }
            }
            
            ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.CONFIRM,'Participant is processed.'+msg);
            ApexPages.addMessage(errorMessage);
        	
            return null;
            //insert participantlist;
        /*}catch (Exception e){
            ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.ERROR,'An error has occured while importin data Please make sure input csv file is correct'+e.getMessage());
            ApexPages.addMessage(errorMessage);
            return null;
        }  */
    }
    public void updatenull(){
        
    }
    
    public PageReference back(){
        pageReference pg = new pageReference('/'+vrId);
        pg.setRedirect(true);
        return pg;
    } 
}