force-app/main/default/objects/Contact/fields/Donor_Type__c.field-meta.xml
<CustomField>
    <fullName>Donor_Type__c</fullName>
    <defaultValue>if( $RecordType.DeveloperName = &apos;Contact&apos;, &apos;Organisation&apos;, null)</defaultValue>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Organisation</fullName>
            </value>
            <value>
                <fullName>Anonymous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ID_No__c.field-meta.xml
<CustomField>
    <fullName>ID_No__c</fullName>
    <externalId>true</externalId>
    <label>Tax Recipient ID No</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/ID_Type__c.field-meta.xml
<CustomField>
    <fullName>ID_Type__c</fullName>
    <label>Tax Recipient ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NRIC</fullName>
            </value>
            <value>
                <fullName>FIN</fullName>
            </value>
            <value>
                <fullName>UEN-Business</fullName>
            </value>
            <value>
                <fullName>UEN-Local Company</fullName>
            </value>
            <value>
                <fullName>UEN-Others</fullName>
            </value>
            <value>
                <fullName>ITR</fullName>
            </value>
            <value>
                <fullName>ASGD</fullName>
            </value>
            <value>
                <fullName>OTHERS</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
                <isActive>false</isActive>
                <label>BC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/isTaxRecipient__c.field-meta.xml
<CustomField>
    <fullName>isTaxRecipient__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isTaxRecipient</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Individual.recordType-meta.xml
<RecordType>
    <fullName>Individual</fullName>
    <active>true</active>
    <label>Individual</label>
</RecordType>

force-app/main/default/objects/Donations__c/Donations__c.object-meta.xml
<CustomObject>
    <label>Donations</label>
    <nameField>
        <displayFormat>{yy}{mm}-{000000}</displayFormat>
        <label>Donation No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Donations__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Cleared_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Cleared_Datetime__c</fullName>
    <label>Cleared Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donation_Amount__c.field-meta.xml
<CustomField>
    <fullName>Donation_Amount__c</fullName>
    <label>Donation Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donation_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Donation_Datetime__c</fullName>
    <label>Donation Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donation_Status__c.field-meta.xml
<CustomField>
    <fullName>Donation_Status__c</fullName>
    <defaultValue>&apos;Pending&apos;</defaultValue>
    <label>Donation Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Payment_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>Cheque Returned</fullName>
            </value>
            <value>
                <fullName>Giro Rejected</fullName>
            </value>
            <value>
                <fullName>CC Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donor_Account__c.field-meta.xml
<CustomField>
    <fullName>Donor_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Will be filled by trigger</description>
    <inlineHelpText>Don&apos;t need to be manually filled, will be automatically overwritten by trigger,</inlineHelpText>
    <label>Donor Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donor_Name__c.field-meta.xml
<CustomField>
    <fullName>Donor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the person who made the donation and paid for it</description>
    <label>Donor Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Donor_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donor_Type__c.field-meta.xml
<CustomField>
    <fullName>Donor_Type__c</fullName>
    <label>Donor Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Organisation</fullName>
            </value>
            <value>
                <fullName>Anonymous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Email_Entered__c.field-meta.xml
<CustomField>
    <fullName>Email_Entered__c</fullName>
    <label>Email (Entered)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Frequency_Period__c.field-meta.xml
<CustomField>
    <fullName>Frequency_Period__c</fullName>
    <formula>Text(Recurring_Donation__r.Frequency__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Frequency Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Frequency_Type__c.field-meta.xml
<CustomField>
    <fullName>Frequency_Type__c</fullName>
    <defaultValue>&quot;One-time&quot;</defaultValue>
    <label>Frequency Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-time</fullName>
                <default>true</default>
                <label>One-time</label>
            </value>
            <value>
                <fullName>Recurring</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Id_No__c.field-meta.xml
<CustomField>
    <fullName>Id_No__c</fullName>
    <formula>Donor_Name__r.ID_No__c</formula>
    <label>Donor Id No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/ID_Type__c.field-meta.xml
<CustomField>
    <fullName>ID_Type__c</fullName>
    <formula>Text(  Donor_Name__r.ID_Type__c )</formula>
    <label>Donor Id Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>eNETS</fullName>
            </value>
            <value>
                <fullName>Giro</fullName>
            </value>
            <value>
                <fullName>PayNow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Recurring_Donation__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Donation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recurring Donation</label>
    <referenceTo>Recurring_Donation__c</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Tax_Deductible__c.field-meta.xml
<CustomField>
    <fullName>Tax_Deductible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tax Deductible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Tax_Recipient_ID_No_Entered__c.field-meta.xml
<CustomField>
    <fullName>Tax_Recipient_ID_No_Entered__c</fullName>
    <label>Tax Recipient ID No. (Entered)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donations__c/recordTypes/Cash.recordType-meta.xml
<RecordType>
    <fullName>Cash</fullName>
    <active>true</active>
    <label>Cash</label>
</RecordType>

force-app/main/default/objects/Recurring_Donation__c/Recurring_Donation__c.object-meta.xml
<CustomObject>
    <label>Recurring Donation</label>
    <nameField>
        <displayFormat>RD{yymmdd}{0000}</displayFormat>
        <label>RD No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recurring Donations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Recurring_Donation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recurring Donations</relationshipLabel>
    <relationshipName>Recurring_Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recurring_Donation__c/fields/Donor_Name__c.field-meta.xml
<CustomField>
    <fullName>Donor_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Donor Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Recurring Donations</relationshipLabel>
    <relationshipName>Recurring_Donations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recurring_Donation__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bi monthly</fullName>
                <isActive>false</isActive>
                <label>Bi monthly</label>
            </value>
            <value>
                <fullName>Bi weekly</fullName>
                <isActive>false</isActive>
                <label>Bi weekly</label>
            </value>
            <value>
                <fullName>Half Yearly</fullName>
                <isActive>false</isActive>
                <label>Half Yearly</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
                <isActive>false</isActive>
                <label>Quarterly</label>
            </value>
            <value>
                <fullName>Weekly</fullName>
                <isActive>false</isActive>
                <label>Weekly</label>
            </value>
            <value>
                <fullName>Yearly</fullName>
                <isActive>false</isActive>
                <label>Yearly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recurring_Donation__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Giro</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recurring_Donation__c/fields/RD_Status__c.field-meta.xml
<CustomField>
    <fullName>RD_Status__c</fullName>
    <defaultValue>&apos;Pending&apos;</defaultValue>
    <label>RD Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recurring_Donation__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Recurring_Donation__c/fields/Tax_Deductible__c.field-meta.xml
<CustomField>
    <fullName>Tax_Deductible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tax Deductible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DonationTest.cls
@isTest
public class DonationTest {
    @isTest
  /**  private static void runTest(){
        // create contact
        // create recurring donation
        // create donation
        // update donation to cleared
        
        Contact c = new Contact();
        c.LastName = 'Testing';
        c.RecordTypeId = Utils.GetRecordTypeId('Contact', 'Individual');
        //c.Email_Personal__c = 'testing@interaktiv.sg';
        c.Email = 'testingers@interaktiv.sg';
        c.Donor_Type__c = 'Individual';
        insert(c);
        
        c = [SELECT Id, AccountId, LastName FROM Contact WHERE Id = :c.Id limit 1];
        
        Recurring_Donation__c rd = new Recurring_Donation__c();
        rd.Amount__c = 100;
        rd.Donor_Name__c = c.Id;
        rd.Account__c = c.AccountId;
        rd.Start_Date__c = Date.today();
        rd.End_Date__c = Date.today().addDays(90);
        rd.Frequency__c = 'Monthly';
        rd.RD_Status__c = 'Approved';
        rd.Payment_Method__c = 'Credit Card';
        insert(rd);
        
        rd = [SELECT Id, Frequency__c,Amount__c FROM Recurring_Donation__c WHERE Id = :rd.Id limit 1];
        system.debug(rd);
        
        Donations__c d = new Donations__c();
        d.Donor_Account__c = c.AccountId;
        d.Recurring_Donation__c = rd.Id;
        d.Donor_Name__c= c.Id;
        d.Donation_Datetime__c = Datetime.now();
        //d.Cleared_Datetime__c = Datetime.now();
        d.Donation_Amount__c = rd.Amount__c;
        d.Donation_Status__c = 'Cleared';
        d.Frequency_Type__c= 'Recurring';
        d.Payment_Method__c = 'Credit Card';
        d.Donor_Type__c='Individual';
        //d.Frequency_Period__c = 'Monthly';
        insert(d);
        
        Donations__c d1 = new Donations__c();
        d1.Donor_Account__c = c.AccountId;
        d1.Donor_Name__c = c.Id;
        d1.Donation_Datetime__c = Datetime.now();
        d1.Cleared_Datetime__c = Datetime.now();
        d1.Donation_Amount__c = rd.Amount__c;
		d1.Donor_Type__c='Individual';
        d1.Donation_Status__c = 'Cleared';
        d1.Tax_Deductible__c = true;
		d1.Payment_Method__c = 'Credit Card';
        insert(d1);


        Donations__c d2 = new Donations__c();
        d2.Donor_Account__c = c.AccountId;
        d2.Donor_Name__c = c.Id;
        d2.Donation_Datetime__c = Datetime.now();
        d2.Cleared_Datetime__c = Datetime.now();
        d2.Donation_Amount__c = rd.Amount__c;
		d2.Donor_Type__c='Individual';
        d2.Donation_Status__c = 'Received';
        d2.Tax_Deductible__c = true;
		d2.Payment_Method__c = 'Credit Card';
        d2.Recurring_Donation__c = rd.Id;
        d2.Frequency_Type__c = 'Recurring';
        //d2.Frequency_Period__c = 'Monthly';
        insert(d2);
    
        Donations__c d3 = [SELECT Id, Donor_Account__c, Donation_Status__c FROM Donations__c WHERE Donation_Status__c = 'Received' AND Recurring_Donation__c = :rd.Id limit 1];
        system.debug(d3);
        d3.Cleared_Datetime__c = Datetime.now();
        d3.Donation_Status__c = 'Cleared';
        update(d3);
		
    } **/
    
    public static void runTest2(){
        Contact c = new Contact();
        c.LastName = 'test1';
        c.RecordTypeId = Utils.GetRecordTypeId('Contact', 'Individual');
        c.Email = 'test1@gmail.com';
        c.Donor_Type__c = 'Individual';
        c.isTaxRecipient__c = true;
        c.ID_Type__c = 'NRIC';
        c.ID_No__c = 'S71080T82';
        c.Tax_Recipient_Full_Name__c = 'test1';
        insert(c);
        
        c = [SELECT Id, AccountId, LastName FROM Contact WHERE Id = :c.Id limit 1];
        
        Donations__c d = new Donations__c();
        d.Donor_Account__c = c.AccountId;
        d.Donor_Name__c= c.Id;
        d.Email_Entered__c = 'test1@gmail.com';
        d.Donation_Datetime__c = Datetime.now();
        d.Donation_Amount__c = 10;
        d.Donation_Status__c = 'Cleared';
        d.Payment_Method__c = 'Credit Card';
        d.Cleared_Datetime__c = Datetime.now();
        d.Donor_Type__c='Individual';
        d.Tax_Recipient_ID_No_Entered__c = 'S71080T82';
        d.ID_Type_Entered__c = 'NRIC';
        d.Tax_Recipient_Full_Name_Entered__c = 'test1';
        insert(d);
        
    }
    
    @isTest
    public static void runTest3(){
        
        Donations__c d = new Donations__c();
     
        d.RecordTypeId = Schema.SObjectType.Donations__c.getRecordTypeInfosByName().get('Cash').getRecordTypeId();
        d.Donor_Type__c = 'Organisation';
        d.Donation_Date__c = Date.today();
        d.Donation_Datetime__c = datetime.now();
        d.Cleared_Datetime__c = datetime.now();
        d.Full_Name_Entered__c = 'Bruce';
        d.Email_Entered__c = 'bruce@mail.com';
        d.Donation_Amount__c = 10;
        d.Donation_Status__c = 'Cleared';
        d.Payment_Method__c = 'Credit Card';
        
        insert(d);
        
    }
    /**
    @isTest
    public static void runTest4(){
        List<Donations__c> listD = new List<Donations__c>();
        
        Contact c = new Contact();
        c.LastName = 'test1';
        c.RecordTypeId = Utils.GetRecordTypeId('Contact', 'Individual');
        c.Email = 'test1@gmail.com';
        c.Donor_Type__c = 'Individual';
        c.isTaxRecipient__c = true;
        c.ID_Type__c = 'NRIC';
        c.ID_No__c = 'S71080T82';
        c.Tax_Recipient_Full_Name__c = 'test1';
        insert(c);
        c = [SELECT Id, AccountId, LastName FROM Contact WHERE Id = :c.Id limit 1];
        
        Donations__c d = new Donations__c();
        d.Donor_Account__c = c.AccountId;
        d.Donor_Name__c= c.Id;
        d.Email_Entered__c = 'test1@gmail.com';
        d.Donation_Datetime__c = Datetime.now();
        d.Donation_Amount__c = 10;
        d.Donation_Status__c = 'Cleared';
        d.Payment_Method__c = 'Credit Card';
        d.Cleared_Datetime__c = Datetime.now();
        d.Donor_Type__c='Individual';
        d.Tax_Recipient_ID_No_Entered__c = 'S71080T82';
        d.ID_Type_Entered__c = 'NRIC';
        d.Tax_Recipient_Full_Name_Entered__c = 'test1';
        insert(d);
        
        Contact c2 = new Contact();
        c2.LastName = 'test2';
        c2.RecordTypeId = Utils.GetRecordTypeId('Contact', 'Individual');
        c2.Email = 'test2@gmail.com';
        c2.Donor_Type__c = 'Individual';
        c2.isTaxRecipient__c = true;
        c2.ID_Type__c = 'NRIC';
        c2.ID_No__c = 'S71080T82';
        c2.Tax_Recipient_Full_Name__c = 'test2';
        insert(c2);
        c2 = [SELECT Id, AccountId, LastName FROM Contact WHERE Id = :c.Id limit 1];
        
        Donations__c d2 = new Donations__c();
        d2.Donor_Account__c = c2.AccountId;
        d2.Donor_Name__c= c2.Id;
        d2.Email_Entered__c = 'test2@gmail.com';
        d2.Donation_Datetime__c = Datetime.now();
        d2.Donation_Amount__c = 10;
        d2.Donation_Status__c = 'Cleared';
        d2.Payment_Method__c = 'Credit Card';
        d2.Cleared_Datetime__c = Datetime.now();
        d2.Donor_Type__c='Individual';
        d2.Tax_Recipient_ID_No_Entered__c = 'S71080T82';
        d2.ID_Type_Entered__c = 'NRIC';
        d2.Tax_Recipient_Full_Name_Entered__c = 'test2';
        insert(d);
        
        listD.add(d);
        listD.add(d2);
        
        DonationsTriggerHandler Dhan = new DonationsTriggerHandler();
        Dhan.getAccountIdBulk(listD);
    }**/
}