force-app/main/default/objects/Contact/fields/Donor_Type__c.field-meta.xml
<CustomField>
    <fullName>Donor_Type__c</fullName>
    <defaultValue>if( $RecordType.DeveloperName = &apos;Contact&apos;, &apos;Organisation&apos;, null)</defaultValue>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Organisation</fullName>
            </value>
            <value>
                <fullName>Anonymous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ID_No__c.field-meta.xml
<CustomField>
    <fullName>ID_No__c</fullName>
    <externalId>true</externalId>
    <label>Tax Recipient ID No</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/ID_Type__c.field-meta.xml
<CustomField>
    <fullName>ID_Type__c</fullName>
    <label>Tax Recipient ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NRIC</fullName>
            </value>
            <value>
                <fullName>FIN</fullName>
            </value>
            <value>
                <fullName>UEN-Business</fullName>
            </value>
            <value>
                <fullName>UEN-Local Company</fullName>
            </value>
            <value>
                <fullName>UEN-Others</fullName>
            </value>
            <value>
                <fullName>ITR</fullName>
            </value>
            <value>
                <fullName>ASGD</fullName>
            </value>
            <value>
                <fullName>OTHERS</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
                <isActive>false</isActive>
                <label>BC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Individual.recordType-meta.xml
<RecordType>
    <fullName>Individual</fullName>
    <active>true</active>
    <label>Individual</label>
</RecordType>

force-app/main/default/objects/Donations__c/Donations__c.object-meta.xml
<CustomObject>
    <label>Donations</label>
    <nameField>
        <displayFormat>{yy}{mm}-{000000}</displayFormat>
        <label>Donation No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Donations__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Cleared_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Cleared_Datetime__c</fullName>
    <label>Cleared Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donation_Amount__c.field-meta.xml
<CustomField>
    <fullName>Donation_Amount__c</fullName>
    <label>Donation Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donation_Date__c.field-meta.xml
<CustomField>
    <fullName>Donation_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Donation Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donation_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Donation_Datetime__c</fullName>
    <label>Donation Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donation_Status__c.field-meta.xml
<CustomField>
    <fullName>Donation_Status__c</fullName>
    <defaultValue>&apos;Pending&apos;</defaultValue>
    <label>Donation Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Payment_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>Cheque Returned</fullName>
            </value>
            <value>
                <fullName>Giro Rejected</fullName>
            </value>
            <value>
                <fullName>CC Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donor_Name__c.field-meta.xml
<CustomField>
    <fullName>Donor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the person who made the donation and paid for it</description>
    <label>Donor Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Donor_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donor_Type__c.field-meta.xml
<CustomField>
    <fullName>Donor_Type__c</fullName>
    <label>Donor Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Organisation</fullName>
            </value>
            <value>
                <fullName>Anonymous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Frequency_Type__c.field-meta.xml
<CustomField>
    <fullName>Frequency_Type__c</fullName>
    <defaultValue>&quot;One-time&quot;</defaultValue>
    <label>Frequency Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-time</fullName>
                <default>true</default>
                <label>One-time</label>
            </value>
            <value>
                <fullName>Recurring</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Id_No__c.field-meta.xml
<CustomField>
    <fullName>Id_No__c</fullName>
    <formula>Donor_Name__r.ID_No__c</formula>
    <label>Donor Id No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/ID_Type__c.field-meta.xml
<CustomField>
    <fullName>ID_Type__c</fullName>
    <formula>Text(  Donor_Name__r.ID_Type__c )</formula>
    <label>Donor Id Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>eNETS</fullName>
            </value>
            <value>
                <fullName>Giro</fullName>
            </value>
            <value>
                <fullName>PayNow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Recurring_Donation__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Donation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recurring Donation</label>
    <referenceTo>Recurring_Donation__c</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Tax_Deductible__c.field-meta.xml
<CustomField>
    <fullName>Tax_Deductible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tax Deductible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Tax_Recipient_Individual__c.field-meta.xml
<CustomField>
    <fullName>Tax_Recipient_Individual__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Recipient Individual</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Donations (Tax Recipient Contact)</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donations__c/recordTypes/Cash.recordType-meta.xml
<RecordType>
    <fullName>Cash</fullName>
    <active>true</active>
    <label>Cash</label>
</RecordType>

force-app/main/default/objects/Recurring_Donation__c/Recurring_Donation__c.object-meta.xml
<CustomObject>
    <label>Recurring Donation</label>
    <nameField>
        <displayFormat>RD{yymmdd}{0000}</displayFormat>
        <label>RD No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recurring Donations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Recurring_Donation__c/fields/Donor_Name__c.field-meta.xml
<CustomField>
    <fullName>Donor_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Donor Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Recurring Donations</relationshipLabel>
    <relationshipName>Recurring_Donations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recurring_Donation__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bi monthly</fullName>
                <isActive>false</isActive>
                <label>Bi monthly</label>
            </value>
            <value>
                <fullName>Bi weekly</fullName>
                <isActive>false</isActive>
                <label>Bi weekly</label>
            </value>
            <value>
                <fullName>Half Yearly</fullName>
                <isActive>false</isActive>
                <label>Half Yearly</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
                <isActive>false</isActive>
                <label>Quarterly</label>
            </value>
            <value>
                <fullName>Weekly</fullName>
                <isActive>false</isActive>
                <label>Weekly</label>
            </value>
            <value>
                <fullName>Yearly</fullName>
                <isActive>false</isActive>
                <label>Yearly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recurring_Donation__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Giro</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recurring_Donation__c/fields/RD_Status__c.field-meta.xml
<CustomField>
    <fullName>RD_Status__c</fullName>
    <defaultValue>&apos;Pending&apos;</defaultValue>
    <label>RD Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recurring_Donation__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Recurring_Donation__c/fields/Tax_Deductible__c.field-meta.xml
<CustomField>
    <fullName>Tax_Deductible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tax Deductible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Recurring_Donation__c/fields/Tax_Recipient_Individual__c.field-meta.xml
<CustomField>
    <fullName>Tax_Recipient_Individual__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Recipient Individual</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Recurring Donations (Tax Recipient Individual)</relationshipLabel>
    <relationshipName>Recurring_Donations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RDTriggerHandlerTest.cls
@isTest
public class RDTriggerHandlerTest {
    //@isTest
    // scenario
    // creating Contact
    // then create RD with that Contact
    // then create a donation tagged to the contact and RD so the RDTriggerHandler will be able to create next donation record
    @isTest
    public static void rd(){
        Contact contactToInsert = new Contact(
            RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId(),
            Donor_Type__c = 'Individual',
            lastName = 'testSetup individual 1',
            Email = 'testSetup1@mail.com',
            ID_Type__c = 'NRIC',
            ID_No__c = 'NRIC-testSetup1',
            Tax_Recipient_Full_Name__c = 'testSetup individual 1'
        );
        Insert contactToInsert;

        Recurring_Donation__c rdToInsert = new Recurring_Donation__c(
            Donor_Name__c = contactToInsert.id,
            Amount__c = 100,
            Start_Date__c = System.today(),
            Payment_Method__c = 'Credit Card',
            Frequency__c = 'Monthly',
            RD_Status__c = 'Pending',
            Tax_Deductible__c = true,
            Tax_Recipient_Individual__c = contactToInsert.id
        );
        Insert rdToInsert;

        Donations__c donationToInsert = new Donations__c(
            RecordTypeId = Schema.SObjectType.Donations__c.getRecordTypeInfosByName().get('Cash').getRecordTypeId(),
            Donor_Type__c = 'Individual',
            Donation_Status__c = 'Cleared',
            Donation_Date__c = System.today(),
            Donation_Datetime__c = System.now(),
            Cleared_Datetime__c = System.now(),
            Frequency_Type__c = 'Recurring',
            Recurring_Donation__c = rdToInsert.id,
            Donor_Name__c = contactToInsert.id,
            Tax_Recipient_Individual__c = contactToInsert.id,
            Tax_Deductible__c = true,
            Donation_Amount__c = 100,
            Payment_Method__c = 'Credit Card'
        );
        Insert donationToInsert;

    }

    @isTest
    public static void runTest4(){
        RDTriggerHandler.getNextDeductionDate(Date.today(), 'Monthly', false);
        RDTriggerHandler.getNextDeductionDate(Date.today(), 'Weekly', false);
        RDTriggerHandler.getNextDeductionDate(Date.today(), 'Bi weekly', false);
        RDTriggerHandler.getNextDeductionDate(Date.today(), 'Bi monthly', false);
        RDTriggerHandler.getNextDeductionDate(Date.today(), 'Quarterly', false);
        RDTriggerHandler.getNextDeductionDate(Date.today(), 'Half Yearly', false);
        RDTriggerHandler.getNextDeductionDate(Date.today(), 'Yearly', false);
        RDTriggerHandler.getNextDeductionDate(Date.today(), 'Negative', false);
        RDTriggerHandler.getNextDeductionDate(Date.newInstance(2022, 1, 16), 'Weekly', true);
    }
}