force-app/main/default/objects/Contact/fields/Donor_Type__c.field-meta.xml
<CustomField>
    <fullName>Donor_Type__c</fullName>
    <defaultValue>if( $RecordType.DeveloperName = &apos;Contact&apos;, &apos;Organisation&apos;, null)</defaultValue>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Organisation</fullName>
            </value>
            <value>
                <fullName>Anonymous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Individual.recordType-meta.xml
<RecordType>
    <fullName>Individual</fullName>
    <active>true</active>
    <label>Individual</label>
</RecordType>

force-app/main/default/objects/Programme_Events__c/Programme_Events__c.object-meta.xml
<CustomObject>
    <label>Programme/ Event</label>
    <nameField>
        <label>Programme/ Events Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programme/ Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Programme_Events__c/fields/Active_Birthday_Programme__c.field-meta.xml
<CustomField>
    <fullName>Active_Birthday_Programme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active Birthday Programme</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Programme_Events__c/fields/Engagement_Type__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Type__c</fullName>
    <inlineHelpText>Please Select Direct/Indirect Patient Involvement</inlineHelpText>
    <label>Engagement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Indirect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Programme_Events__c/fields/Event_Attire__c.field-meta.xml
<CustomField>
    <fullName>Event_Attire__c</fullName>
    <label>Event Attire</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Casual</fullName>
            </value>
            <value>
                <fullName>Smart Casual</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Programme_Events__c/fields/Programme_Description__c.field-meta.xml
<CustomField>
    <fullName>Programme_Description__c</fullName>
    <label>Programme Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Programme_Events__c/fields/Venue_of_Event_or_Mobilisation__c.field-meta.xml
<CustomField>
    <fullName>Venue_of_Event_or_Mobilisation__c</fullName>
    <label>Venue of Event or Mobilisation</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BirthdayCronJobTest.cls
@isTest
class BirthdayCronJobTest {

	static testmethod void test() {
		
		Integer testMonth = date.today().month();
		Integer testDay = date.today().day();
		BirthdayCronJob BCJ = new BirthdayCronJob(); 
		
		//BCJ.sendMail(); 
		Programme_Events__c programEventObj= new Programme_Events__c(
        name='testing1',
        Engagement_Type__c='Direct',
        Programme_Description__c='Test',
        Event_Attire__c='Casual',
        Venue_of_Event_or_Mobilisation__c='test',
        Start_Date_Time__c= Date.today().addDays(-30),
        End_Date_Time__c= Date.today().addDays(30),
        Active_Birthday_Programme__c = true
        );
        insert programEventObj;
        
		Contact testContact = new Contact();
		testContact.FirstName = 'Test';
		testContact.LastName = 'Contact';
		testContact.Email = 'romipaytm@gmail.com';
		testContact.Birthdate = date.today();
        testContact.Donor_Type__c = 'Individual';
		//testContact.Send_Birthday_Email__c    = true;
		
		insert testContact;
		
		
		//BCJ.sendMail();
		
		String CRON_EXP = '0 0 0 3 9 ? 2022';
		String jobId = System.schedule('testBasicScheduledApex', CRON_EXP, new BirthdayCronJob());
        
		
		CronTrigger ct = [SELECT id, CronExpression, TimesTriggered, NextFireTime
							FROM CronTrigger 
							WHERE id = :jobId];
		System.assertEquals(CRON_EXP, ct.CronExpression);
	
		System.assertEquals(0, ct.TimesTriggered);
		
		//System.assertEquals('2022-09-03 00:00:00', String.valueOf(ct.NextFireTime));
		
		//delete testContact;
		
	}
}