force-app/main/default/objects/Contact/fields/Donor_Type__c.field-meta.xml
<CustomField>
    <fullName>Donor_Type__c</fullName>
    <defaultValue>if( $RecordType.DeveloperName = &apos;Contact&apos;, &apos;Organisation&apos;, null)</defaultValue>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Organisation</fullName>
            </value>
            <value>
                <fullName>Anonymous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Individual.recordType-meta.xml
<RecordType>
    <fullName>Individual</fullName>
    <active>true</active>
    <label>Individual</label>
</RecordType>

force-app/main/default/objects/Volunteer_Request__c/Volunteer_Request__c.object-meta.xml
<CustomObject>
    <label>Volunteer Request</label>
    <nameField>
        <label>Activity/Event</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Request__c/fields/Cancel_VR__c.field-meta.xml
<CustomField>
    <fullName>Cancel_VR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cancel VR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/fields/Others_Please_Indicate__c.field-meta.xml
<CustomField>
    <fullName>Others_Please_Indicate__c</fullName>
    <description>Change Label from Others (Please Indicate) based user Request</description>
    <label>Cancel Reason (Please Indicate)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/fields/Recruitment_Deadline__c.field-meta.xml
<CustomField>
    <fullName>Recruitment_Deadline__c</fullName>
    <label>Recruitment Deadline</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/recordTypes/Direct.recordType-meta.xml
<RecordType>
    <fullName>Direct</fullName>
    <active>true</active>
    <label>Direct</label>
</RecordType>

force-app/main/default/classes/AssignedTest.cls
@isTest
public class AssignedTest {
    @TestSetup
    static void makeData(){
        List<Contact> contactToInsertList = new List<Contact>{
            new Contact(
                RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId(),
                Donor_Type__c = 'Individual',
                lastName = 'Apple Pine 1',
                Email = 'apple1@email.com'
            ),
            new Contact(
                RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId(),
                Donor_Type__c = 'Individual',
                lastName = 'Apple Pine 2',
                Email = 'apple2@email.com'
            ),
            new Contact(
                RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId(),
                Donor_Type__c = 'Individual',
                lastName = 'Apple Pine 3',
                Email = 'apple3@email.com'
            )
        };

        Insert contactToInsertList;
    }

	@isTest static void TestUploadVolunteerController(){
        integer progNums = 1;
        List<Volunteer_Request__c> progList = new List<Volunteer_Request__c>();
        for(Integer i=0; i<progNums; i++) {
            Volunteer_Request__c v = new Volunteer_Request__c();
            v.Name = 'Test VR';
            v.Start_Date__c = Date.today().addDays(i+3);
            v.End_Date__c = Date.today().addDays(i+9);
            v.RecordTypeId = Schema.SObjectType.Volunteer_Request__c.getRecordTypeInfosByName().get('Direct').getRecordTypeId();
            v.Start_Time__c = Time.newInstance(5, 0, 0, 0);
            v.Recruitment_Deadline__c = Date.today();
            progList.add(v);
        }
        insert(progList);
        Volunteer_Request__c v = progList[0];
        v.Start_Date__c = Date.today().addDays(-30);
        v.End_Date__c = Date.today().addDays(-10);
        update(v);
        v.Start_Date__c = Date.today().addDays(1);
        v.End_Date__c = Date.today().addDays(5);
        update(v);
        v.Start_Date__c = Date.today().addDays(-1);
        v.End_Date__c = Date.today().addDays(5);
        update(v);
        Test.startTest();
        v.Cancel_VR__c = true;
        v.Others_Please_Indicate__c = 'testing';
        update(v);
        ApexPages.CurrentPage().getParameters().put('id', progList.get(0).Id);
        UploadVolunteerController uv = new UploadVolunteerController(new ApexPages.StandardController(progList.get(0)));
        String s = 	'Fulname,Email,Mobile'+
				   	'Apple Pine 1,apple1@email.com,99999747\n'+
					'Apple Pine 2,apple2@email.com,88888888\n'+
					'Apple Pine 3,apple3@email.com,99987455';
        uv.csvFileBody = Blob.valueOf(s);
        uv.back();
        uv.importCSVFile(); 
        String s1 = 	'Firstname,Email,Mobile\n'+
				   	'Apple Pine 1,apple1@email.com,99999747\n'+
					'Apple Pine 2,apple2@email.com,88888888\n'+
					'Apple Pine 3,apple3@email.com,99987455';
        uv.csvFileBody = Blob.valueOf(s1);
        uv.importCSVFile(); 
        String s2 = 	'"Fullname","Email","Mobile"\n'+
				   	'"Apple Pine 1","apple1@email.com","99999747"\n'+
					'"Apple Pine 2","apple2@email.com","88888888"\n'+
					'"Apple Pine 3","apple3@email.com","99987455"';
        uv.csvFileBody = Blob.valueOf(s2);
        uv.importCSVFile();
        VolunteerAcceptDeclineController pa = new VolunteerAcceptDeclineController(new ApexPages.StandardController(progList.get(0)));
        pa.pt.Assignee_Status__c = 'Selected';
        pa.refreshTable();
        pa.selectAll();
        pa.unselectAll();
        pa.selectAll();
        pa.acceptVolunteer();
        pa.declineVolunteer();
        pa.back();
        Test.stopTest();
    }
}