force-app/main/default/objects/Contact/fields/Donor_Type__c.field-meta.xml
<CustomField>
    <fullName>Donor_Type__c</fullName>
    <defaultValue>if( $RecordType.DeveloperName = &apos;Contact&apos;, &apos;Organisation&apos;, null)</defaultValue>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Organisation</fullName>
            </value>
            <value>
                <fullName>Anonymous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Donations__c/Donations__c.object-meta.xml
<CustomObject>
    <label>Donations</label>
    <nameField>
        <displayFormat>{yy}{mm}-{000000}</displayFormat>
        <label>Donation No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Donations__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donation_Amount__c.field-meta.xml
<CustomField>
    <fullName>Donation_Amount__c</fullName>
    <label>Donation Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donation_Date__c.field-meta.xml
<CustomField>
    <fullName>Donation_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Donation Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donation_Status__c.field-meta.xml
<CustomField>
    <fullName>Donation_Status__c</fullName>
    <defaultValue>&apos;Pending&apos;</defaultValue>
    <label>Donation Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Payment_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>Cheque Returned</fullName>
            </value>
            <value>
                <fullName>Giro Rejected</fullName>
            </value>
            <value>
                <fullName>CC Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donor_Account__c.field-meta.xml
<CustomField>
    <fullName>Donor_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Will be filled by trigger</description>
    <inlineHelpText>Don&apos;t need to be manually filled, will be automatically overwritten by trigger,</inlineHelpText>
    <label>Donor Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donor_Name__c.field-meta.xml
<CustomField>
    <fullName>Donor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the person who made the donation and paid for it</description>
    <label>Donor Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Donor_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donor_Type__c.field-meta.xml
<CustomField>
    <fullName>Donor_Type__c</fullName>
    <label>Donor Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Organisation</fullName>
            </value>
            <value>
                <fullName>Anonymous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Frequency_Type__c.field-meta.xml
<CustomField>
    <fullName>Frequency_Type__c</fullName>
    <defaultValue>&quot;One-time&quot;</defaultValue>
    <label>Frequency Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-time</fullName>
                <default>true</default>
                <label>One-time</label>
            </value>
            <value>
                <fullName>Recurring</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donations__c/fields/is_RD_Generated__c.field-meta.xml
<CustomField>
    <fullName>is_RD_Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>used to mark if this Donation is generated by RD
Intentionally not displayed on any page layout</description>
    <label>is RD Generated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>eNETS</fullName>
            </value>
            <value>
                <fullName>Giro</fullName>
            </value>
            <value>
                <fullName>PayNow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Recurring_Donation__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Donation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recurring Donation</label>
    <referenceTo>Recurring_Donation__c</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Tax_Deductible__c.field-meta.xml
<CustomField>
    <fullName>Tax_Deductible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tax Deductible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Tax_Recipient_Individual__c.field-meta.xml
<CustomField>
    <fullName>Tax_Recipient_Individual__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Recipient Individual</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Donations (Tax Recipient Contact)</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Tax_Recipient_Organisation__c.field-meta.xml
<CustomField>
    <fullName>Tax_Recipient_Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Recipient Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Donations (Tax Recipient Organisation)</relationshipLabel>
    <relationshipName>Donations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recurring_Donation__c/Recurring_Donation__c.object-meta.xml
<CustomObject>
    <label>Recurring Donation</label>
    <nameField>
        <displayFormat>RD{yymmdd}{0000}</displayFormat>
        <label>RD No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recurring Donations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Recurring_Donation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recurring Donations</relationshipLabel>
    <relationshipName>Recurring_Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recurring_Donation__c/fields/Donor_Name__c.field-meta.xml
<CustomField>
    <fullName>Donor_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Donor Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Recurring Donations</relationshipLabel>
    <relationshipName>Recurring_Donations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recurring_Donation__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bi monthly</fullName>
                <isActive>false</isActive>
                <label>Bi monthly</label>
            </value>
            <value>
                <fullName>Bi weekly</fullName>
                <isActive>false</isActive>
                <label>Bi weekly</label>
            </value>
            <value>
                <fullName>Half Yearly</fullName>
                <isActive>false</isActive>
                <label>Half Yearly</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
                <isActive>false</isActive>
                <label>Quarterly</label>
            </value>
            <value>
                <fullName>Weekly</fullName>
                <isActive>false</isActive>
                <label>Weekly</label>
            </value>
            <value>
                <fullName>Yearly</fullName>
                <isActive>false</isActive>
                <label>Yearly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recurring_Donation__c/fields/Next_Deduction_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Deduction_Date__c</fullName>
    <label>Next Deduction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Recurring_Donation__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Giro</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recurring_Donation__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Recurring_Donation__c/fields/Tax_Deductible__c.field-meta.xml
<CustomField>
    <fullName>Tax_Deductible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tax Deductible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Recurring_Donation__c/fields/Tax_Recipient_Individual__c.field-meta.xml
<CustomField>
    <fullName>Tax_Recipient_Individual__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Recipient Individual</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Recurring Donations (Tax Recipient Individual)</relationshipLabel>
    <relationshipName>Recurring_Donations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recurring_Donation__c/fields/Tax_Recipient_Organisation__c.field-meta.xml
<CustomField>
    <fullName>Tax_Recipient_Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Recipient Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recurring Donations (Tax Recipient Organisation)</relationshipLabel>
    <relationshipName>Recurring_Donations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recurring_Donation__c/fields/Total_Donation_to_Date__c.field-meta.xml
<CustomField>
    <fullName>Total_Donation_to_Date__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Donation to Date</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/RDTriggerHandler.cls
public with sharing class RDTriggerHandler {

    // run @before_insert
    public static void getAccountId(Recurring_Donation__c newRecord){
        newRecord.Account__c = [
            SELECT AccountId
            FROM Contact
            WHERE id = :newRecord.Donor_Name__c
        ].AccountId;
    }
    

    // Run @before_update
    public static void firstDonation(Recurring_Donation__c newRecord){
        newRecord.Next_Deduction_Date__c = getNextDeductionDate((Date)newRecord.Start_Date__c, newRecord.Frequency__c, true);
        newRecord.Total_Donation_to_Date__c = newRecord.Amount__c;
    }


    // Run @after_update
    public static void createNextDonation(Recurring_Donation__c newRecord, Recurring_Donation__c oldRecord){
        // 1. check if next donation already exist with status 'scheduled'
        List<donations__c> existingNextDonation = [
            SELECT ID, Donation_Date__c, Donation_Status__c
            FROM Donations__c
            WHERE Recurring_Donation__c = :oldRecord.id
                AND Donation_Date__c = :oldRecord.Next_Deduction_Date__c
                AND Donation_Status__c = 'Scheduled'
        ];

        // 2. if there are scheduled record, but payment have not been commited, then delete the records
        if(existingNextDonation.size() > 0){
            delete existingNextDonation;
        }

        // Logic #1 and #2 are used to anticipate if User manually changed next deduction date on SF platform
        // the logic will delete the latest scheduled donation 

        // 3. create the next donation base on Next_Deduction_Date__c
        createNewDonation(newRecord);
    }

    
    public static void createNewDonation(Recurring_Donation__c rDonation){
        Contact contactDetail = [
            SELECT Id, 	Donor_Type__c, name
            FROM Contact
            WHERE Id = :rDonation.Donor_Name__c
        ];

        Donations__c donation = new Donations__c(
            Frequency_Type__c = 'Recurring',
            Donation_Date__c = Date.valueOf(rDonation.Next_Deduction_Date__c),
            Donation_Status__c = 'Scheduled',
            Donation_Amount__c = rDonation.Amount__c,
            Donor_Account__c = rDonation.Account__c,
            Donor_Name__c = rDonation.Donor_Name__c,
            Donor_Type__c = contactDetail.Donor_Type__c,
            Payment_Method__c = rDonation.Payment_Method__c,
            Recurring_Donation__c = rDonation.id,
            Tax_Deductible__c = rDonation.Tax_Deductible__c,
            Tax_Recipient_Individual__c = rDonation.Tax_Recipient_Individual__c ,
            Tax_Recipient_Organisation__c = rDonation.Tax_Recipient_Organisation__c ,
            is_RD_Generated__c = true
        );


        Insert donation;
    }

    
    public static Date getNextDeductionDate(Date startDate, String frequency, Boolean noWeekEnd){
        Date deductionDate;
        try {
            if(startDate == null || frequency == null)
                throw new CustomException('Required value: [startDate, frequency]');
            else{
                switch on frequency {
                    when 'Monthly' {
                        deductionDate = startDate.addMonths(1);        
                    }
                    when 'Weekly' {
                        deductionDate = startDate.addDays(7);           
                    }
                    when 'Bi weekly' {
                        deductionDate = startDate.addDays(14);           
                    }
                    when 'Bi monthly' {
                        deductionDate = startDate.addMonths(2);           
                    }
                    when 'Quarterly' {
                        deductionDate = startDate.addMonths(3);           
                    }
                    when 'Half Yearly' {
                        deductionDate = startDate.addMonths(6);           
                    }
                    when 'Yearly' {
                        deductionDate = startDate.addYears(1);           
                    }
                    when else {
                        throw new CustomException('unRecognized Value');
                    }
                } 

                if(noWeekEnd){
                    // As of 20-09-2021, 
                    // for datetime.format('u'): Monday is 1, Sunday is 7
                    // anticipate error potential in the future if salesforce change monday to be 2 and sunday to be 1
                    Datetime dt = deductionDate;
                    Integer dayNumber = Integer.valueOf( dt.format('u') );
                    
                    if(dayNumber > 5 )
                        deductionDate = deductionDate.addDays(7-dayNumber+1);
                }

            }
        } catch (Exception e) {
            System.Debug('\n\n' + e);
        }

        return deductionDate;
    }

}