force-app/main/default/objects/Contact/fields/ID_No__c.field-meta.xml
<CustomField>
    <fullName>ID_No__c</fullName>
    <externalId>true</externalId>
    <label>Tax Recipient ID No</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/ID_Type__c.field-meta.xml
<CustomField>
    <fullName>ID_Type__c</fullName>
    <label>Tax Recipient ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NRIC</fullName>
            </value>
            <value>
                <fullName>FIN</fullName>
            </value>
            <value>
                <fullName>UEN-Business</fullName>
            </value>
            <value>
                <fullName>UEN-Local Company</fullName>
            </value>
            <value>
                <fullName>UEN-Others</fullName>
            </value>
            <value>
                <fullName>ITR</fullName>
            </value>
            <value>
                <fullName>ASGD</fullName>
            </value>
            <value>
                <fullName>OTHERS</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
                <isActive>false</isActive>
                <label>BC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ISS_Enquiry__c.field-meta.xml
<CustomField>
    <fullName>ISS_Enquiry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ISS Enquiry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Enquiry__c/Enquiry__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <displayFormat>EN-{YYYY}{MM}{DD}{00}</displayFormat>
        <label>Enquiry No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enquiry__c/fields/Client_Email__c.field-meta.xml
<CustomField>
    <fullName>Client_Email__c</fullName>
    <label>Client Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If this field is not blank, it means this record is tagged to the client record internally</inlineHelpText>
    <label>Client Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Enquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/ClientNameEntered__c.field-meta.xml
<CustomField>
    <fullName>ClientNameEntered__c</fullName>
    <description>Name (as per BC/NRIC)</description>
    <inlineHelpText>Name (as per BC/NRIC)</inlineHelpText>
    <label>Client Name (Entered)</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Number__c</fullName>
    <description>contact number client personal information</description>
    <label>Contact Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/ID_Type__c.field-meta.xml
<CustomField>
    <fullName>ID_Type__c</fullName>
    <label>ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>NRIC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Intake__c/Intake__c.object-meta.xml
<CustomObject>
    <label>Intake</label>
    <nameField>
        <displayFormat>IN-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Intake No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intake</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Intake__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <label>Client Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Intake</relationshipLabel>
    <relationshipName>Intake</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Intake__c/fields/Enquiry_No__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_No__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry No.</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Intake</relationshipLabel>
    <relationshipName>Intake</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Needs_Assessment__c/Needs_Assessment__c.object-meta.xml
<CustomObject>
    <label>Needs Assessment</label>
    <nameField>
        <displayFormat>NA-{yymmdd}-{00}</displayFormat>
        <label>NA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Needs Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Needs_Assessment__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Needs Assessments</relationshipLabel>
    <relationshipName>Needs_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Needs_Assessment__c/fields/Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Enquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Needs Assessments (Enquiry)</relationshipLabel>
    <relationshipName>Needs_Assessments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Needs_Assessment__c/fields/Intake_No__c.field-meta.xml
<CustomField>
    <fullName>Intake_No__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake No.</label>
    <referenceTo>Intake__c</referenceTo>
    <relationshipLabel>Needs Assessments</relationshipLabel>
    <relationshipName>Needs_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/enquiryISSTriggerHandler.cls
public with sharing class enquiryISSTriggerHandler {
    
    // TODO: change to bulkified
    public static void setContactandIntake(Enquiry__c[] newRecordList) {
        // check contact with email is exist or not
        // if not exist => create contact with ISS_Enquiry__c true
        // connect to intake
        // if exist, change record type with ISS_Enquiry__c true, and type change to Client
        // connect to intake

        for (Enquiry__c enItem: newRecordList) {
            // validate from inserting data, 
            // Client_Email__c  must not null to execute trigger
            if (enItem.Client_Email__c != null || enItem.Client_Email__c != '') {

                // check contact available or not or not
                Contact[] contacts = [SELECT Id, Name, RecordTypeId, ISS_Enquiry__c FROM Contact WHERE Email = :enItem.Client_Email__c];
                            
                Id contactId;

                if (contacts.size() > 0){
                    // contact exist
                    for (Contact cItem: contacts) {
                        //enquiryContactIds.add(cItem.Id);

                        cItem.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Client').getRecordTypeId();
                        cItem.ISS_Enquiry__c = true;

                        contactId = cItem.Id;
                    }

                    Database.update(contacts, false);
                } else {
                    List<Contact> contactToCreate = new List<Contact>();

                    contactToCreate.add(new Contact(
                        RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Client').getRecordTypeId(),
                        LastName = enItem.ClientNameEntered__c,
                        // ID_No__c = enItem.ID_Number__c, // Tax Recipient ID No  (delete soon)
                        // ID_Type__c = enItem.ID_Type__c, // Tax Recipient ID Type : NRIC, dll  (delete soon)
                        // Tax_Recipient_Full_Name__c= enItem.ClientNameEntered__c, // Tax_Recipient_Full_Name__c (delete soon)
                        Phone = enItem.Contact_Number__c,
                        Email = enItem.Client_Email__c,
                        ISS_Enquiry__c = true                   
                    ));

                    System.debug('contact to add \n');
                    System.debug(contactToCreate);

                    Database.SaveResult[] saveResult = Database.insert(contactToCreate, false);

                    for (Database.SaveResult sr : saveResult) {
                        if(sr.isSuccess()) {
                            contactId = sr.getId();
                        } else {
                            System.debug('error insert data contact\n' + sr.getErrors());
                        }
                    }
                }

                // create intake 
                List<Intake__c> intakeToCreate = new List<Intake__c>();

                intakeToCreate.Add(new Intake__c(
                    RecordTypeId = Schema.SObjectType.Intake__c.getRecordTypeInfosByName().get('Intake - ISS').getRecordTypeId(),
                    Client_Name__c = contactId,
                    Enquiry_No__c = enItem.id
                ));

                Database.SaveResult[] saveResult = Database.insert(intakeToCreate, false);
                for (Database.SaveResult sr : saveResult) {
                    if(sr.isSuccess()) {
                        System.debug('success insert Intake\n' + sr);
                    } else {
                        System.debug('error insert data intake\n' + sr.getErrors());
                    }
                }
            }
        }
    }

    // TODO: change to bulkified
    public static void setNeedAssessment(Enquiry__c[] newRecordList) {

        for (Enquiry__c neItem: newRecordList) {
            // create need assessment 

            // get IntakeID
            String intakeId;

            List<Intake__c> intakeRecord = [SELECT Id, Name FROM Intake__c WHERE Enquiry_No__c = :neItem.Id];

            for (Intake__c inItem : intakeRecord) {
                intakeId = inItem.Id;
            }

            List<Needs_Assessment__c> needAssessmentToCreate = new List<Needs_Assessment__c>();

            needAssessmentToCreate.Add(new Needs_Assessment__c(
                Enquiry__c = neItem.Id,
                Intake_No__c = intakeId
            ));

            Database.SaveResult[] saveResult = Database.insert(needAssessmentToCreate, false);
            for (Database.SaveResult sr : saveResult) {
                if(sr.isSuccess()) {
                    System.debug('success insert need assessment\n' + sr);
                } else {
                    System.debug('error insert data need assessment\n' + sr.getErrors());
                }
            }
        }
    }
}