force-app/main/default/objects/Contact/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <label>Remarks</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Birthday_Programme__c.field-meta.xml
<CustomField>
    <fullName>Birthday_Programme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Birthday Programme</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Programme_Event__c.field-meta.xml
<CustomField>
    <fullName>Programme_Event__c</fullName>
    <label>Programme/ Event</label>
    <referenceTo>Programme_Events__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Programme_Events__c/Programme_Events__c.object-meta.xml
<CustomObject>
    <label>Programme/ Event</label>
    <nameField>
        <label>Programme/ Events Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programme/ Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Programme_Events__c/fields/Active_Birthday_Programme__c.field-meta.xml
<CustomField>
    <fullName>Active_Birthday_Programme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active Birthday Programme</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Programme_Events__c/fields/Programme_Stage__c.field-meta.xml
<CustomField>
    <fullName>Programme_Stage__c</fullName>
    <label>Programme Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BirthdayCronJob.cls
global class BirthdayCronJob implements Schedulable{ 
	
	global void execute(SchedulableContext SC) {
    	Contact[] contacts = [SELECT Id, email, Birthdate
	        				FROM Contact 
	        				WHERE DAY_IN_MONTH(Birthdate) = : date.today().day() 
							AND CALENDAR_MONTH(Birthdate) = : date.today().month()   
	        				];
		List<Programme_Events__c> bdProgramme = [SELECT Id, Active_Birthday_Programme__c FROM Programme_Events__c WHERE Active_Birthday_Programme__c = true AND Programme_Stage__c != 'Cancelled' limit 1];
        if(bdProgramme != null){
            List<Participant__c> pList = [SELECT Id, Contact_Name__c, Programme_Event__c FROM Participant__c WHERE Programme_Event__c = :bdProgramme.get(0).Id AND Contact_Name__c IN :contacts];
            Set<Id> partExist = new Set<Id>();
            if(pList != null){
                for(Participant__c p : pList){
                    p.Birthday_Programme__c = true;
                    partExist.add(p.Contact_Name__c);
                }
            }
            for(Contact c : contacts) {
                if(!partExist.contains(c.Id)){
                    // create participant record
                    Participant__c p = new Participant__c();
                    p.Contact_Name__c = c.Id;
                    p.Programme_Event__c = bdProgramme.get(0).Id;
                    p.Birthday_Programme__c = true;
                    p.Remarks__c = 'Participant for donate Birthday';
                    pList.add(p);
                }
            } 
            upsert(pList);
        }
        
	}
}