force-app/main/default/objects/Enquiry__c/Enquiry__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <displayFormat>EN-{YYYY}{MM}{DD}{00}</displayFormat>
        <label>Enquiry No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enquiry__c/fields/Client_Email__c.field-meta.xml
<CustomField>
    <fullName>Client_Email__c</fullName>
    <label>Client Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/ClientNameEntered__c.field-meta.xml
<CustomField>
    <fullName>ClientNameEntered__c</fullName>
    <description>Name (as per BC/NRIC)</description>
    <inlineHelpText>Name (as per BC/NRIC)</inlineHelpText>
    <label>Client Name (Entered)</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Direct_Contact_No__c.field-meta.xml
<CustomField>
    <fullName>Direct_Contact_No__c</fullName>
    <label>Direct Contact No</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Email_Refererrer__c.field-meta.xml
<CustomField>
    <fullName>Email_Refererrer__c</fullName>
    <label>Email (Refererrer)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Enquiry_Option__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Option__c</fullName>
    <label>Enquiry Option</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Full_Name_Referrer__c.field-meta.xml
<CustomField>
    <fullName>Full_Name_Referrer__c</fullName>
    <label>Full Name (Referrer)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Name_of_Organisation__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Organisation__c</fullName>
    <label>Name of Organisation</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EnquiryiSSTriggerHandlerTest.cls
@isTest
public class EnquiryiSSTriggerHandlerTest {
    @isTest
    public static void testEnqISSTrigger() {
        Enquiry__c newEnquiry = new Enquiry__c(
            Client_Email__c = 'testtest@mail.com',
            ClientNameEntered__c = 'testtest',
            Full_Name_Referrer__c = 'referrer-test',
            Email_Refererrer__c = 'referrer-test@mail.com',
            Designation__c = 'designation',
            Direct_Contact_No__c = '111111',
            Name_of_Organisation__c = 'testaktiv',
            Department__c = 'testing',
            Enquiry_Option__c = 'LS Services'
        );

        Database.SaveResult saveResult  = Database.insert(newEnquiry);
        System.assertEquals(true, saveResult.isSuccess());
    }
}