force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Donations__c/Donations__c.object-meta.xml
<CustomObject>
    <label>Donations</label>
    <nameField>
        <displayFormat>{yy}{mm}-{000000}</displayFormat>
        <label>Donation No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Donations__c/fields/Donor_Name__c.field-meta.xml
<CustomField>
    <fullName>Donor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the person who made the donation and paid for it</description>
    <label>Donor Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Donor_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Recurring_Donation__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Donation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recurring Donation</label>
    <referenceTo>Recurring_Donation__c</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recurring_Donation__c/Recurring_Donation__c.object-meta.xml
<CustomObject>
    <label>Recurring Donation</label>
    <nameField>
        <displayFormat>RD{yymmdd}{0000}</displayFormat>
        <label>RD No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recurring Donations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Recurring_Donation__c/fields/Donor_Name__c.field-meta.xml
<CustomField>
    <fullName>Donor_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Donor Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Recurring Donations</relationshipLabel>
    <relationshipName>Recurring_Donations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/devSandbox.cls
public with sharing class devSandbox {
    public static void deleteAllJap(){
        Map<Id, Contact> contactJap = new Map<Id, Contact>([
            SELECT Id, AccountId
            FROM Contact
            WHERE lastName LIKE '%jap%' 
                OR lastName LIKE '%hendy%'
                OR lastName Like '%wijaya%'
                OR lastName Like '%jhw%'
        ]);

        delete new List<Donations__c>([
            SELECT Id 
            FROM Donations__c
            WHERE Donor_Name__c IN :contactJap.keySet()
        ]);

        delete new List<Recurring_Donation__c>([
            SELECT Id
            FROM Recurring_Donation__c
            WHERE Donor_Name__c IN :contactJap.keySet()
        ]);

        Set<Id> accountIdToDeleteSet = new Set<Id>();
        for(Contact cItem : contactJap.values()){
            accountIdToDeleteSet.add(cItem.AccountId);
        }

        List<Account> accountToDeleteList = new List<Account>();
        for(Id accountId : accountIdToDeleteSet){
            accountToDeleteList.add( new Account(
                id = accountId
            ));
        }

        delete accountToDeleteList;
    }

   




    
}