force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Email_Sent__c</fullName>
    <label>Email Sent</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Invitation_Link__c.field-meta.xml
<CustomField>
    <fullName>Invitation_Link__c</fullName>
    <formula>$Label.Landing_URL + &quot;volunteer-program?id=&quot;+Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invitation Link</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Participant_Name__c.field-meta.xml
<CustomField>
    <fullName>Participant_Name__c</fullName>
    <formula>Contact_Name__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Participant Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Program_Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Event_Name__c</fullName>
    <formula>Programme_Event__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program/ Event Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Programme_Event__c.field-meta.xml
<CustomField>
    <fullName>Programme_Event__c</fullName>
    <label>Programme/ Event</label>
    <referenceTo>Programme_Events__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Selected</fullName>
                <default>true</default>
                <label>Selected</label>
            </value>
            <value>
                <fullName>Invitation Sent</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Absent</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Withdraw</fullName>
                <label>Withdrawn</label>
            </value>
            <value>
                <fullName>Registered</fullName>
                <isActive>false</isActive>
                <label>Registered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Programme_Events__c/Programme_Events__c.object-meta.xml
<CustomObject>
    <label>Programme/ Event</label>
    <nameField>
        <label>Programme/ Events Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programme/ Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Programme_Events__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ad-hoc</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Fortnightly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Programme_Events__c/fields/Programme_Description__c.field-meta.xml
<CustomField>
    <fullName>Programme_Description__c</fullName>
    <label>Programme Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Programme_Events__c/fields/Programme_Remarks__c.field-meta.xml
<CustomField>
    <fullName>Programme_Remarks__c</fullName>
    <label>Programme Remarks</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Programme_Events__c/fields/Programme_Stage__c.field-meta.xml
<CustomField>
    <fullName>Programme_Stage__c</fullName>
    <label>Programme Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Programme_Events__c/fields/Programme_Title__c.field-meta.xml
<CustomField>
    <fullName>Programme_Title__c</fullName>
    <label>Programme Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/Volunteer_Request__c.object-meta.xml
<CustomObject>
    <label>Volunteer Request</label>
    <nameField>
        <label>Activity/Event</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Request__c/fields/Programme_Event__c.field-meta.xml
<CustomField>
    <fullName>Programme_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programme/ Event</label>
    <referenceTo>Programme_Events__c</referenceTo>
    <relationshipLabel>Volunteer Requests</relationshipLabel>
    <relationshipName>Volunteer_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer_Request__c/fields/Programme_Stage__c.field-meta.xml
<CustomField>
    <fullName>Programme_Stage__c</fullName>
    <formula>TEXT(Programme_Event__r.Programme_Stage__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Programme Stage</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchSendParticipantEmail.cls
global class BatchSendParticipantEmail implements Database.Batchable<sObject> {
	global String query;
    global String objName;
    global String errorMsg;
    global String volIds;
    global String templateId;
    global String vrId;
    
    global BatchSendParticipantEmail(String vIds, String tId, String vreqId){
        query = 'SELECT Id,name'+
                ',Contact_Name__r.firstname'+
            	',Contact_Name__r.Name'+
                ',Contact_Name__r.lastname'+
                ',Contact_Name__r.Email'+
                ',Contact_Name__r.Phone'+
                ',Contact_Name__r.MobilePhone'+
                ',Status__c'+
                ',Contact_Name__c'+
                ',CreatedById'+
                ',Email_Sent__c'+
            	',Email__c'+
                ',Programme_Event__c'+
                ',Invitation_Link__c'+
            	',Participant_Name__c'+
                ' FROM Participant__c'+
                ' WHERE Id IN '+vIds;
        volIds = vIds;
        system.debug('=======ericca debug query========'+query);
        templateId = tId; 
        vrId = vreqId;
    }
    
    global Database.QueryLocator start (Database.BatchableContext bc){
        system.debug('=======ericca debug query========'+volIds);
        return Database.getQueryLocator(query);
    }
    
    global void execute (Database.BatchableContext bc, List<SObject> scope){
        System.debug('lstRI before = ' + scope );  
        //Set<Id> pIds = new Set<Id>();
        if(scope.size()>0){
            Set<id> contIds = new Set<Id>();
            /*for(SObject s : scope){
                pIds.add((Id)s.get('Contact_Name__c'));
            }*/
            EmailTemplate emailTemp =[SELECT subject,Body,DeveloperName,Id,HTMLValue  FROM EmailTemplate where id=:templateId LIMIT 1];
        	List<Programme_Events__c> L = [ SELECT Id,name
                                            ,End_Date_Time__c 
                                            ,Frequency__c
                                            ,Programme_Remarks__c
                                            ,Start_Date_Time__c
                                            ,Programme_Stage__c
                                            ,Programme_Title__c 
                                            ,Programme_Description__c
                                          	,Owner.Name
                                            FROM Programme_Events__c WHERE Id = :vrId
                                          ];
            //Map<Id, Contact> contactMap = new Map<Id, Contact>([SELECT Id, Name, Email, Phone, MobilePhone, Passcode__c 
            //                                                    FROM Contact WHERE Id IN :pIds]);
            
            for(SObject S : scope){  
                Datetime startDatetime = L[0].Start_Date_Time__c;
                Datetime endDatetime = L[0].End_Date_Time__c;
                
                String emsg;
                String esub;
                if(emailTemp.Subject != null){
                    esub = emailTemp.Subject;
                    esub = (L[0].name <> null) ? esub.replace('{!Volunteer_Request__c.Name}', L[0].name) : esub.replace('{!Volunteer_Request__c.Name}', '');
                } else {
                    esub = '';
                }
                
                if(!Test.isRunningTest()){emsg = emailTemp.HtmlValue;}
                else{emsg = emailTemp.Body;}
                
                emsg = (L[0].Name <> null) ? emsg.replace('{!Programme_Event__c.Name}', L[0].Name) : emsg.replace('{!Programme_Event__c.Name}', '');
                emsg = (L[0].Name <> null) ? emsg.replace('{!Participant__c.Program_Event_Name__c}', L[0].Name) : emsg.replace('{!Participant__c.Program_Event_Name__c}', '');

                emsg = (L[0].Programme_Description__c <> null) ? emsg.replace('{!Programme_Event__c.Programme_Description__c}', L[0].Programme_Description__c) : emsg.replace('{!Programme_Event__c.Programme_Description__c}', '');
                emsg = (L[0].Owner.Name <> null) ? emsg.replace('{!Programme_Event__c.Owner_name__c}', L[0].Owner.Name) : emsg.replace('{!Programme_Event__c.Owner_name__c}', '');

                String strname = (String)s.get('Participant_Name__c');
                esub = (L[0].Start_Date_Time__c <> null) ? esub.replace('{!Programme_Event__c.Start_Date_Time__c}', startDatetime.format('dd-MMM-yyyy hh:mm a')) : esub.replace('{!Programme_Event__c.Start_Date_Time__c}', '');
                emsg = (L[0].Start_Date_Time__c <> null) ? emsg.replace('{!Programme_Event__c.Start_Date_Time__c}', startDatetime.format('dd-MMM-yyyy hh:mm a')) : emsg.replace('{!Programme_Event__c.Start_Date_Time__c}', '');
                emsg = (L[0].End_Date_Time__c <> null) ? emsg.replace('{!Programme_Event__c.End_Date_Time__c}', enddatetime.format('dd-MMM-yyyy hh:mm a')) : emsg.replace('{!Programme_Event__c.End_Date_Time__c}', '');
            	     
                emsg = (strname <> null) ? emsg.replace('{!Participant__c.Contact_Name__c}', strname) : emsg.replace('{!Participant__c.Contact_Name__c}', '');
                emsg = ((String)s.get('Invitation_Link__c') <> null) ? emsg.replace('{!Participant__c.Invitation_Link__c}', (String)s.get('Invitation_Link__c')) : emsg.replace('{!Participant__c.Invitation_Link__c}', '');
            	
                List<String> toemail = new List<String>();
                toemail.add((String)s.get('Email__c'));
            	Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            	email.setToAddresses(toemail); 
                email.setHtmlBody(emsg); 
            	email.setSubject(esub);
            	Messaging.SendEmailResult [] results = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
                
                s.put('Email_sent__c', Date.today());
                if(s.get('Status__c') == 'Selected') s.put('Status__c', 'Invitation Sent');
            }
            if(!Test.isRunningTest())update(scope);  
        }
    }
    
    global void finish (Database.BatchableContext bc){
        
    }
}