force-app/main/default/objects/Donations__c/Donations__c.object-meta.xml
<CustomObject>
    <label>Donations</label>
    <nameField>
        <displayFormat>{yy}{mm}-{000000}</displayFormat>
        <label>Donation No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Donations__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Cleared_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Cleared_Datetime__c</fullName>
    <label>Cleared Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donation_Amount__c.field-meta.xml
<CustomField>
    <fullName>Donation_Amount__c</fullName>
    <label>Donation Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donation_Date__c.field-meta.xml
<CustomField>
    <fullName>Donation_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Donation Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donation_Status__c.field-meta.xml
<CustomField>
    <fullName>Donation_Status__c</fullName>
    <defaultValue>&apos;Pending&apos;</defaultValue>
    <label>Donation Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Payment_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>Cheque Returned</fullName>
            </value>
            <value>
                <fullName>Giro Rejected</fullName>
            </value>
            <value>
                <fullName>CC Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donor_Account__c.field-meta.xml
<CustomField>
    <fullName>Donor_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Will be filled by trigger</description>
    <inlineHelpText>Don&apos;t need to be manually filled, will be automatically overwritten by trigger,</inlineHelpText>
    <label>Donor Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donor_Name__c.field-meta.xml
<CustomField>
    <fullName>Donor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the person who made the donation and paid for it</description>
    <label>Donor Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Donor_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donor_Type__c.field-meta.xml
<CustomField>
    <fullName>Donor_Type__c</fullName>
    <label>Donor Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Organisation</fullName>
            </value>
            <value>
                <fullName>Anonymous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Frequency_Type__c.field-meta.xml
<CustomField>
    <fullName>Frequency_Type__c</fullName>
    <defaultValue>&quot;One-time&quot;</defaultValue>
    <label>Frequency Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-time</fullName>
                <default>true</default>
                <label>One-time</label>
            </value>
            <value>
                <fullName>Recurring</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Id_No__c.field-meta.xml
<CustomField>
    <fullName>Id_No__c</fullName>
    <formula>Donor_Name__r.ID_No__c</formula>
    <label>Donor Id No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>eNETS</fullName>
            </value>
            <value>
                <fullName>Giro</fullName>
            </value>
            <value>
                <fullName>PayNow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DonationReconcilController.cls
public class DonationReconcilController {
    public Donations__c donation {get;set;}
    public Donations__c donation1 {get;set;}
    public List<Donations__c> donationList {get;set;}
    public List<DonationObj> donationObjList {get;set;}
    public Id Id{get;set;}
    public Decimal totalDonation {get;set;}
    public Decimal selectedDonation{get;set;}
    public boolean frequencyTypeOnetime {get; set;}
    public boolean frequencyTypeRecurring {get; set;}
    
    public DonationReconcilController (ApexPages.StandardController controller){
        Id = ApexPages.CurrentPage().getParameters().get('id');
        donation = new Donations__c();
        donation1 = new Donations__c();
        donation.Cleared_Date__c = Date.today();
        donation.Donation_Status__c = null;
        donation.Frequency_Type__c = null;
        totalDonation = 0;
        selectedDonation = 0;
    }
    
    public void selectAll(){
        for(DonationObj obj : donationObjList){
            obj.updated = true;
        }
        selectedDonation = totalDonation ;
    }
    
    public void unselectAll(){
        for(DonationObj obj : donationObjList){
            obj.updated = false;
        }
        selectedDonation = 0;
    }
    
    public void search(){
        selectedDonation = 0;
        totalDonation = 0;
        String query = 'SELECT Id, Name, Donation_Date__c, 	Donor_Account__c, Donor_Name__c, ID_no__c, Amount__c, Donation_Status__c, Cleared_Date__c, Cleared_Datetime__c, Frequency_Type__c, Donation_Amount__c, Donor_type__c FROM Donations__c WHERE ';
        boolean andclaus = false; //Channel_of_Donations__c,  Donation_Purpose__c, 
        if(donation.Donation_Date__c <> null){
            Datetime dt = Datetime.newInstance(donation.Donation_Date__c.year(), donation.Donation_Date__c.month(), donation.Donation_Date__c.day());
            query += ' Donation_Date__c >=  '+dt.format('yyyy-MM-dd');
            andclaus = true;
        }
        if(donation.Cleared_Date__c <> null){
            Datetime dt = Datetime.newInstance(donation.Cleared_Date__c.year(), donation.Cleared_Date__c.month(), donation.Cleared_Date__c.day());
            if(andclaus){
                query += ' AND ';
            }
            query += ' Donation_Date__c <= '+dt.format('yyyy-MM-dd');
        }
        if(donation.Donation_Status__c != null){
            if(andclaus){
                query += ' AND ';
            }
            query += ' Donation_Status__c = \''+donation.Donation_Status__c+'\'' ;
            andclaus = true;
        }
        /*if(donation.Frequency_Type__c!= null){
            if(andclaus){
                query += ' AND ';
            }
            query += ' Frequency_Type__c = \''+donation.Frequency_Type__c+'\'';
            andclaus = true;
        }*/
        if(frequencyTypeOnetime == true && frequencyTypeRecurring == true){
        }else if(frequencyTypeOnetime == true){
            if(andclaus){
                query += ' AND ';
            }
            query += ' Frequency_Type__c = \'One-Time\'';
            andclaus = true;
        }else if(frequencyTypeRecurring == true){
            if(andclaus){
                query += ' AND ';
            }
            query += ' Frequency_Type__c = \'Recurring\'';
            andclaus = true;
        }
        if(donation.Payment_Method__c != null){
            if(andclaus){
                query += ' AND ';
            }
            query += 'Payment_Method__c = \''+donation.Payment_Method__c+'\'';
            andclaus = false;
        }
        /*if(donation.Channel_of_Donations__c != null){
            if(andclaus){
                query += ' AND ';
            }
            query += 'Channel_of_Donations__c = \''+donation.Channel_of_Donations__c+'\'';
            andclaus = false;
        }*/
        query += ' ORDER BY Donation_Date__c';
        system.debug('================='+query);
        donationList = Database.query(query);
        
        if(donationList != null){
            donationObjList = new List<DonationObj>();
            for(Donations__c d : donationList){
                totalDonation += d.Donation_Amount__c;
                DonationObj obj = new DonationObj(d);
                donationObjList.add(obj);
            }
        }
    }
    
    public PageReference back(){
        pageReference pg = new pageReference('/'+Id);
        pg.setRedirect(true);
        return pg;
    }
    
    public PageReference save(){
        integer iselect = 0;
        List<Donations__c> updatedDonation = new List<Donations__c>();
        for(DonationObj obj: donationObjList){
            if(obj.updated == true){
                Donations__c p = obj.don;
                p.Donation_Status__c = donation1.Donation_Status__c;
                if( donation1.Donation_Status__c == 'Cleared'){
                    p.Cleared_Datetime__c = Datetime.now();
                }
                else if( donation1.Donation_Status__c != 'Cleared' ){
                    p.Cleared_Datetime__c = null;
                }
                updatedDonation.add(p);
                iselect++;
            }
        }
        try{
            if(iselect == 0){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'No Volunteer selected.'));
            }else{
                update(updatedDonation);
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, updatedDonation.size()+ ' donation is updated.'));
            }
        }catch(Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Error: Unable to update this Donation. ERROR CODE:'+e.getMessage()));
        }
        
        return null;
    }
    
    public void calculateSelected(){
        selectedDonation = 0; 
        for(DonationObj obj: donationObjList){
            if(obj.updated == true){
                selectedDonation += obj.don.Donation_Amount__c;
            }
        }
    }
    public class DonationObj {
        public boolean updated {get;set;}
        public Donations__c don {get;set;}
        
        public DonationObj(Donations__c d){
            updated = false;
            don = d;
        }
    }
    
    
}