force-app/main/default/objects/Donations__c/Donations__c.object-meta.xml
<CustomObject>
    <label>Donations</label>
    <nameField>
        <displayFormat>{yy}{mm}-{000000}</displayFormat>
        <label>Donation No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Donations__c/fields/Cleared_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Cleared_Datetime__c</fullName>
    <label>Cleared Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donation_Amount__c.field-meta.xml
<CustomField>
    <fullName>Donation_Amount__c</fullName>
    <label>Donation Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donation_Date__c.field-meta.xml
<CustomField>
    <fullName>Donation_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Donation Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donation_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Donation_Datetime__c</fullName>
    <label>Donation Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donation_Status__c.field-meta.xml
<CustomField>
    <fullName>Donation_Status__c</fullName>
    <defaultValue>&apos;Pending&apos;</defaultValue>
    <label>Donation Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Payment_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>Cheque Returned</fullName>
            </value>
            <value>
                <fullName>Giro Rejected</fullName>
            </value>
            <value>
                <fullName>CC Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donor_Type__c.field-meta.xml
<CustomField>
    <fullName>Donor_Type__c</fullName>
    <label>Donor Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Organisation</fullName>
            </value>
            <value>
                <fullName>Anonymous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Email_Entered__c.field-meta.xml
<CustomField>
    <fullName>Email_Entered__c</fullName>
    <label>Email (Entered)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Full_Name_Entered__c.field-meta.xml
<CustomField>
    <fullName>Full_Name_Entered__c</fullName>
    <label>Full Name (Entered)</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>eNETS</fullName>
            </value>
            <value>
                <fullName>Giro</fullName>
            </value>
            <value>
                <fullName>PayNow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donations__c/recordTypes/Cash.recordType-meta.xml
<RecordType>
    <fullName>Cash</fullName>
    <active>true</active>
    <label>Cash</label>
</RecordType>

force-app/main/default/classes/FixerPatchTest.cls
@isTest
public with sharing class FixerPatchTest {
    @testSetup
    static void makeData(){
        List<Donations__c> donationToInsertList = new List<Donations__c>{
            new Donations__c(
                RecordTypeId = Schema.SObjectType.Donations__c.getRecordTypeInfosByName().get('Cash').getRecordTypeId(),
                Donor_Type__c = 'Individual',
                Donation_Status__c = 'Cleared',
                Donation_Date__c = System.today(),
                Donation_Datetime__c = System.now(),
                Cleared_Datetime__c = System.now(),
                Full_Name_Entered__c = 'Test 1',
                Email_Entered__c = 'test1@mail.com',
                Donation_Amount__c = 100,
                Payment_Method__c = 'Credit Card'
            )
        };

        insert donationToInsertList;
    }


    @isTest
    public static void fixDuplicateTaxReceiptNoTest(){
        FixerPatch.fixDuplicateTaxReceiptNo();
    }
}