force-app/main/default/objects/Donations__c/Donations__c.object-meta.xml
<CustomObject>
    <label>Donations</label>
    <nameField>
        <displayFormat>{yy}{mm}-{000000}</displayFormat>
        <label>Donation No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Donations__c/fields/Donor_Account__c.field-meta.xml
<CustomField>
    <fullName>Donor_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Will be filled by trigger</description>
    <inlineHelpText>Don&apos;t need to be manually filled, will be automatically overwritten by trigger,</inlineHelpText>
    <label>Donor Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donor_Name__c.field-meta.xml
<CustomField>
    <fullName>Donor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the person who made the donation and paid for it</description>
    <label>Donor Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Donor_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/sendDonationResponseEmailBatchable.cls
public with sharing class sendDonationResponseEmailBatchable implements Database.Batchable<SObject>{
    public String query;
    public String emailTemplateName;
    public List<Id> donationIdList = new List<Id>();

    public sendDonationResponseEmailBatchable(List<Donations__c> donationList, String emailTemplateName){
        for(Donations__c dItem : donationList){
            this.donationIdList.add(dItem.id);
        }

        query = 'SELECT Id, Donor_Name__c, Donor_Account__c '
            + 'FROM Donations__c '
            + 'WHERE '
            + 'Id in :donationIdList';

        this.emailTemplateName = emailTemplateName;
    }

    
    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }


    public void execute(Database.BatchableContext BC, List<Donations__c> donationList){

        for(Donations__c dItem : donationList){
            Utils.sendSingleEmailTemplate(dItem.Donor_Name__c, emailTemplateName, dItem.id);
        }
    }


    public void finish(Database.BatchableContext BC){
        System.debug('\n\nSend Donation response email in batch done \n');
    }


}