force-app/main/default/objects/Donations__c/Donations__c.object-meta.xml
<CustomObject>
    <label>Donations</label>
    <nameField>
        <displayFormat>{yy}{mm}-{000000}</displayFormat>
        <label>Donation No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Donations__c/fields/Cleared_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Cleared_Datetime__c</fullName>
    <label>Cleared Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Donor_Name__c.field-meta.xml
<CustomField>
    <fullName>Donor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the person who made the donation and paid for it</description>
    <label>Donor Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Donor_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Old_Tax_Receipt_No__c.field-meta.xml
<CustomField>
    <fullName>Old_Tax_Receipt_No__c</fullName>
    <description>This field is used to record the old tax receipt no that was caused by duplication prior to May 2022 update</description>
    <label>(Old) Tax Receipt No.</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Tax_Receipt_No__c.field-meta.xml
<CustomField>
    <fullName>Tax_Receipt_No__c</fullName>
    <inlineHelpText>If the prefix is T, it is a tax-deductible donation
If the prefix is N, it is a non-tax deductible donation</inlineHelpText>
    <label>Tax Receipt No.</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donations__c/fields/Tax_Receipt_Running_No__c.field-meta.xml
<CustomField>
    <fullName>Tax_Receipt_Running_No__c</fullName>
    <label>Tax Receipt Running No</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FixerPatch.cls
public with sharing class FixerPatch {
    // 1. clear running number from ALL record
    // 2. copy existing 'tax receipt no' to field 'old number'
    // 3. regen on the existing 'tax receipt no', starting from 1
    // - utilizing the trigger function, it is temporary modified to only generate tax receipt no on donation cleared after 2021-12-31
    // - revert the trigger function to the normal one
    public static void fixDuplicateTaxReceiptNo(){
        List<Donations__c> donationToFixList = [
            SELECT Id, Tax_Receipt_No__c, Old_Tax_Receipt_No__c, Tax_Receipt_Running_No__c
            FROM Donations__c
            WHERE Donor_Name__c != null
                AND (
                    Tax_Receipt_Running_No__c != null
                    OR Tax_Receipt_No__c != null
                )
            ORDER BY Cleared_Datetime__c ASC
        ];

        for(Donations__c dItem : donationToFixList){
            dItem.Tax_Receipt_Running_No__c = null;
            dItem.Old_Tax_Receipt_No__c = dItem.Tax_Receipt_No__c;
            dItem.Tax_Receipt_No__c = null;
        }

        if(donationToFixList.size() > 0){
            Update(donationToFixList);
        }
    }
}