force-app/main/default/objects/Intake__c/Intake__c.object-meta.xml
<CustomObject>
    <label>Intake</label>
    <nameField>
        <displayFormat>IN-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Intake No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intake</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Intake__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <label>Client Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Intake</relationshipLabel>
    <relationshipName>Intake</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Intake__c/fields/Enquiry_No__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_No__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry No.</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Intake</relationshipLabel>
    <relationshipName>Intake</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Needs_Assessment__c/Needs_Assessment__c.object-meta.xml
<CustomObject>
    <label>Needs Assessment</label>
    <nameField>
        <displayFormat>NA-{yymmdd}-{00}</displayFormat>
        <label>NA No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Needs Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Needs_Assessment__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Needs Assessments</relationshipLabel>
    <relationshipName>Needs_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Needs_Assessment__c/fields/Enquiry_Id__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry Id</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Needs Assessments</relationshipLabel>
    <relationshipName>Needs_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Needs_Assessment__c/fields/Intake_No__c.field-meta.xml
<CustomField>
    <fullName>Intake_No__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake No.</label>
    <referenceTo>Intake__c</referenceTo>
    <relationshipLabel>Needs Assessments</relationshipLabel>
    <relationshipName>Needs_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Questionnaire_Item__c/Questionnaire_Item__c.object-meta.xml
<CustomObject>
    <label>Questionnaire Item</label>
    <nameField>
        <displayFormat>QI-{0000}</displayFormat>
        <label>Questionnaire Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questionnaire Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Questionnaire_Item__c/fields/Assessment_Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Questionnaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Questionnaire</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Questionnaire Items</relationshipLabel>
    <relationshipName>Questionnaire_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Questionnaire_Item__c/fields/Needs_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Needs_Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Needs Assessment</label>
    <referenceTo>Needs_Assessment__c</referenceTo>
    <relationshipLabel>Questionnaire Items</relationshipLabel>
    <relationshipName>Questionnaire_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Questionnaire_Item__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <formula>Assessment_Questionnaire__r.Order_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/NeedAssessmentTriggerHandler.cls
public with sharing class NeedAssessmentTriggerHandler {

    public static void updateIntakeIDandEnquiryID(List<Needs_Assessment__c> newRecords) {
        try {
            // TODO: update to bulkified
            List<Needs_Assessment__c> naAfterInserts = new List<Needs_Assessment__c>();
 
            for (Needs_Assessment__c nAItem: newRecords) {
                if (String.isNotBlank(nAItem.Intake_No__c)) {
                    List<Intake__c> intakeRecord = [SELECT Id, Name, Enquiry_No__c, Client_Name__c FROM Intake__c WHERE Id = :nAItem.Intake_No__c];

                    Id enqId;
                    Id clientId;

                    for (Intake__c iItem: intakeRecord ){
                        enqId = iItem.Enquiry_No__c;
                        clientId = iItem.Client_Name__c;
                    }

                    Needs_Assessment__c naNew = new Needs_Assessment__c(Id = nAItem.Id);
                    
                    naNew.Enquiry_Id__c = enqId;
                    naNew.Client_Name__c = clientId;

                    naAfterInserts.add(naNew);
                } 
            }   

            Database.update(naAfterInserts, false);
            
        } catch (Exception err) {
            System.debug('\n\nError NeedsAssessment Handler');
            System.debug('Message : ' + err.getMessage());
            System.debug('Line Number : ' + err.getLineNumber());
            Trigger.new[0].addError(err.getMessage());
        }
    }

    // TODO: change to bulkified
    public static void generateQuestions(Needs_Assessment__c[] newRecords) {
        List<Integer> orderQuestions = new List<Integer>();

        // set selection all question from order number 1 to 44, 
        // 1 - 22, need assessment question
        // 23 - 37, other communication skill
        // 38 - 44, first row
        for (Integer i = 1 ; i <= 47 ; i++) {
            orderQuestions.Add(i);
        }
        
        for (Needs_Assessment__c naItem: newRecords) {
            // create list question for need assessmet

            List<Question__c> questions = [SELECT Id, Name FROM Question__c WHERE Order_Number__c IN :orderQuestions ORDER BY Order_Number__c ASC];

            // create new Questionaire items
            List<Questionnaire_Item__c> insertQuestionaires = new List<Questionnaire_Item__c>();

            // comparing with question items created before
            List<Questionnaire_Item__c> existsQuestionaires = [SELECT Id, Name, Assessment_Questionnaire__r.Order_Number__c, Needs_Assessment__c, Needs_Assessment__r.Name 
                FROM Questionnaire_Item__c 
                WHERE Needs_Assessment__c = :naItem.Id
                ORDER BY Assessment_Questionnaire__r.Order_Number__c ASC];

            for(Question__c qItem: questions) {
                Boolean exist = false;
                
                // check existing questionaire
                // avoid duplicate question in need assessment
                for (Questionnaire_Item__c existQItem: existsQuestionaires) {
                    if (existQItem.Assessment_Questionnaire__r.Order_Number__c == qItem.Order_Number__c) {
                        exist = true;
                        break;
                    }
                }

                if(exist) {
                    continue;
                } else {
                    insertQuestionaires.Add(new Questionnaire_Item__c(
                        Needs_Assessment__c = naItem.Id,
                        Assessment_Questionnaire__c = qItem.Id
                    ));
                }
            }

            Database.SaveResult[] saveResult = Database.insert(insertQuestionaires, false);
            for (Database.SaveResult sr : saveResult) {
                if (sr.isSuccess()) {
                    System.debug('success insert data questionaire\n' + sr);
                } else {
                    System.debug('error insert data question in need assessmnet enquiry\n' + sr.getErrors());
                }
            }
        }

    }   
}