force-app/main/default/objects/Intake__c/Intake__c.object-meta.xml
<CustomObject>
    <label>Intake</label>
    <nameField>
        <displayFormat>IN-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Intake No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intake</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Intake__c/fields/Intake_Status__c.field-meta.xml
<CustomField>
    <fullName>Intake_Status__c</fullName>
    <label>Intake Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Started</fullName>
                <default>true</default>
                <label>Started</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Proceed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Intake__c/fields/Verifier_Email__c.field-meta.xml
<CustomField>
    <fullName>Verifier_Email__c</fullName>
    <label>Verifier Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/IntakeTriggerHandler.cls
public with sharing class IntakeTriggerHandler {
    
    // TODO: update to bulkified
    public static void UpdateIntakeStatus(List<Intake__c> newRecordList) {
        for (Intake__c intakeItem : newRecordList) {        
            if(intakeItem.Approved__c == true && intakeItem.Verifier_Email__c != null && intakeItem.Approver_Email__c != null) {
               intakeItem.Intake_Status__c = 'Proceed';
            } else if (intakeItem.Verifier_Email__c != null && intakeItem.Approver_Email__c != null) {
                intakeItem.Intake_Status__c = 'Processing';
            }
        }
    }
       
}